### ISSUE TITLE
Нет Readme

### ISSUE THREAD

**Issue by hawk911** [salexdv/bsl_console#1]
Как подключить или как воспользоваться данной фичей?

**Comment by salexdv** [comment]
Просто запустите index.html из каталога src. Если используете Chrome, то запускать его нужно с ключом --allow-file-access-from-files. Для других браузеров надо смотреть.
Добавлю в Readme

**Comment by salexdv** [comment]
> Как подключить или как воспользоваться данной фичей?

Просто запустите index.html из каталога src. Если используете Chrome, то запускать его нужно с ключом --allow-file-access-from-files. Для других браузеров надо смотреть.
Добавлю в Readme
