### ISSUE TITLE
Получение списка выбора при нажатии .

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#10]
Это бы сократило инициализацию
аналогичный вопрос:
https://github.com/Pr-Mex/VAEditor/issues/107#issuecomment-664778815

**Comment by salexdv** [comment]
> Это бы сократило инициализацию
> аналогичный вопрос:
> [Pr-Mex/VAEditor#107 (comment)](https://github.com/Pr-Mex/VAEditor/issues/107#issuecomment-664778815)

Не очень понял, что нужно сделать. Сейчас так и работает. [Вот пример](https://github.com/salexdv/git_images/blob/master/bslconsole_catalog_comletition.gif?raw=true)

**Comment by Evg-lylyk** [comment]
Сейчас идет ЗаполнитьКоллекциюМетаданныхНаСервере() в момент запуска уже все заполнено.
Лучше изначально не заполнять а при нажатии . дополнять
Метаданные   "." - обратится в 1С получить МД, аналогично для другого Перечисления, Предопределенные элементы и т.д.

**Comment by Evg-lylyk** [comment]
Еще глобальный контекста очень большой, может возможно какую то часть получить при обращении

**Comment by salexdv** [comment]
> Сейчас идет ЗаполнитьКоллекциюМетаданныхНаСервере() в момент запуска уже все заполнено.
> Лучше изначально не заполнять а при нажатии . дополнять
> Метаданные "." - обратится в 1С получить МД, аналогично для другого Перечисления, Предопределенные элементы и т.д.

Так работает только тогда, когда нет **БСП** и модуля **ДлительныеОперации**. Если длительные операции есть, то загрузка происходит в фоне. Если получать структуру метаданных только при обращении к ним, то точно будет тормозить - это ведь вызов с клиента на сервер и потом еще время на обновление данных в JS.

**Comment by salexdv** [comment]
> Еще глобальный контекст очень большой, может возможно какую то часть получить при обращении

Если имеется в виду описание всех процедур, классов и перечислений встроенного языка, то там действительно около 2-3 Мб, но на загрузку в 1С это не влияет практически никак. Только что ради интереса провел замер. С загрузкой всего описания html документ формируется за 1399 мс, а без за 1250 мс. Разница в 0.1 сек ну не серьезна, честное слово.

**Comment by Evg-lylyk** [comment]
"происходит в фоне. Если получать структуру метаданных только при обращении к ним, то точно будет тормозить - это ведь вызов с клиента на сервер и потом еще время на обновление данных в JS"
В фоне это хорошо, но можно не делать
"точно будет тормозить" будет очень маленький объем данных

**Comment by Evg-lylyk** [comment]
> > Еще глобальный контекст очень большой, может возможно какую то часть получить при обращении
> 
> Если имеется в виду описание всех процедур, классов и перечислений встроенного языка, то там действительно около 2-3 Мб, но на загрузку в 1С это не влияет практически никак. Только что ради интереса провел замер. С загрузкой всего описания html документ формируется за 1399 мс, а без за 1250 мс. Разница в 0.1 сек ну не серьезна, честное слово.
Поставил замер перед открытием
![image](https://user-images.githubusercontent.com/48444742/88659657-1745f800-d0de-11ea-83eb-c317992271fe.png)

**Comment by Evg-lylyk** [comment]
Может стоит попробовать архив без сжатия сделать, для имеющегося кода

**Comment by salexdv** [comment]
> Может стоит попробовать архив без сжатия сделать, для имеющегося кода

Попробую

**Comment by salexdv** [comment]
> "происходит в фоне. Если получать структуру метаданных только при обращении к ним, то точно будет тормозить - это ведь вызов с клиента на сервер и потом еще время на обновление данных в JS"
> В фоне это хорошо, но можно не делать
> "точно будет тормозить" будет очень маленький объем данных
Дело не в объеме. Сначала в JS надо определить какой объект метаданных нужен, передать его в 1С, затем в 1С-ке будет вызов с клиента на сервер и обратно в JS. Это во-первых. Во-вторых надо будет переписать чуть ли не всё, чтобы в monaco, когда вызывается провайдер для автокомплита реализовать эту схему. В данный момент вызывается провайдер, который ищет данные уже в готовом объекте со всеми метаданными, а придется делать разрыв на то, чтобы 1С-ка еще что-то вернула.

**Comment by Evg-lylyk** [comment]
Не силен в тонкостях ява, но это хороший подход расходует меньше памяти, нет инициализации...

**Comment by salexdv** [comment]
> Не силен в тонкостях ява, но это хороший подход расходует меньше памяти, нет инициализации...

Этот подход может и хорош в теории, но на практике это куча костылей и клиент-серверных вызовов, вместо того, чтобы подождать 1-2 секунды инициализации и дальше не видеть вообще никаких тормозов в подсказках. Вы вполне можете доработать консоль под себя. Файл с метаданными можно формировать заранее, если напрягает его формирование при открытии обработки, тогда всё станет еще быстрее.

> Может стоит попробовать архив без сжатия сделать, для имеющегося кода

Это особо ни на что не влияет т.к. файл из макета всё равно надо положить во временное хранилище, а потом извлечь. Если архив без сжатия, то извлекаться из архива всё будет быстрее, но помещение/извлечение из хранилища будет дольше. В [новом релизе](https://github.com/salexdv/bsl_console/releases/tag/v0.1.6) извлечение исходников происходит только при изменении версии обработки, либо при самом первом запуске. Это дает ускорение.

**Comment by salexdv** [comment]
Еще немного доработал механизм получение метаданных. Теперь на клиенте из временного хранилища сразу получается готовая JSON-строка с описанием метаданных, т.е. не тратиться время на запись структуры в JSON и получение текста из файла, как это было сделано раньше.
