### ISSUE TITLE
Подсказка при наведении (HOVER) не скрывается автоматически пока курсор не отведешь на 10 пикселей от границы окна

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#100]
Из-за этого, если на имени функции появилась такая подсказка, то перемещение курсора вправо на один из ее параметров не вызывает подсказку удержания заново. Приходится довольно далеко уводить курсор вверх и затем возвращать его вниз на параметр. Было бы удобнее уменьшить это расстояние хотя бы в 2 раза.

![изображение](https://user-images.githubusercontent.com/11896251/117560831-e4cc2100-b099-11eb-8883-c6074400976b.png)

**Comment by salexdv** [comment]
Я не могу влиять на данные настройки
