### ISSUE TITLE
Нужна функция для вызова подсказки по вызову метода 

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#102]
Например хочу вызывать эту подсказку при выполнении пользователем моей команды в 1С

![изображение](https://user-images.githubusercontent.com/11896251/117581939-4e831400-b108-11eb-9145-a0afbf42fbcd.png)

**Comment by salexdv** [comment]
Добавил функцию [`triggerSigHelp()`](https://github.com/salexdv/bsl_console/blob/develop/docs/trigger_signature_help.md)

**Comment by tormozit** [comment]
Заработало.
