### ISSUE TITLE
Хочу автоматической окраски особым фоном вхождений текущего слова

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#103]
Сейчас при выделении слова все его вхождения в тексте окрашиваются фоном выделения.
Хочется аналогичной возможности (но с другим цветом) для текущего слова, чтобы написав слово, можно было увидеть сразу все его вхождения в видимой области текста.
Обе возможности присутствуют во встроенном редакторе кода платформы.

![изображение](https://user-images.githubusercontent.com/11896251/117638895-01488600-b18c-11eb-992c-7bc6109f338a.png)

**Comment by salexdv** [comment]
> Обе возможности присутствуют во встроенном редакторе кода платформы.

Можно подробнее?

**Comment by tormozit** [comment]
![изображение](https://user-images.githubusercontent.com/11896251/117803352-34a81500-b25f-11eb-8647-2614ea90856b.png)

**Comment by salexdv** [comment]
Похоже на глюк webkit в самой платформе 1С т.к. в браузере текущий идентификатор выделяется всегда даже без двойного клика
![GKI3Y88Lag](https://user-images.githubusercontent.com/6356534/117825136-ba37bf00-b277-11eb-95a5-af29deffc308.gif)

**Comment by tormozit** [comment]
Очень полезная фича. Будет обидно, если такой мощный редактор останется лишен ее в окнах 1С.

**Comment by salexdv** [comment]
Выделение вхождений текущего слова происходит, если в начале строк с текущим словом есть пробел или табуляция.
Выделение происходит через класс `selectionHighlight`, который в случае отсутствия пробела по какой-то причине не появляется у элемента в DOM.

![Безымянный](https://user-images.githubusercontent.com/6356534/140796160-b609f947-7820-42ef-be2f-bed77ede4768.png)

Причем работает это странно. Иногда достаточно добавить пробел, затем удалить его и выделение продолжает работает корректно. В браузере ничего подобного не наблюдается. С чем связано такое поведение пока выяснить не удалось.
