### ISSUE TITLE
Работа в веб-клиенте

### ISSUE THREAD

**Issue by Maribobah** [salexdv/bsl_console#11]
Не работает в веб-клиенте. Падает при открытии поскольку вызываются неподдерживаемые методы работы с JSON.
Хотелось бы иметь поддержку этого режима работы, поскольку не всегда есть возможность подключиться к тонкому клиенту.

**Comment by salexdv** [comment]
Сразу вспомнился мем
![мем](https://user-images.githubusercontent.com/6356534/88651237-232bbd00-d0d2-11ea-90da-b9d73dfddfbc.jpg)
Подумаю, как исправить.

**Comment by salexdv** [comment]
К сожалению сделать полноценную работу в веб-клиенте не получается. В [этом релизе](https://github.com/salexdv/bsl_console/releases/tag/v0.1.7) можно только редактировать код, никакое взаимодействие 1С и редактора, увы, недоступно. Иногда редактор в веб-клиенте запускается только после того, как в соседней вкладке была открыта [данная](https://salexdv.github.io/bsl_console/src/index.html) ссылка.

**Comment by Maribobah** [comment]
Жаль конечно, ну ладно
