### ISSUE TITLE
После клика  на гиперссылке и вызова hideHoverList() в окне подсказки удержания (HOVER) фокус ввода не возвращается в редактор

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#110]
После клика на гиперссылке и вызова hideHoverList() в окне подсказки удержания (HOVER)
```
		ИначеЕсли Событие.event = "EVENT_ON_LINK_CLICK" Тогда
			РедакторHTML.hideHoverList();

```
![изображение](https://user-images.githubusercontent.com/11896251/117927064-59a19400-b302-11eb-82cb-b41790603d01.png)

Фокус ввода не возвращается в редактор.

**Comment by tormozit** [comment]
Способ обхода понятен. Хочется чтобы это само происходило.

**Comment by tormozit** [comment]
Попробовал разные способы вернуть фокус. Не помогает.
```
РедакторHTML.editor.focus();
РедакторHTML.focus();
ЭтаФорма.ТекущийЭлемент = Элемент;
```

**Comment by salexdv** [comment]
Добавил возврат фокуса

**Comment by tormozit** [comment]
Столкнулся с проблемой. После обработки клика на гиперссылке некорректно отрабатывает метод setSelectionByLength().
Например есть текст
```
//
	Массив = Новый Массив;
	Массив.Добавить(1);
```
Если я по кнопке в форме 1С выполняю код
`РедакторHTML.setSelectionByLength(9, 24);`
то выделяется так
![изображение](https://user-images.githubusercontent.com/11896251/118030579-2bf23480-b36e-11eb-8eae-f4642af7a4e8.png)
а если делаю то же самое при обработке клика
```
РедакторHTML.hideHoverList();
РедакторHTML.setSelectionByLength(9, 24);
```
то выделяется так 
![изображение](https://user-images.githubusercontent.com/11896251/118030749-5fcd5a00-b36e-11eb-876a-ddd294014ba1.png)

**Comment by salexdv** [comment]
Не смог воспроизвести. Ниже вариант с выделением по кнопке, результат такой, же как у тебя на последнем
![GLWVWsFoJ8](https://user-images.githubusercontent.com/6356534/118129712-33b0e800-b405-11eb-9b05-a1a5c2220fc8.gif)
Вот вариант с обработкой клика по ссылке:
![ZwkdfwrQoE](https://user-images.githubusercontent.com/6356534/118129797-4cb99900-b405-11eb-9978-e04a009efeec.gif)
Не понимаю, как ты получил такай вариант выделения:

![](https://user-images.githubusercontent.com/11896251/118030579-2bf23480-b36e-11eb-8eae-f4642af7a4e8.png)

**Comment by tormozit** [comment]
Виноват. Косяк был в моем коде. Не достаточно изолировал его при очистке примера воспроизведения.
