### ISSUE TITLE
Сочетание CTRL+L должно удалять выделенные строки по аналогии со встроенным редактором

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#111]
Встроенный редактор кода платформы удаляет выделенные строки при нажатии CTRL+L. Хочется аналогичного поведения.

**Comment by salexdv** [comment]
> Встроенный редактор кода платформы удаляет выделенные строки при нажатии CTRL+L. Хочется аналогичного поведения.

Для этого есть сочетание клавиш CTRL+Del

**Comment by tormozit** [comment]
Нужна совместимость с оригинальным редактором, чтобы пользователю не приходилось переучиваться и переключать набор сочетаний клавиш у себя в памяти при переключении между редакторами.  Я могу конечно добавить свою команду в 1С, но считаю что пользователи будут сильнее любить твой редактор, если там все будет максимально привычно.

**Comment by salexdv** [comment]
Добавил

**Comment by tormozit** [comment]
Заработало
