### ISSUE TITLE
Свойство ReadOnly стало возвращать Неопределено

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#112]
Не заметил с какой версии это началось. Но думаю что совсем недавно.
После вызова 

`РедакторHTML.setReadOnly(Истина)`

оно (свойство ReadOnly) все равно возвращает Неопределено. 
Раньше точно работало, т.е. возвращало значение типа Булево.

**Comment by salexdv** [comment]
Функция setReadOnly никогда не возвращала значения т.к. в этом нет смысла, всё равно вернётся то, что передано в параметре

**Comment by tormozit** [comment]
Суть проблемы я описал в заголовке. Она касается свойства, а не функции. Функцию я привел лишь для иллюстрации отсутствия возможности обойти проблему.

**Comment by salexdv** [comment]
> Суть проблемы я описал в заголовке. Она касается свойства, а не функции. Функцию я привел лишь для иллюстрации отсутствия возможности обойти проблему.

Что за свойство `ReadOnly`? Есть readOnlyMode, его можно прочитать и оно нормально работает. Правда это свойство я особо нигде не декларировал. В 1С ты и так должен знать только чтение у тебя или нет т.к. ты на основании чего то же его устанавливаешь и сам отслеживаешь состояние.

**Comment by tormozit** [comment]
Да. Ты свойство ReadOnly не декларировал. Но тогда непонятно как текущее установленное функцией setReadOnly значение потом прочитать. Буду использовать readOnlyMode. Прошу добавить его в документацию.
Дублировать хранение установленного значения в 1С кажется неправильным.

**Comment by salexdv** [comment]
Добавил функцию `getReadOnly()`

**Comment by tormozit** [comment]
Заработало
