### ISSUE TITLE
Проблемы на LINUX

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#116]
У меня нет Linux. Но хотелось бы примерно понимать, какие проблемы препятствуют работе редактора на Linux?

**Comment by salexdv** [comment]
> У меня нет Linux. Но хотелось бы примерно понимать, какие проблемы препятствуют работе редактора на Linux?

webkit в 1С под linux не поддерживает тот стандарт JavaScript, который необходим для корректной работы, поэтому для запуска текущий код нужно транспилировать в более старый стандарт. Для этого потребуется немного поменять архитектуру

**Comment by salexdv** [comment]
#18
