### ISSUE TITLE
Хочу отображать описания для всех слов в списке автодополнения одновременно

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#119]
![изображение](https://user-images.githubusercontent.com/11896251/118354334-45b09900-b573-11eb-9320-81fe24140b3a.png)

**Comment by salexdv** [comment]
Попробуй вызывать вот так:
```js
enableSuggestActivationEvent(true, true)
```

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
В таком режим длинные имена свойств ожидаемо плохо различимы. Может быть для него можно увеличить ширину окна списка?

![изображение](https://user-images.githubusercontent.com/11896251/118562580-a1e30b00-b775-11eb-9ce7-f63b216b45e6.png)

![изображение](https://user-images.githubusercontent.com/11896251/118562585-a3acce80-b775-11eb-8f6c-5dbf19e80329.png)

**Comment by salexdv** [comment]
>  В таком режим длинные имена свойств ожидаемо плохо различимы. Может быть для него можно увеличить ширину окна списка?

Динамически сделать это нормально сложно. Если очень надо, можешь добавить в decoration.css что-то вроде
```css
.monaco-editor .suggest-widget {
    width: 600px;
}
````

**Comment by tormozit** [comment]
С шириной 500 пикселей стало нормально. Но если переключаюсь в режим отображения детальной информации по текущей строке, то все равно ширина крайне малая. 

![изображение](https://user-images.githubusercontent.com/11896251/121803056-5aeb1700-cc48-11eb-95ea-c622b26e8fd0.png)

Ее как то можно изменить?

**Comment by salexdv** [comment]
> Ее как то можно изменить?

При показе детальной информации ширина считается иначе. Точного алгоритма я не скажу, но по ощущениям можно умножать на 2 примерно т.е. для примера выше надо еще в **decoration.css** дописать следующее:

```css
.monaco-editor .suggest-widget.docs-side {
    width: 1200px;
}
```

**Comment by tormozit** [comment]
Помогло.

**Comment by tormozit** [comment]
Функция enableSuggestActivationEvent исчезла. Как теперь решается эта задача?

**Comment by tormozit** [comment]
Вроде как вместо нее теперь надо использовать SetOption, но у нее нет второго параметра https://github.com/salexdv/bsl_console/issues/247

**Comment by tormozit** [comment]
Вроде бы нашел новую опцию для замены второго параметра - alwaysDisplaySuggestDetails https://github.com/salexdv/bsl_console/blob/develop/docs/set_option.md . Но пока не смог проверить из-за других проблем.
