### ISSUE TITLE
Конструктор запроса

### ISSUE THREAD

**Issue by d-hurricane** [salexdv/bsl_console#12]
Текст запроса, возвращаемый конструктором, вставляется в исходный код "как есть":
- не учитывается отступ первой строки, все последующие строки вставляются без отступа;
- не экранируются кавычки при использовании строковых литералов в тексте запроса.

Также при повторной попытке открыть текст запроса конструктором предлагается создать новый в случае, если текста запроса содержит строковые литералы.

**Comment by salexdv** [comment]
Проверю и исправлю

**Comment by d-hurricane** [comment]
Подскажите, я хоть туда написал? :-) А то я пишу про обработку, сейчас смотрю, что в репозитории то ее и нет. И вроде как issue не в тему получается.

**Comment by salexdv** [comment]
Да, туда. Сама обработка выкладывается только в [релизах](https://github.com/salexdv/bsl_console/releases). В исходниках только JS код, который используется для работы.

**Comment by salexdv** [comment]
> * не экранируются кавычки при использовании строковых литералов в тексте запроса.

Будет исправлено в новом релизе.
> * не учитывается отступ первой строки, все последующие строки вставляются без отступа;

Это правильное поведение

**Comment by d-hurricane** [comment]
> Это правильное поведение

Но это же неудобно. Некоторые разработчики используют отступ относительно основного кода, да и в условиях/циклах все время поправлять придется.
```bsl
Запрос = Новый Запрос;

// Отступ относительно того же блока кода.
Запрос.Текст =
	"ВЫБРАТЬ
|	Т.Ссылка
|ИЗ
|	Справочник.Номенклатура КАК Т";

// Отступ в теле условного оператора.
Если НекоеУсловие() Тогда

	Запрос.Текст = "ВЫБРАТЬ
|	Т.Ссылка
|ИЗ
|	Справочник.Номенклатура КАК Т";

КонецЕсли;
```
Уточню, что под отступом для первой строки текста запроса я подразумеваю не позицию открывающих кавычек текста, а именно отступ всей инструкции, где начинается текст запроса.

**Comment by salexdv** [comment]
> Но это же неудобно. Некоторые разработчики используют отступ относительно основного кода, да и в условиях/циклах все время поправлять придется.

Согласен. Подумаю, как это можно реализовать.
