### ISSUE TITLE
Хочу справа от точки при нажатии точки при открытом списке автодополнения вставлять текущее слово списка и точку

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#120]
Например стою справа от "Справочники.БанковскиеСчета.СоздатьЭлемент().". Вызываю через CTRL+SPACE открытие списка автодополнения. Активирую строку списка "БанкДляРасчетов". Нажимаю клавишу "."

![изображение](https://user-images.githubusercontent.com/11896251/118354424-acce4d80-b573-11eb-8c3b-efd3aba30a4b.png)

Хочу чтобы при этом вставилось слово "БанкДляРасчетов." и снова открылся список подсказки автодополнения.

![изображение](https://user-images.githubusercontent.com/11896251/118354545-3251fd80-b574-11eb-9c7f-c4dea4df5ab3.png)

**Comment by salexdv** [comment]
```js
setActiveSuggestionAcceptors('.')
```
После такого вызова должно заработать

**Comment by salexdv** [comment]
> После такого вызова должно заработать

К сожалению, работает это только в браузере. В webkit внутри 1С своё видение кодов клавиш. Буду рассматривать другие варианты реализации.

**Comment by salexdv** [comment]
Готово

**Comment by tormozit** [comment]
Работает, но не вызывается событие EVENT_ON_SELECT_SUGGEST_ROW . Я же своим алгоритмом выполняю вставку. Хочется единообразия выполнения вставки выбранного слова.

**Comment by salexdv** [comment]
> не вызывается событие EVENT_ON_SELECT_SUGGEST_ROW 

Добавил

**Comment by tormozit** [comment]
Заработало. Но есть ожидаемое неудобство - при нажатии точки всегда происходит вставка, а иногда нужно будет вставить точку. Предлагаю в этом режиме (ну или всегда) при нажатии CTRL+"." вставлять ".", т.е. без вставки активного слова списка. Ну или нужен другой простой способ вставить просто ".".

**Comment by tormozit** [comment]
Есть еще проблемка. В событии EVENT_ON_SELECT_SUGGEST_ROW я могу добавить скобки и переставить каретку. Поэтому хотелось бы, чтобы ты вставлял точку только если каретка стоит справа от идентификатора, а лучше дай мне рычаг управления вставкой точки после слова через параметр события.

![изображение](https://user-images.githubusercontent.com/11896251/118597836-edb5a480-b7b5-11eb-8a12-d5fb488b924d.png)

**Comment by salexdv** [comment]
> Есть еще проблемка. В событии EVENT_ON_SELECT_SUGGEST_ROW я могу добавить скобки после вставки слова и переставить каретку. Поэтому хотелось бы, чтобы ты вставлял точку только если каретка стоит справа от идентификатора, а лучше дай мне рычаг управления вставкой точки после слова через параметр события.

Событие генерируемое для 1С (EVENT_ON_SELECT_SUGGEST_ROW) никак не может влиять на событие нажатия в браузере (onkeypress), поэтому подобный параметр в событии я просто не могу реализовать. Всё что ты можешь сделать, это программно выделить точку и заменить её на пустое значение.

**Comment by tormozit** [comment]
> программно выделить точку и заменить её на пустое значение

Как я пойму, что это надо сделать? Или же как мне отличить умышленную вставку точки от твоей?

**Comment by tormozit** [comment]
> Событие генерируемое для 1С (EVENT_ON_SELECT_SUGGEST_ROW) никак не может влиять на событие нажатия в браузере (onkeypress), поэтому подобный параметр в событии я просто не могу реализовать.

Тогда прошу при нажатии "." вставлять только слово и добавить в событииEVENT_ON_SELECT_SUGGEST_ROW параметр с нажатой клавишей (Отмена/Выбор/ВЫборСТочкой).

**Comment by salexdv** [comment]
> > программно выделить точку и заменить её на пустое значение
> 
> Как я пойму, что это надо сделать? Или же как мне отличить умышленную вставку точки от твоей?

В  событии триггер будет иметь вид не просто `selection`, а `force-selection-[Char]`, где `[Char]` - символ, зарегистрированный через `setActiveSuggestionAcceptors`, нажатие которого сгенерировало событие

**Comment by salexdv** [comment]
> > Событие генерируемое для 1С (EVENT_ON_SELECT_SUGGEST_ROW) никак не может влиять на событие нажатия в браузере (onkeypress), поэтому подобный параметр в событии я просто не могу реализовать.
> 
> Тогда прошу при нажатии "." вставлять только слово и добавить в событии EVENT_ON_SELECT_SUGGEST_ROW параметр с типом нажатой клавиши (Отмена/Выбор/ВыборСТочкой) и можно даже модификаторы ALT/SHIFT/CTRL. А я уже сам добавлю, если надо, точку и открою список автодополнения (вроде же в API есть метод для ее принудительного вызова?).

Сделал так, чтобы точка не вставлялась. 
Модификаторы ALT/SHIFT/CTRL в события EVENT_ON_ACTIVATE_SUGGEST_ROW и EVENT_ON_SELECT_SUGGEST_ROW я вставил, но при `CTRL+.` они не имеют значения т.к. нажатие `CTRL+либой символ` в принципе не вызывает onkeypress в браузере. Вот при выборе пункта подсказки через ALT/SHIFT/CTRL+Entrer они будут передаваться

**Comment by salexdv** [comment]
> > > Событие генерируемое для 1С (EVENT_ON_SELECT_SUGGEST_ROW) никак не может влиять на событие нажатия в браузере (onkeypress), поэтому подобный параметр в событии я просто не могу реализовать.
> > 
> > 
> > Тогда прошу при нажатии "." вставлять только слово и добавить в событии EVENT_ON_SELECT_SUGGEST_ROW параметр с типом нажатой клавиши (Отмена/Выбор/ВыборСТочкой) и можно даже модификаторы ALT/SHIFT/CTRL. А я уже сам добавлю, если надо, точку и открою список автодополнения (вроде же в API есть метод для ее принудительного вызова?).
> 
> Сделал так, чтобы точка не вставлялась.
> Модификаторы ALT/SHIFT/CTRL в события EVENT_ON_ACTIVATE_SUGGEST_ROW и EVENT_ON_SELECT_SUGGEST_ROW я вставил, но при `CTRL+.` они не имеют значения т.к. нажатие `CTRL+любой символ` в принципе не вызывает onkeypress в браузере. Вот при выборе пункта подсказки через ALT/SHIFT/CTRL+Entrer они будут передаваться

Всё это, конечно, немного похоже на костыль, но webkit, который в 1С, увы, ведет себе не всегда так, как этого ожидаешь.

**Comment by tormozit** [comment]
В событии EVENT_ON_SELECT_SUGGEST_ROW вызываю triggerSuggestions и там вложенно вызывается showCustomSuggestions и событие EVENT_BEFORE_SHOW_SUGGEST. Код отрабатывает, но окно списка не появляется.

**Comment by salexdv** [comment]
> В событии EVENT_ON_SELECT_SUGGEST_ROW после собственной вставки точки вызываю triggerSuggestions() и там вложенно в событии EVENT_BEFORE_SHOW_SUGGEST вызывается showCustomSuggestions(). Код отрабатывает, но окно списка не появляется. Видимо у тебя это окно закрывается насильно после выброса EVENT_ON_SELECT_SUGGEST_ROW. Есть идеи как мне заново сразу открыть список автодополнения?

Твои цепочки событий всё тяжелее становится воспроизвести ))
Попробуй пока вызвать showCustomSuggestions через обработку ожидания с задержкой в 100 мс. В зависимости от результата буду смотреть, что делать дальше.

**Comment by tormozit** [comment]
Через задержку 100мс работает, но это большой костыль. Такое я не могу включить в релиз. Там возникает лишнее ожидание и возможна двойная/лишняя обработка события EVENT_BEFORE_SHOW_SUGGEST, если пользователь успеет ввести символ или переместить каретку за эти 100мс.

По поводу воспроизведения подготовил выгрузку базы https://www.hostedredmine.com/attachments/408434 . Запускать так 
![изображение](https://user-images.githubusercontent.com/11896251/118686584-cccc6e00-b80c-11eb-9130-9110818315ab.png)
В модуле формы Обработка.ирКонсольКода ставь точку останова на строке
`РедакторHTML.triggerSuggestions(); // Так список не появляется на экране`

**Comment by salexdv** [comment]
> Через задержку 100мс работает, но это большой костыль. Такое я не могу включить в релиз.

Я понимаю, что костыль. Попросил сделать так только для того, чтобы понять из-за чего такое происходит. Подумаю, как решить.

**Comment by salexdv** [comment]
В общем потратил просто уйму времени на то, чтобы решить проблему, но такая цепочка событий, как у тебя работать нормально отказывается. Проблема в том, что список подсказок есть и при нажатии точки происходит выбор пункта внутри редактора, одновременно с этим вызывается `EVENT_ON_SELECT_SUGGEST_ROW`, где у тебя вызывается `hideSuggestionsList() `  и `triggerSuggestions`. Видимо, где-то внутри происходит обработка выбора пункта, и тут список и этот пункт пропадают. Что-то при этом клинится, хотя никаких ошибок нет.
Решение такое. Добавил функцию для установки опциональных настроек и немного доработал механизм выбора активной подсказки по клавиши. Т.к. ты сам вставляешь текст при выборе `EVENT_ON_SELECT_SUGGEST_ROW`, то и стандартная вставка, которая происходила до этого тебе не нужна. При инициализации редактора (`РедакторHTML_Инициировать`) допиши следующее:
```js
// Отключаем вставку точки
РедакторHTML.setOption("skipInsertSuggestionAcceptor", true);
// Отключаем стандартную обработку вставки активного пункта подсказки. Практически 'СтандартнаяОбработка = Ложь'
РедакторHTML.setOption("skipAcceptionSelectedSuggestion", true);
```
После этого всё должно заработать

**Comment by tormozit** [comment]
Большое спасибо. Заработало. Вставку точкой полюбили многие пользователи моей старой подсказки. Поэтому они будут очень рады сохранению этой удобной фичи.

**Comment by tormozit** [comment]
Эта фича при почти постоянно открытом окне автодополнения дает слишком много нежелательных срабатываний. Поэтому пришлось ее отключить.
