### ISSUE TITLE
Есть ли способ проверить что поле редактора сейчас в фокусе ввода?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#121]
8.3.14-19
У формы 1С есть метод ВводДоступен(). Он проверят фокус ввода формы, т.е. нажатия клавиш попадают ли в какой либо элемент этой формы. Но если активно поле HTML документа, то этот метод возвращает всегда Ложь. Я эту ошибку отправил в 1С https://partners.v8.1c.ru/forum/topic/1943796 . Но думаю ждать исправления придется долго. А пока его нет нужно как то определять что ввод в поле HTML документа доступен. Можно ли сделать в редакторе аналогичный метод?

**Comment by salexdv** [comment]
Добавил функцию `hasTextFocus()`, попробуй.

**Comment by tormozit** [comment]
Заработало. 
А штатная функция у webKit с именем hasFocus() мне почему то возвращает Истина, если у формы нет фокуса, но поле HTML является текущим элементом. Хотелось бы в идеале найти способ узнать это от самого webKit. Если встретится, то дай знать.

**Comment by tormozit** [comment]
Небольшая беда есть. Если активировать другую форму и затем обратно активировать форму с полем редактора, то hasTextFocus() начинает возвращать Ложь. Хотя если нажать любую букву, то она будет напечатана в поле редактора, т.е. по факту фокус ввода у него есть.

**Comment by tormozit** [comment]
У меня на эту проверку завязано автосохранение текста в редакторе. Поэтому она должна работать очень надежно.
