### ISSUE TITLE
Редактор теряет фокус ввода после открытия модального окна 

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#122]
8.3.18 обычная форма
При открытом списке автодополнения после открытия модального окна 1С редактор теряет фокус ввода. Он остается текущим элементом формы, но каретка не мигает и нажатия клавиш не приводят к печати символов. Переключение на другое окно в приложении 1С и обратно или на окно другого приложения и обратно исправляют проблему

![изображение](https://user-images.githubusercontent.com/11896251/118434477-d0190a00-b6e5-11eb-96d5-cccbe596bd2a.png)

![изображение](https://user-images.githubusercontent.com/11896251/118434585-fb9bf480-b6e5-11eb-8f43-caa31abd4a26.png)

![изображение](https://user-images.githubusercontent.com/11896251/118434630-0bb3d400-b6e6-11eb-9ca1-c36508f6bf73.png)

**Comment by tormozit** [comment]
Снова пришлось лечить через РедакторHTML.editor.focus() . Наверное стоит создать этот метод у корневого объекта, т.к. его уже не первый раз приходится звать для лечения подобных проблем.

**Comment by salexdv** [comment]
> 8.3.18
> При открытом списке автодополнения после открытия модального окна 1С редактор теряет фокус ввода. Он остается текущим элементом формы, но каретка не мигает и нажатия клавиш не приводят к печати символов. Переключение на другое окно в приложении 1С и обратно или на окно другого приложения и обратно исправляют проблему

Я не думаю, что это проблема редактора. Он ничего не знает ни о каких модальных окнах. Похожая проблема возникает при использовании контекстного меню в 1С. Это больше похоже на проблему 1С.

**Comment by tormozit** [comment]
Интересно, что РедакторHTML.editor.focus() приводит к миганию каретки, но печать вводимых символов все равно не выполняется.

**Comment by tormozit** [comment]
> Похожая проблема возникает при использовании контекстного меню в 1С
Где почитать про эту проблему?

**Comment by tormozit** [comment]
Кстати в любой ситуации после выполнения кода 
`ЭтаФормаТекущийЭлемент = ПолеHTML;`
редактор не получает фокус ввода. В ряде случае установить фокус ввода помогает 
`РедакторHTML.editor.focus()`
Но гарантировано (во всех ситуациях) фокус ввода установить сейчас можно только кликом.

**Comment by tormozit** [comment]
Максимизация или восстановление размеров формы, в которой находится редактор, восстанавливают его фокус ввода.

**Comment by tormozit** [comment]
Пока нашел решение только через SendKeys - отправку нажатия ALT два раза подряд.

**Comment by salexdv** [comment]
> > Похожая проблема возникает при использовании контекстного меню в 1С
> 
> Где почитать про эту проблему?

Эта проблема нигде не описана. Она относится к связке 1С+редактор, но не к самому редактору.

**Comment by tormozit** [comment]
Проблема оказалась шире, чем я изначально думал. Например в таком состоянии (после закрытия модального окна) клавиатурный ввод частично может направляться даже в другое окно. Например в окно конфигуратора, если оно по Z-порядку находится следующим после окна клиентского приложения. Т.е. окон конфигуратора вообще не видно пользователю, а нажатия клавиш CTRL+V, CTRL+Z, CTRL+C приходят ему! Т.е. поработав с редактором, я с удивлением обнаруживаю, что код в конфигураторе испорчен.

**Comment by salexdv** [comment]
Как это воспроизвести? Открываю модальное окно при открытом списке подсказок, при закрытии окна фокус в редакторе, можно печатать
![oZKDdXk88b](https://user-images.githubusercontent.com/6356534/119098535-9a925a80-ba1e-11eb-828e-420b01d8e75f.gif)
При закрытии окна по Esc тоже нет проблем

**Comment by tormozit** [comment]
Воспроизведение потери фокуса. Открыть обрабокту в обычном приложении. Активировать вторую страницу (с редактором). Кликнуть в поле редактора. Нажать CTRL+R. Откроется модальная форма. Закрыть ее. Вводить текст. При этом происходит ничего.
[Консоль кода HTML.zip](https://github.com/salexdv/bsl_console/files/6521578/HTML.zip)

**Comment by salexdv** [comment]
В твоём примере так себя ведет не только поле HTML-документа, но и обычное поле ввода надо ним. Если активизировать поле ввода, а затем нажать CRTL+R, то фокус обратно тоже не вернутся.

**Comment by tormozit** [comment]
> Если активизировать поле ввода, а затем нажать CRTL+R, то фокус обратно тоже не вернутся

У меня такого не наблюдается. фокус ввода возвращается в поле ввода. 8.3.18

**Comment by salexdv** [comment]
> > Если активизировать поле ввода, а затем нажать CRTL+R, то фокус обратно тоже не вернутся
> 
> У меня такого не наблюдается. фокус ввода возвращается в поле ввода. 8.3.18

В любом случае, как я уже говорил ранее, редактор ничего не знает о модальных окнах. Это глюк 1С. Ни одного нормального способа вернуть фокус HTML-полю я не знаю.

**Comment by tormozit** [comment]
Ну хотя бы событие у тебя там какое то приходит при активации окна формы после закрытия модальной формы? Если да, то можно передать его мне, чтобы двойным нажатием ALT возвращал фокус.

**Comment by salexdv** [comment]
> Ну хотя бы событие у тебя там какое то приходит при активации окна формы после закрытия модальной формы? Если да, то можно передать его мне, чтобы я двойным нажатием ALT возвращал фокус.

Никакого события внутри редактора при закрытии модальной формы не происходит.
Ты и так можешь делать двойной ALT сразу после закрытия модального окна, для этого не нужно никакое событие.

**Comment by tormozit** [comment]
Речь про чужое модальное или разные мои окна - у меня много мест в коде где открываются окна во время редактирования. В каждом это прописывать - очень не хорошее решение.

**Comment by salexdv** [comment]
> Речь про чужое модальное или разные мои окна - у меня много мест в коде где открываются окна во время редактирования. В каждом это прописывать - очень не хорошее решение.

Другого решения нет.

**Comment by salexdv** [comment]
Пример с обычным полем HTML
[ПотеряФокуса.zip](https://github.com/salexdv/bsl_console/files/6622362/default.zip)
