### ISSUE TITLE
Зависание в режиме языка запросов после Тип("

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#123]
Редактирую запрос из вложенного файла
[Clip_243318.txt](https://github.com/salexdv/bsl_console/files/6495402/Clip_243318.txt)
```
ИТОГИ
	СУММА(РеализованноеКоличество),
	СУММА(РеализованнаяМасса),
	СУММА(КоличествоПоСпецификации),
	СУММА(ЧистоваяМассаПоСпецификации),
	СУММА(МассаПоСпецификации),
	СУММА(ДельтаРеализации),
	СУММА(ВыпущенноеКоличество),
	СУММА(ВыпущеннаяМасса),
	СУММА(ДельтаВыпуска)
	Тип("
```
Если стоя после кавычки вызвать контекстную подсказку через CTRL+SPACE, то редактор зависает (100% загрузка процессора). События при этом не вызываются. Видимо при парсинге контекста происходит зацикливание.
В чистом тексте после строки 
`Тип(" `
зависания не происходит

**Comment by salexdv** [comment]
Проверил и в толстом и в тонком клиенте, воспроизвести не удалось.

![tXWec1EHPe](https://user-images.githubusercontent.com/6356534/118533560-e27c5d80-b750-11eb-8b29-837343848091.gif)

События вызываются, подсказка работает, загрузки процессора нет.

**Comment by tormozit** [comment]
Отбой. Ошибка в моем коде.
