### ISSUE TITLE
На 8.3.16 сочетание CTRL+SPACE не вызывает появление автодополнения

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#124]
Рекомендую добавить информацию об этом в известные проблемы.
> На платформах до 8.3.16 могут не работать горячие клавиши CTRL+C, CTRL+V и CTRL+Z и т.п.

**Comment by salexdv** [comment]
Какой точно релиз и разрядность?

**Comment by tormozit** [comment]
1С:Предприятие 8.3 (8.3.16.1224) 32х

**Comment by salexdv** [comment]
Проверил, CTRL+SPACE работает

![ZtB9VC8Int](https://user-images.githubusercontent.com/6356534/119015112-47c68d80-b9a1-11eb-8f59-ea902e3e64e2.gif)

**Comment by tormozit** [comment]
> Проверил, CTRL+SPACE работает

Так это потому что я его там кнопкой 1С сделал и сам вызываю показ списка.

**Comment by salexdv** [comment]
> > Проверил, CTRL+SPACE работает
> 
> Так это потому что я его там кнопкой 1С сделал и сам вызываю показ списка.

Проверил и в тонком и в толстом клиентах, используя собственную разработку, всё работает.

**Comment by salexdv** [comment]
Любые горячие клавиши в платформах до последних 8.3.16 это беда. Постараюсь в описании написать чуть более подробно, чем сейчас
