### ISSUE TITLE
В редакторе кнопка F3 обрабатывается платформой и это неудобно

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#125]
8.3.18
1. Выделяю слово
2. Нажимаю Ctrl+F3, происходит его поиск
3. Нажимаю F3 - ожидаю поиск следующего вхождения того же слова, но тут платформа 1С  выполняет поиск другого слова
Хочется чтобы F3 в редакторе работала с той же строкой, с которой работает CTRL+F3 и CTRL+F.

![изображение](https://user-images.githubusercontent.com/11896251/118852753-bc36f900-b8db-11eb-8512-4b224549b2ac.png)

Предлагаю по нажатию CTRL+F3 запоминать искомую строку по аналогии с тем, как это делает платформа.  Затем при нажатии F3 искать эту строку. Также отображать эту строку в панели поиска редактора, открываемой по CTRL+F. Сейчас эта строка даже при поиске по CTRL+F3 там не отображается, хотя написано "3 из 3", что несколько странно выглядит.

![изображение](https://user-images.githubusercontent.com/11896251/118853408-644cc200-b8dc-11eb-878b-15e3e9069a34.png)

**Comment by salexdv** [comment]
По умолчанию в браузере так и работает, но 1С напрочь игнорирует F3, поэтому решением может быть сделать скрытую командную панель и кнопку на ней с назначенным сочетанием F3. При нажатии кнопки можно вызывать на выбор
```js
РедакторHTML.nextMatch();
РедакторHTML.previousMatch();
```

**Comment by tormozit** [comment]
Заработало. 

> F3 тогда в принципе на форме будет всегда выполнять данное действие, но возможно этого будет достаточно.

Я засунул эти команды в контекстное меню. Оно подключает сочетания клавиш только кода активен элемент формы. Таким образом потерь функциональности не возникает.
