### ISSUE TITLE
Прошу убрать сдвиг текста вниз при открытии панели поиска на первой строке текста

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#126]
Если нажать CTRL+F3 или CTRL+F, находясь в первой строке текста, то открывается панель поиска. При этом зачем то весь текст сдвигается вниз. А при ее скрытии текст снова сдвигается вверх. 

![изображение](https://user-images.githubusercontent.com/11896251/118881665-ff08c900-b8fb-11eb-869c-dca8b3edc2e4.png)

Если встать на непервую строку текста и открыть панель поиска, то текст вниз не сдвигается, то при этом можно прокрутить полосой прокрутки вверх так, что первая строка текста станет не первой в видимой области как и в первом случае.

![изображение](https://user-images.githubusercontent.com/11896251/118882018-5e66d900-b8fc-11eb-8ffb-7f162f46dd47.png)

![изображение](https://user-images.githubusercontent.com/11896251/118881641-fa441500-b8fb-11eb-8ff1-d63c510d841f.png)

И вместе с этой проблемой иногда еще наблюдается и родственная - панель поиска становится высотой 5 пискелей, т.е. не видно ее содержимого. Пока стабильно не воспроизвел ее. Но надеюсь с устранением описанной выше проблемы исправится и эта.

**Comment by salexdv** [comment]
Убрал

**Comment by salexdv** [comment]
> И вместе с этой проблемой иногда еще наблюдается и родственная - панель поиска становится высотой 5 пискелей, т.е. не видно ее содержимого. Пока стабильно не воспроизвел ее. Но надеюсь с устранением описанной выше проблемы исправится и эта.

Сейчас такого поведения не должно наблюдаться

**Comment by tormozit** [comment]
Заработало.
