### ISSUE TITLE
При открытии панели поиска сочетанием CTRL+F3 выделенное слово не вставляется в панель поиска

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#127]
Есть текст встроенного языка
`Многострочный = Ложь;`
Стоя на первом слове нажимаю CTRL+F3. При этом открывается панель поиска с пустой искомой строкой. Ожидалось что в искомой строке будет написано "Многострочный" 
![изображение](https://user-images.githubusercontent.com/11896251/118966848-b04a4600-b972-11eb-831f-a3e149d06c38.png)

**Comment by salexdv** [comment]
Доработал

**Comment by tormozit** [comment]
Заработало
