### ISSUE TITLE
Наложение текста после увеличения прокруткой колесом мыши с зажатым CTRL

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#128]
```
	РедакторHTML = ПолеHTML.Документ.defaultView;
	РедакторHTML.enableBeforeHoverEvent(Истина);
	РедакторHTML.renderWhitespace(Истина);
	РедакторHTML.setFontSize(13);
	РедакторHTML.setFontFamily("Lucida Console");
	РедакторHTML.showStatusBar(Ложь);
```
![изображение](https://user-images.githubusercontent.com/11896251/119034093-acd8ae00-b9b6-11eb-850d-e5101bc4d45d.png)

Вероятно нужно где то прописать пропорциональное увеличение отступов между строками. И на статусную строку обрати внимание.

**Comment by salexdv** [comment]
Ну это проблема скорее 1С, чем редактора. Проще попробовать просто отключить обработку колесика с зажатым CTRL

**Comment by tormozit** [comment]
Да, если исправлять сложно, то надо хотя бы заблокировать это изменение масштаба. Им пользуются редко. Я вообще не пользуюсь. Но случайно крутануть можно.

**Comment by tormozit** [comment]
Штатный редактор при "CTRL+прокрутка колеса" делает ускоренную прокрутку. Хотелось бы чтобы в твоем редакторе работало также.

**Comment by salexdv** [comment]
Мне не удалось переопределить такое поведение. Из поля HTML-документа 1С не дает доступ к событиям колеса мыши. На данный момент решения нет.

**Comment by tormozit** [comment]
А можно хотя бы сделать команду для установки 100% масштаба? Вот если случайно пользователь крутанул колесо, то чтобы мог вернуться к оригинальному масштабу?

**Comment by salexdv** [comment]
> А можно хотя бы сделать команду для установки 100% масштаба? Вот если случайно пользователь крутанул колесо, то чтобы мог вернуться к оригинальному масштабу?

Я не встречал способа из JS вернуть документу масштаб 100%
