### ISSUE TITLE
Нажатие Esc при фокусе в поле редактора  и открытой панели поиска закрывает форму 1С

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#129]
1. Открыть редактор в форме 1С
2. Установить каретку на любое слово в поле редактора и нажать CTRL+F3
3. Нажать 2 раза Esc для закрытия панели поиска
4. Нажать CTRL+F3 на любом слове в поле редактора
5. Нажать Esc 

Форма 1С закроется, а ожидалось что она останется открытой и нажатие будет обработано редактором (будет закрыта панель поиска).
Во вчерашней сборке в п.4 при этом отображалась урезанная по высоте панели поиска. А сейчас уже нормальная. Но во вчерашней сборке закрытия формы 1С не происходит.

**Comment by tormozit** [comment]
С такой багой не хотелось бы выпускать завтрашний релиз. Сможешь исправить ее завтра?

**Comment by salexdv** [comment]
> С такой багой не хотелось бы выпускать завтрашний релиз. Сможешь исправить ее завтра?
> Мне в 1С будет очень сложно это пролечить.

Пока у меня нет понимания, что нужно исправить. Да такое поведение воспроизводится, но редактор фокус не теряет. Если после 4 шага начать печатать, то изменяется текст в окне поиска.

**Comment by salexdv** [comment]
Попробуй сейчас, пожалуйста.

**Comment by tormozit** [comment]
Форма 1С закрываться перестала, но переход к следующему вхождению слова тоже перестал выполняться по нажатию CTRL+F3

**Comment by tormozit** [comment]
Заработало
