### ISSUE TITLE
Контекстная подсказка результата запроса

### ISSUE THREAD

**Issue by d-hurricane** [salexdv/bsl_console#13]
Неверно интерпретируется результат метода "Выполнить" запроса. Предполагаю, что вместо метода запроса подразумевается одноименный метод глобального контекста, из-за чего не работает контекстная подсказка ни для результата запроса, ни для выборки данных из запроса:
```bsl
Запрос = Новый Запрос();
Запрос.Текст = "ВЫБРАТЬ 1";

Результат = Запрос.Выполнить();
Выборка = Результат.Выбрать();
```

**Comment by salexdv** [comment]
> Неверно интерпретируется результат метода "Выполнить" запроса.

Подсказка в таком случае и не задумывалась. Сейчас такое работает только для конструкций вида
```bsl
Док = Документы.ПриходнаяНакладная.СоздатьДокумент();
Док. // тут подсказка
```
У меня пока нет в планах реализовывать полноценный конфигуратор, поэтому подсказки для объектов (переменных), полученных какими-либо методами не предусмотрены. Это достаточно сложно воплотить в жизнь.

**Comment by d-hurricane** [comment]
Да, понял. Сработала контекстная подсказка для переменной "Запрос", поэтому я решил, что и для остальных должно сработать.
