### ISSUE TITLE
Блокировать обработку ALT+UP/DOWN

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#130]
Я использую собственное окно подсказки по вызову метода в обычном приложении 

![изображение](https://user-images.githubusercontent.com/11896251/119049776-a273df80-b9c9-11eb-85d2-a4dd2f0e14d2.png)

Варианты сигнатуры в нем переключаются сочетаниями ALT+UP/DOWN для единообразия с твоей подсказкой по вызову метода, которую я использую в управляемом приложении. Проблема в том, что когда открыта твоя подсказка, ты сам можешь решать как трактовать неоднозначное сочетание  (либо сдвинуть выделенные строки, либо переключить сигнатуру). Мне тоже нужно такое управление.

И даже с твоим окном подсказки по вызову метода не все гладко в такой ситуации. Если выбрана крайняя сигнатура и еще раз нажать ALT+UP/DOWN в сторону края списка вариантов, то начинает срабатывать сдвиг текста, не закрывая при этом окно подсказки. Что необычно и не каждый сразу поймет.

![изображение](https://user-images.githubusercontent.com/11896251/119050383-7311a280-b9ca-11eb-91a6-a4fb9a9c5b33.png)

**Comment by tormozit** [comment]
Предлагаю все таки сделать единообразно с конфигуратором.
1. Переключение сигнатур повесить на CTRL+Up/Down
2. Пока видимо окно сигнатуры, не смещать видимую область в тексте при нажатии клавиш переключения сигнатур
3. Добавить в API функцию для переключения подавления обработки этих сочетаний клавиш, чтобы я мог реализовать аналогичное поведение.

**Comment by tormozit** [comment]
Пока открыто окно подсказки по вызову метода (твое или мое), сочетания клавиш для переключения сигнатур не должны направляться в сам редактор, т.е. делать в нем свою обычную функцию (сдвиг выделенного текста или сдвиг видимой области внутри текста). Чтобы редактор понимал, когда это нужно запрещать, я должен ему это сообщить. Для этого нужен метод - на включение и выключение подавления/блокировки обработки этих команд.

**Comment by salexdv** [comment]
Я никак не могу предотвратить нажатие CTRL+Up/Down. Отследить да, предотвратить - нет.

**Comment by tormozit** [comment]
Тогда давай делать переключение сигнатур на ALT+UP/DOWN. Их то ты сможешь подавлять, ведь ты же сам их обрабатываешь?

**Comment by salexdv** [comment]
> Тогда давай делать переключение сигнатур на ALT+UP/DOWN. Их то ты сможешь подавлять, ведь ты же сам их обрабатываешь?

Нет, я не могу влиять на эти сочетания. Всё что можно - это заменить ALT+Up/Down на CTRL+Up/Down, что я уже сделал.

**Comment by tormozit** [comment]
Задокументировал проблему https://www.hostedredmine.com/issues/928504 . Сигнатуры переключать конечно приходится не часто. Но удар по удобству в этом сценарии заметный.

**Comment by salexdv** [comment]
> Задокументировал проблему https://www.hostedredmine.com/issues/928504 . Сигнатуры переключать конечно приходится не часто. Но удар по удобству в этом сценарии заметный.

Я не понимаю в чем неудобство. Да ALT+Up/Down сдвигают строку, но ведь для прокрутки вариантов сигнатур и в конфигураторе и у меня используется CTRL+Up/Down. Зачем вдруг пользователю нажимать ALT, если он привык к CTRL?

**Comment by tormozit** [comment]
У меня есть свое окно подсказки по вызову метода
![изображение](https://user-images.githubusercontent.com/11896251/119188363-3bb2fc80-ba83-11eb-8ee7-5b925d3cf67a.png)

В нем есть кнопки переключения вариантов синтаксиса (сигнатур) метода. В поле текстового документа 1С сочетания клавиш CTRL+Up/Down двигают видимую область текста вверх. Поэтом когда я, подключившись через внешнюю компоненту к клавиатурному вводу, получаю внешнее событие о нажатии сочетания CTRL+Up, то я могу выполнить переключение на следующую сигнатуру.  Но платформенная обработка реакции поля текстового документа на это сочетание тоже отрабатывает - видимая область текста сдвигается вверх. Поэтому я вместо CTRL+Up/Down слушаю ALT+Up/Down. С ними в поле текстового документа побочных действий программы не возникает. 

Но если я из твоего редактора открываю то же свое окно подсказки (без захвата фокуса естественно) по вызову метода, то любое из сочетаний CTRL+Up/Down или ALT+Up/Down выполняют какое то действие, которое я не могу предотвратить. Поэтому получив внешнее событие о нажатии такого сочетания, я хоть и могу выполнить свою обработку (переключить сигнатуру в моем окне), но еще выполняется и твоя - сдвигаются выделенные строки или видимая область текста. 

В итоге получается нажатие этих сочетаний выполняет оба действия - и мое и штатное для твоего редактора. 
Конечно я могу назначить другие сочетание клавиш, но оно не будет таким удобным и привычным как эти. А я когда делаю альтернативу чему то, стараюсь чтобы она по возможности во всем была не менее удобна.

**Comment by salexdv** [comment]
Увидел сегодня [способ](https://github.com/Microsoft/monaco-editor/issues/940), как можно попытаться заблокировать такие сочетания. Попробую реализовать.

**Comment by salexdv** [comment]
Добавил две функции:
1. `disableKeyBinding` - отключает любое стандартное сочетание клавиш редактора
2. `enableKeyBinding` - включает обратно сочетание

Функции на вход принимают один числовой параметр, который является результатом ПОБИТОВОГО ИЛИ для сочетания кодов клавиш.

[Тут](https://microsoft.github.io/monaco-editor/api/enums/monaco.keycode.htm) есть коды всех клавиш, правда для CTRL/ALT/SHIFT они некорректные и указаны ниже.

key | KeyCode | 
-- | --
Ctrl |  2048
Alt |  512
Shift | 1024

Например, для `ALT(512)+ArrowUp(16)` побитовое ИЛИ будет равно **528**.
Для `ALT(512)+ArrowDown(18)` ПОБИТОВОГО ИЛИ будет равно **530**.
Можно [тут](https://www.mymathtables.com/calculator/digital/bit-manipulation-operator-calculator.html) быстро проверить.

Для отключения данных сочетаний вызываем функции:
```js
disableKeyBinding(528);
disableKeyBinding(530);
```
После вызова при нажатии `ALT+ArrowUp` будет генерироваться событие `EVENT_KEY_BINDING_528`, а для `ALT+ArrowDown` -  `EVENT_KEY_BINDING_530`

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
> [Тут](https://microsoft.github.io/monaco-editor/api/enums/monaco.keycode.htm) есть коды всех клавиш

Ссылка битая

**Comment by salexdv** [comment]
> Ссылка битая

Исправил
