### ISSUE TITLE
Неудобство в подсказке по запросу 

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#131]
![Ошибка подсказки, можно чтобы подсказывал поля](https://user-images.githubusercontent.com/48444742/119115118-7c812600-ba2f-11eb-9738-a73d41733108.png)
Можно чтобы давал выбирать поля, но после точки ошибочное поведение
Не критично

**Comment by Evg-lylyk** [comment]
Проверил в сегодняшней версии, поведение не изменилось

**Comment by salexdv** [comment]
> Проверил в сегодняшней версии, поведение не изменилось

Проверил еще раз. После точки при таком составе запроса ничего не показывает

**Comment by Evg-lylyk** [comment]
Прошу прошения, все работает
