### ISSUE TITLE
Неудобство не подсказывает источник данных в ИЗ после ","

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#132]
![Screenshot_1](https://user-images.githubusercontent.com/48444742/119115404-d08c0a80-ba2f-11eb-983e-ca3feba78e17.png)
Не критично

**Comment by salexdv** [comment]
Теперь подсказка должна показываться

**Comment by Evg-lylyk** [comment]
Проверяю, все также

**Comment by salexdv** [comment]
> Проверяю, все также

Может криво обновились исходники? 
![yfxVAJKsi9](https://user-images.githubusercontent.com/6356534/119492330-9d1aea00-bd67-11eb-9a48-dc728cfafdbf.gif)

**Comment by Evg-lylyk** [comment]
Прошу прошения, все работает
