### ISSUE TITLE
Переход к парной скобке CTRL+"[" и CTRL+"]"

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#133]
Во встроенном редакторе платформы переход к парной скобке выполняется сочетаниями CTRL+"[" и CTRL+"]". Можно ли в твоем редакторе сделать также? Если нет, то какими сочетаниями это выполняется?

**Comment by salexdv** [comment]
> Во встроенном редакторе платформы переход к парной скобке выполняется сочетаниями CTRL+"[" и CTRL+"]". Можно ли в твоем редакторе сделать также? Если нет, то какими сочетаниями это выполняется?

Переход к парной скобке работает по сочетанию `CTRL+SHIFT+\`
Есть еще команда выделения всего текста между скобками, но она не имеет привязки к горячим клавишам.

**Comment by salexdv** [comment]
Можно переопредить и сделать по аналогии с конфигуратором

**Comment by tormozit** [comment]
Считаю, что лучше назначить CTRL+"[" и CTRL+"]" по умолчанию. Так будет удобнее большинству 1Сников, т.к. сочетания из конфигуратора им знакомы с большей вероятностью, чем сочетания VSCode.

**Comment by tormozit** [comment]
Заработало. Однако не для всех ожидаемых случаев. Например не работает для программных скобок типа "Для/Пока"-"КонецЦикла", "Если"-"КонецЕсли", "Попытка"- "КонецПопытки". Во встроенном редакторе работает.

**Comment by salexdv** [comment]
> Заработало. Однако не для всех ожидаемых случаев. Например не работает для программных скобок (обрамляющих конструкций) типа "Для/Пока"-"КонецЦикла", "Если"-"КонецЕсли", "Попытка"- "КонецПопытки". Во встроенном редакторе работает.

Подумаю, как это решить

**Comment by tormozit** [comment]
Заработало
