### ISSUE TITLE
Полный список сочетаний клавиш с описанием на русском

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#134]
Было бы здорово задокументировать все сочетания клавиш на русском языке. И начать предлагаю с тех. которые отличаются от встроенного редактора

**Comment by salexdv** [comment]
По мере появления свободного времени постараюсь описывать их здесь, для начала

**Comment by salexdv** [comment]
[Задокументировал](https://github.com/salexdv/bsl_console/blob/develop/docs/shortcuts.md) сочетания

**Comment by tormozit** [comment]
Про F3 не совсем понял. Вроде же оно приходит к тебе и его ловит 1С.
Наверное стоит сделать пометки про работу в окне 1С.

**Comment by salexdv** [comment]
> Про F3 не совсем понял. Вроде же оно НЕ приходит в редактор внутри окна 1С и его ловит главное окно 1С.
> Наверное стоит сделать пометки про работу в окне 1С.

Редактор может работать на сайте, например. 1С для его работы необязательна.
