### ISSUE TITLE
Событие EVENT_BEFORE_SIGNATURE в режиме языка запросов не вызывается

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#135]
Уже все перепроверил. Событие не вызывается в режиме языка запросов. Например нажимаю символ "(" и открывается стандартная подсказка по вызову метода, но события EVENT_BEFORE_SIGNATURE (сначала ошибочно указал EVENT_BEFORE_SHOW_SUGGEST) не вызывается.

Воспроизвести можно в моей демобазе. Надо поставить точку останова на первой строке метода РедакторHTMLonclick() в модуле Обработка.ирКонсольЗапросов.Форма и отрыть форму консоли так
![изображение](https://user-images.githubusercontent.com/11896251/119217541-8cf2d880-bae3-11eb-9049-64a345186e20.png)

**Comment by salexdv** [comment]
Только что проверил на последней версии из dev-ветки
![zER3tKcmKB](https://user-images.githubusercontent.com/6356534/119237587-47b3c280-bb46-11eb-80e0-9bb5d06ddfdd.gif)

**Comment by tormozit** [comment]
Виноват. Перепутал имя события. Имел ввиду EVENT_BEFORE_SIGNATURE - подсказка по вызову метода, которая параметры показывает.
![изображение](https://user-images.githubusercontent.com/11896251/119238677-88163f00-bb4c-11eb-9930-98f205732a4b.png)
