### ISSUE TITLE
clearMetadata не очищает запросы по EVENT_GET_METADATA

### ISSUE THREAD

**Issue by GenVP** [salexdv/bsl_console#136]
При частичном обновлении метаданных через  EVENT_GET_METADATA эти запросы сохраняются как выполненные.
При вызове clearMetadata очищаются только существующие метаданные, но не выполненные запросы.

В стандартной консоли, наверное, это не воспроизведется, так как там нет смены конфигурации.

**Comment by GenVP** [comment]
В типовой консоли можно воспроизвести с доработками:
1. Отключить обновление всех метаданных в ОбновитьМетаданные добавив "Возврат;" в начале.
2. Добавить команду на форму, вызывающую ОбнулитьМетаданные()
3. Вызвать подсказку, по коллекции - будут получены объекты.
4. Обнулить метаданные по кнопке.
5. Вызвать подсказку, по коллекции - будет "Предложения отсутствую", так как коллекция запрошена ранее, а метаданных нет.

**Comment by salexdv** [comment]
> При частичном обновлении метаданных через EVENT_GET_METADATA эти запросы сохраняются как выполненные.
> При вызове clearMetadata очищаются только существующие метаданные, но не выполненные запросы.
> 
> В стандартной консоли, наверное, это не воспроизведется, так как там нет смены конфигурации.

Спасибо! Исправлю
