### ISSUE TITLE
Хочу окраски измененных фрагментов с маркировкой их позиции на полосе прокрутки

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#139]
Хочу окраски (например вертикальными линиями слева как в VSCode) измененных фрагментов текста с маркировкой их позиции на полосе прокрутки. Исходный текст хотелось бы передавать в вызове updateText(), т.к. в консоли кода/запросов пользователь может много раз переключаться между разными текстами и редактировать их попеременно многократно.
Понимаю, что задача непростая. Поэтому описал на перспективу.

**Comment by salexdv** [comment]
Пока не очень ясна механика использования. Можешь пояснить подробнее, как ты будешь это использовать?
Для теста добавил функцию `showDiff`, которая на вход принимает оригинальный текст т.е. считается, что текст в редакторе уже изменен. При вызове `showDiff` происходит сравнение и раскрашивание.

**Comment by salexdv** [comment]
Вот так выглядит результат работы:

![editor](https://user-images.githubusercontent.com/6356534/119352209-1227ea00-bcaa-11eb-960e-a87213850acc.png)

На полосе прокрутке тоже видны изменения.

**Comment by salexdv** [comment]
Так как функция тестовая она не учитывает наличие закладок и индикацию ошибок т.е. при её вызове отображение закладок пропадет.

**Comment by salexdv** [comment]
В теории можно попробовать в режиме реального времени вызывать `showDiff`, когда приходит событие `EVENT_CONTENT_CHANGED`

**Comment by tormozit** [comment]
Работает с приемлемой скоростью - 10-15мс для небольших текстов, которых большинство. 
Есть проблема с маркировкой измененных строк - появляется нежданная пометки изменности предыдущей строки после ввода второго символа в текущей строке

![изображение](https://user-images.githubusercontent.com/11896251/119382104-44494400-bcca-11eb-9fa3-53f4d41ea79b.png)

![изображение](https://user-images.githubusercontent.com/11896251/119382113-46ab9e00-bcca-11eb-89ca-ab15e1abfb00.png)

![изображение](https://user-images.githubusercontent.com/11896251/119382132-4b705200-bcca-11eb-998a-7afbdff0c217.png)

**Comment by tormozit** [comment]
Еще есть проблема с нежданным обнаружением добавленной строки в конце текста сразу после его загрузки. При этом на полосе прокрутки используется некорректный цвет маркировки.

![изображение](https://user-images.githubusercontent.com/11896251/119382592-e832ef80-bcca-11eb-8523-b47e18022edb.png)

**Comment by tormozit** [comment]
Еще проблема с удалением последней строки. При этом все строки текста помечаются как "добавленные".

![изображение](https://user-images.githubusercontent.com/11896251/119384333-3517c580-bccd-11eb-9e44-297e878a3b43.png)

![изображение](https://user-images.githubusercontent.com/11896251/119384334-36e18900-bccd-11eb-99db-23e056154f3f.png)

**Comment by tormozit** [comment]
Еще было бы здорово как то помечать места, где строки были удалены. Может короткой горизонтальной линией?

**Comment by salexdv** [comment]
Это только первая примерка, чтобы просто посмотреть, будет ли это нормально работать. Всю реализацию я буду переделывать, чтобы можно было просто один раз задать оригинальный текст одной функцией, а дальше при изменении текста редактор сам будет всё пересчитывать.

**Comment by salexdv** [comment]
Добавил функцию `setOriginalText`, которой можно задать эталонный текст, ну или очистить его, передав пустое значение.
Если эталонный текст установлен, то раскраска изменений будет происходить автоматически при изменении содержимого.
Реализация раскраски максимально близкая к VSCode. Она, конечно, не идеальная, но лучшего способа пока не придумал.

**Comment by tormozit** [comment]
Работает. Но моргание при вводе символов этих вертикальных линий слева сильно отвлекает внимание.

**Comment by salexdv** [comment]
> Работает. Но при вводе символов моргание этих вертикальных линий слева сильно отвлекает внимание.

Доработал, теперь моргания не будет.

**Comment by salexdv** [comment]
Добавил виджет для быстрого просмотра изменений
![sTdsAOa0qe](https://user-images.githubusercontent.com/6356534/119486729-3eeb0880-bd61-11eb-8642-cb6ad38374d0.gif)

**Comment by tormozit** [comment]
Заработало. Мощная функция.

**Comment by tormozit** [comment]
Надо бы на русский перевести слово "changes"
![изображение](https://user-images.githubusercontent.com/11896251/119653815-71b00200-be30-11eb-98f1-3f93175d34af.png)

**Comment by tormozit** [comment]
Вместо надписи "changes" теперь вижу "кракозябры"
![изображение](https://user-images.githubusercontent.com/11896251/119888054-96de6680-bf3d-11eb-9d9f-aae8708d1f1b.png)

Имея уже 2 места проявления этой беды, может появятся новые версии о ее причине.

**Comment by salexdv** [comment]
> Вместо надписи "changes" теперь вижу "кракозябры"

![editor](https://user-images.githubusercontent.com/6356534/119936086-4133a980-bf91-11eb-92a2-577cb56bda21.png)

**Comment by tormozit** [comment]
Заработало. 
При записи текста по умолчанию используется UTF8. А вот при чтении действительно используется "автоматическое определение кодировки" и только если оно "удалось", то используется UTF8. Видимо для твоих файлов оно "удалось" и получилось не UTF8.

**Comment by tormozit** [comment]
Еще будет полезно добавить в окне изменений блока кнопку "Откатить изменения".
