### ISSUE TITLE
Номер тест версии платформы

### ISSUE THREAD

**Issue by GenVP** [salexdv/bsl_console#14]
Просьба добавить в начало readme номер версии платформы на котором тестируется обработка.
Чтобы было понятно на какой версии функционал точно должен работать.
Например, на 8.3.15 не работают CTRL+C, CTRL+V, но на 8.3.16 он работают и это теперь понятно.

**Comment by salexdv** [comment]
Версию платформы может и не добавлю, а вот известные проблемы на разных платформах добавить стоит. Спасибо, что обратили внимание на это. [Тут](https://infostart.ru/public/1266087/) я это указал, а в readme пропустил
