### ISSUE TITLE
Подсказка по вызову метода не закрывается при перемещении в конец строки клавишей End

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#140]
Стою внутри скобок

![изображение](https://user-images.githubusercontent.com/11896251/119379186-d439be80-bcc7-11eb-881b-ebcae7725482.png)

Нажимаю клавишу END

![изображение](https://user-images.githubusercontent.com/11896251/119379138-c5530c00-bcc7-11eb-8f2f-ce2cff1f17ac.png)

Каретка уже вне вызова метода (справа от последнего символа строки), но подсказка все еще отображается. А ожидалось, что она скроется.

**Comment by salexdv** [comment]
Не наблюдаю такого поведения.
![rmj9YaCZdq](https://user-images.githubusercontent.com/6356534/119494295-d18fa580-bd69-11eb-92cf-a312380e0905.gif)
Как можно воспроизвести?

**Comment by tormozit** [comment]
Поставить ";" после скобки. У тебя ее нет.

**Comment by tormozit** [comment]
Заработало
