### ISSUE TITLE
Нажатие CTRL+Z сразу после установки текста через updateText() удаляет весь текст

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#141]
Нажатие CTRL+Z сразу после установки текста через updateText() удаляет весь текст.
А ожидалось, что текст не будет удален.

**Comment by salexdv** [comment]
Исправил. Сейчас CTRL+Z должен отрабатывать нормально.

**Comment by tormozit** [comment]
Обновился. Проблема осталась.

**Comment by salexdv** [comment]
Как можно воспроизвести? Только что проверял, результат ниже:

![3iyjuACdmK](https://user-images.githubusercontent.com/6356534/119615528-2d107080-be08-11eb-9c5d-65c57fb6beee.gif)

**Comment by tormozit** [comment]
Жми в консоли "УстановитьТЕкст" и потом CTRL+Z

![изображение](https://user-images.githubusercontent.com/11896251/119653459-06663000-be30-11eb-80a9-5e7c81ec8ec9.png)

[Консоль кода HTML.zip](https://github.com/salexdv/bsl_console/files/6546371/HTML.zip)

**Comment by salexdv** [comment]
> Жми в консоли "УстановитьТЕкст" и потом CTRL+Z

Тут проблема скорее в том, что 1С не устанавливает фокус в поле HTML-документа. Если нажать на редактор т.е. установить курсор в него и заменить текст, то всё прекрасно работает. Если фокуса нет, то редактор почему-то не сохраняет состояние в стек, даже принудительно. Пока я не знаю, как это обойти.

**Comment by tormozit** [comment]
Не заработало

**Comment by salexdv** [comment]
> Не заработало. Проблема важная, т.к. есть частный сценарий в редакторах - пользователь быстро хочет откатиться к исходному состоянию текста, для чего он удерживает CTRL+Z до тех пор, пока текст не перестает изменяться. В твоем редакторе он будет получать пустой текст.

Выше я описал в чем проблема. Решить из редактора её невозможно. Если будет происходить нормальная установка фокуса в поле HTML-документа с редактором, то и CTRL+Z будет работать нормально.

**Comment by tormozit** [comment]
Я так понял, что вызов updateText() мне надо всегда выполнять при наличии фокуса ввода и тогда будет происходить сброс истории отмены изменений. Правильно?

**Comment by salexdv** [comment]
> Я так понял, что вызов updateText() мне надо всегда выполнять с предварительной установкой фокуса ввода на поле редактора и тогда будет происходить сброс истории отмены изменений. Правильно?

Да

**Comment by tormozit** [comment]
> 
> 
> > Я так понял, что вызов updateText() мне надо всегда выполнять с предварительной установкой фокуса ввода на поле редактора и тогда будет происходить сброс истории отмены изменений. Правильно?
> 
> Да
Тщательно проверил. У меня не работает этот способ обхода.

**Comment by tormozit** [comment]
Прошу предоставить пример внешней обработки, где работает сброс истории отмены.

**Comment by salexdv** [comment]
Попробуй сейчас

**Comment by tormozit** [comment]
Заработало во всех случаях, кроме самой первого вызова updateText(), которое у меня выполняется в обработчике ДокументСформирован(). Установка фокуса ввода не помогает.

**Comment by salexdv** [comment]
![yHENR4tH3Y](https://user-images.githubusercontent.com/6356534/120363228-8ef33d80-c314-11eb-9bc8-0c080d9e2e4e.gif)

[Консоль кода HTML_undo.zip](https://github.com/salexdv/bsl_console/files/6577919/HTML_undo.zip)

**Comment by tormozit** [comment]
8.3.18
Скачал твой пример. У меня он правда немного по-другому выглядит.
![изображение](https://user-images.githubusercontent.com/11896251/120372617-14c8b600-c320-11eb-86de-f5b86c72b1b7.png)
Сразу после открытия формы я кликнул в поле HTML. Появилась каретка. Я нажат CTRL+Z. Весь текст удалился

**Comment by salexdv** [comment]
> Я нажат CTRL+Z. Весь текст удалился

Так а чего ты ждал? При инициализации редактора текст в нём был пустой. Потом был вызван `UpdateText` и что-то установлено. Да, при нажатии `CTRL+Z` текст опять станет пустой т.к. это возврат на один шаг назад. Если нужно, чтобы такого не происходило, то можно воспользоваться родным методом редактора, а именно `setValue`

**Comment by tormozit** [comment]
Через editor.setValue заработало.
В самом первом сообщении я описал ожидания

> Нажатие CTRL+Z сразу после установки текста через updateText() удаляет весь текст.
> А ожидалось, что текст не будет удален.

Тут я кстати давно уже спрашивал как правильно устанавливать текст https://github.com/salexdv/bsl_console/issues/58 . Кажется будет правильно все таки добавить как я просил - аналог метода УстановитьТекст в API, либо в методе updateText добавить параметр для сброса истории редактирования (вызова внутри setValue).
