### ISSUE TITLE
Прошу показывать детальную информацию в строке списка автоподополнения при наведении курсора мыши

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#142]
И было бы логичным перед отображением вызывать событие EVENT_ON_ACTIVATE_SUGGEST_ROW чтобы я там мог при необходимости вычислить информацию о типе.

![изображение](https://user-images.githubusercontent.com/11896251/119526892-78833a00-bd88-11eb-8765-27770987e381.png)

**Comment by salexdv** [comment]
Добавил генерацию события, но есть нюансы:
1. В качестве триггера у параметров события будет указан `hover`
2. В параметры события `EVENT_ON_ACTIVATE_SUGGEST_ROW` добавлено поле `row_id`, по которому потом можно обновить описание.
```json
{
  "trigger": "*hover*", НОВОЕ_ЗНАЧЕНИЕ
  "current_word": "",
  "last_word": "авансовыйотчет",
  "last_expression": "документы.авансовыйотчет.",
  "focused": "Выбрать",
  "row_id": "5", ДОБАВЛЕНО
  "rows": [
    "Выбрать",
    "НайтиПоНомеру",
    "НайтиПоРеквизиту",
    "ПолучитьДанныеВыбора",
    "ПолучитьМакет",
    "ПолучитьСсылку",
    "ПолучитьФорму",
    "ПолучитьФормуВыбора",
    "ПолучитьФормуНовогоДокумента",
    "ПолучитьФормуСписка",
    "ПустаяСсылка",
    "СоздатьДокумент"
  ]
}
```
3. Добавил функцию `setSuggestItemDetailById`, с помощью которой можно обновить описание у элемента с конкретным `row_id`. Вызывается так:
```js
setSuggestItemDetailById(5, "Это новое описание для пункта подсказки");
```
Всё это должно замечательно работать, но проблема в том, что даже если ты обновишь описание, то нажать значок, позволяющий открыть детальную информацию, ты нажать не сможешь т.к. он отображается только у того пункта, на котором находится фокус. 
Еще желательно проверить работоспособность всех случаев, когда к тебе приходят события `EVENT_ON_ACTIVATE_SUGGEST_ROW` и `EVENT_ON_SELECT_SUGGEST_ROW` т.к. переписал я там довольно много.

**Comment by salexdv** [comment]
> Всё это должно замечательно работать, но проблема в том, что даже если ты обновишь описание, то нажать значок, позволяющий открыть детальную информацию, ты нажать не сможешь т.к. он отображается только у того пункта, на котором находится фокус.

Больше не актуально

**Comment by salexdv** [comment]
Достаточно ли текущего функционала для решения указанной задачи?

**Comment by tormozit** [comment]
Устанавливаю детальное описание через setSuggestItemDetailById() при каждом вызове события EVENT_ON_ACTIVATE_SUGGEST_ROW . Детальное описание в списке отображается верно. Но вот в окне детальной информации оно не обновляется.

![изображение](https://user-images.githubusercontent.com/11896251/121397237-d30dc000-c95c-11eb-8cef-59faa8a256a0.png)
