### ISSUE TITLE
Не работает подсказка для существующего кода при частичном чтении метаданных

### ISSUE THREAD

**Issue by GenVP** [salexdv/bsl_console#143]
Порядок воспроизведения:
1. Отключить обновление всех метаданных в ОбновитьМетаданные добавив "Возврат;" вначале.
2. Вставить в консоль кода код. Например:
```bsl
Спр = Справочники.Алгоритмы. // <- тут не сработает
```
3. Вызвать подсказку после "Справочники.Алгоритмы.". Она не сработает и не будет события "EVENT_GET_METADATA"
3. Если сначала проверить на "Справочники.", а затем на "Справочники.Алгоритмы.", то сработает. Так как будет сначала события EVENT_GET_METADATA для "справочники", а затем для "справочники.алгоритмы".

**Comment by salexdv** [comment]
Проверю

**Comment by GenVP** [comment]
Я, думаю, нашел как исправить. но не уверен, что оптимально:

![image](https://user-images.githubusercontent.com/34754769/119533925-06faba00-bd8f-11eb-93a0-470212dd7667.png)

**Comment by salexdv** [comment]
> Я, думаю, нашел как исправить. но не уверен, что оптимально:

Оно и так должно срабатывать по идее, я посмотрю в чём дело.

**Comment by salexdv** [comment]
Должно заработать. Спасибо!

**Comment by GenVP** [comment]
Да, работает.
