### ISSUE TITLE
При нажатии ENTER в строке без печатных символов удаляются все непечатные символы

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#144]
Ввести в новой строке символ табуляции. Нажать ENTER. Произойдет переход на новую строку с сохранением табуляции левее каретки в новой строке, но в предыдущей строке табуляция удаляется. А ожидалось, что она останется.

![изображение](https://user-images.githubusercontent.com/11896251/119534817-00207700-bd90-11eb-8c2b-a0344d7875e5.png)

**Comment by salexdv** [comment]
Это не ошибка, а стандартное поведение редактора. В VSCode работает также. Конфигуратор так не делает, но простого способа изменить такое поведение я не знаю.

**Comment by tormozit** [comment]
Почему тут поведение конфигуратора мне кажется удобнее, чем VSCode, имеет смысл пояснить?
Хотя я не любитель пустых строк, но многим они нравятся. Забочусь о них)

**Comment by salexdv** [comment]
> Почему тут поведение конфигуратора мне кажется удобнее, чем VSCode, имеет смысл пояснить?
> Хотя я не любитель пустых строк, но многим они нравятся. Забочусь о них)

Я понимаю, что это привычно, но изобретать велосипед ради этого не хочется. Если мне попадется на глаза простой способ отключить это, сделаю.

**Comment by salexdv** [comment]
Нашел опцию редактора. Попробуй у себя при замене `customOptions` в исходниках добавить `trimAutoWhitespace: false`. Если устроит новое поведение, добавлю в проект.

**Comment by tormozit** [comment]
Проверил. Да. так работает намного привычнее.

**Comment by tormozit** [comment]
Заработало.
