### ISSUE TITLE
Сломался список автодополнения 

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#145]
Обновился на последний комит . Даже в чистом редакторе не заполняется список автодополнения

![изображение](https://user-images.githubusercontent.com/11896251/119602765-8c648580-bdf4-11eb-96c7-d12ec24bcb9d.png)

**Comment by salexdv** [comment]
> Обновился на последний комит . Даже в чистом редакторе не заполняется список автодополнения

Если открыть консоль (CTRL+SHIFT+I), что там написано? Я такой проблемы не наблюдаю, всё работает.

**Comment by tormozit** [comment]
![изображение](https://user-images.githubusercontent.com/11896251/119605466-84f3ab00-bdf9-11eb-8195-163dda34c028.png)

[Консоль кода HTML.zip](https://github.com/salexdv/bsl_console/files/6543932/HTML.zip)

**Comment by salexdv** [comment]
Исправил

**Comment by tormozit** [comment]
Заработало
