### ISSUE TITLE
При установке/открытии подсказки по вызову метода хочу указывать текущую сигнатуру

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#146]
Сейчас я не могу указать текущую сигнатуру в методе setCustomSignatures() и ты открываешь первую

![изображение](https://user-images.githubusercontent.com/11896251/119604172-51b01c80-bdf7-11eb-8af3-56d014e61b01.png)

А ведь параметров по факту больше одного и она явно не подходит в этом месте. Поэтому я подбираю первую с не меньшим числом параметров.

![изображение](https://user-images.githubusercontent.com/11896251/119604254-6db3be00-bdf7-11eb-9f0c-f77a427878b6.png)

Хочу в твоей подсказке по вызову метода параметр для указания текущей сигнатуры. 
Ну и тебе имеет смысл сделать подобный анализ при открытии внутренним механизмом.

**Comment by salexdv** [comment]
У редактора нет возможности указать номер открываемой сигнатуры
