### ISSUE TITLE
Редактор блокирует сочетание ALT+[, хотя не блокирует ALT+]

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#147]
Очень нужно разблокировать сочетание RightALT+[, т.к. сочетания RightALT+[ и RightALT+] [используются](https://1c.chistov.pro/2012/11/1.html) многими для ввода квадратных скобок без переключения языка ввода (на русском).

**Comment by tormozit** [comment]
Подозреваю что я смогу это сделать через универсальное отключение обработки сочетаний клавиш, которое ты для меня сделал - disableKeyBinding(). Но уверен, что и это будет полезно за пределами моего продукта, т.е. лучше сделать в твоей поставке.

**Comment by salexdv** [comment]
Редактор сам по себе ничего не блокирует. В браузере всё работает, как положено. Пока непонятно, из-за чего возникает проблема. `disableKeyBinding` её не решает.

**Comment by tormozit** [comment]
В режиме встроенного языка при решении реальных задач не могу пользоваться твоим редактором из-за этой беды, т.к. вводить квадратные скобки надо относительно часто. Каждый раз спотыкаюсь об нее и переключаюсь обратно во встроенный редактор, где у меня ALT+[ позволяет мне вводить левую квадратную скобку без переключения языка ввода.

**Comment by salexdv** [comment]
Проблему исправил, но решение так себе.

**Comment by tormozit** [comment]
Вроде работает. Почему ты не доволен решением?

**Comment by salexdv** [comment]
> Вроде работает. Почему ты не доволен решением?

Мне кажется, это костыль. В браузере и так всё работает, это какой-то глюк поля HTML-документа.

**Comment by tormozit** [comment]
Обнаружил что в некоторых случаях при нажатии ALT+[ выполняется выделение фрагмента до закрывающей скобки.  Происходит во всех языках. 
![изображение](https://user-images.githubusercontent.com/11896251/120266869-7569db80-c2ab-11eb-9896-9758192d6311.png)
![изображение](https://user-images.githubusercontent.com/11896251/120266891-80247080-c2ab-11eb-9500-bb5184ff53c2.png)

Видео приложил
[Неожиданное выделение квадратных скобок.zip](https://github.com/salexdv/bsl_console/files/6573360/default.zip)

**Comment by salexdv** [comment]
> Обнаружил что при нажатии ALT+[ в русской 1С раскладке после печати "[" выполняется выделение фрагмента до следующей закрывающей квадратной скобки. Происходит во всех языках.
> При быстром наборе это естественно приводит к удалению выделенного фрагмента текста. Поэтому проблема важная.

Ох уж это поле HTML-документа. Теперь выделение фрагмента между скобками `SHIFT+ALT+B`. Уж не знаю, как могло нажатие `ALT+[` вызывать `CTRL+ALT+[`

**Comment by tormozit** [comment]
Еще заметил что в английской раскладке в твоем редакторе ALT+[ печатает "[" и издает системный звук (как при нажатии недопустимого сочетания клавиш), а нажатие ALT+] не печатает символа и издает такой же звук. При этом в во встроенном редакторе при их нажатии происходит ничего. Я в английской раскладке почти не пишу. Поэтому для меня это неважно.
