### ISSUE TITLE
Ошибка. Некорректно подцвечивается КОНЕЦ из ВЫБОР...

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#148]
![Screenshot_1](https://user-images.githubusercontent.com/48444742/119632712-bbd9b900-be19-11eb-9ec8-e854314884cd.png)

**Comment by Evg-lylyk** [comment]
И 1 у имени поля должна быть черного цвета

**Comment by salexdv** [comment]
Исправил
