### ISSUE TITLE
Не закрывается панель поиска текста

### ISSUE THREAD

**Issue by aleksandr-ermakov** [salexdv/bsl_console#149]
![image](https://user-images.githubusercontent.com/28656669/119639267-812b4d00-be28-11eb-8aed-957f5325459b.png)

Когда В основном окне нажимаем Ctr+F
  И Нажимаем в панели "крестик" или нажимаем Esc
Тогда Панель становится недоступна и не закрывается.

**Comment by salexdv** [comment]
> Когда В основном окне нажимаем Ctr+F
> И Нажимаем в панели "крестик" или нажимаем Esc
> Тогда Панель становится недоступна и не закрывается.

В обработке, выложенной в релизах, действительно наблюдается такое поведение. Это уже исправлено, и в новом релизе всё будет хорошо.

**Comment by salexdv** [comment]
Исправлено в релизе [**0.2.6**](https://github.com/salexdv/bsl_console/releases/tag/v0.2.6)
