### ISSUE TITLE
Пропадает картинка слева от слова в списке автодополнения

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#150]
Ненамеренно задал такое детальное описание метода
```
Структура

Параметры:
ТаблицаФормы
```
При активации его строки в списке автодополнения пропадает картинка слева от слова
![изображение](https://user-images.githubusercontent.com/11896251/119763963-34438700-beb9-11eb-9ab5-e5fd178dbcfb.png)

**Comment by salexdv** [comment]
Не удалось воспроизвести

![editor](https://user-images.githubusercontent.com/6356534/119775524-66121900-becc-11eb-93ed-c9e61866e6ee.png)

**Comment by tormozit** [comment]
Попробуй навести на слово указателем мыши

![изображение](https://user-images.githubusercontent.com/11896251/119776231-53e4aa80-becd-11eb-9a81-0b88a1008efc.png)

**Comment by salexdv** [comment]
> Попробуй навести на слово указателем мыши

Всё равно картинка на месте. Можешь выложить сюда полный JSON, который отдаешь для `showCustomSuggestions`?

**Comment by tormozit** [comment]
JSON описание этого метода ниже
```
{
"name": "ТабличноеПолеКлючСтрокиЛкс",
"text": "ТабличноеПолеКлючСтрокиЛкс",
"kind": "Method",
"detail": "Структура\n\n Параметры:\n  ТаблицаФормы\u0009\u0009 ",
"documentation": "Метаданные"
}
```

**Comment by salexdv** [comment]
Неуловимый глюк:
![B2Hn9edw0n](https://user-images.githubusercontent.com/6356534/119936583-1138d600-bf92-11eb-9b66-eca0628642fe.gif)

**Comment by tormozit** [comment]
Нужно навести указатель мыши на строку списка. Только тогда картинка пропадает.

**Comment by tormozit** [comment]
Вот список с двумя соседями
```
 {
"name": "СтрокаТабличнойКоллекцииПоКлючуЛкс",
"text": "СтрокаТабличнойКоллекцииПоКлючуЛкс",
"kind": "Method",
"detail": "",
"documentation": "Метаданные"
},
{
"name": "ТабличноеПолеКлючСтрокиЛкс",
"text": "ТабличноеПолеКлючСтрокиЛкс",
"kind": "Method",
"detail": "Структура\n\n Параметры:\n  ТаблицаФормы\u0009\u0009 ",
"documentation": "Метаданные"
},
{
"name": "ТабличноеПолеКлючиСтрокЛкс",
"text": "ТабличноеПолеКлючиСтрокЛкс",
"kind": "Method",
"detail": "??,  ",
"documentation": "Метаданные"
}
```

**Comment by salexdv** [comment]
Всё равно не удается воспроизвести

![editor](https://user-images.githubusercontent.com/6356534/120239267-8e03d280-c266-11eb-9407-4a3115e06023.png)

Насколько часто возникает проблема. Она еще актуальна?

**Comment by tormozit** [comment]
Теперь не удается воспроизвести. Я видел такую проблему только на одном слове, хотя и стабильно.
