### ISSUE TITLE
Отсутствует описание ОбменДанными для Объект

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#151]
Пример
Объект = Строка.Ссылка.ПолучитьОбъект();
Объект. <Тут нет ОбменДанными>

Важно, это часто используется поставить
Объект.ОбменДанными.Загрузка = Истина;

и еще здесь де не хватает ДополнительныеСвойства - Структура

**Comment by salexdv** [comment]
Добавил для справочников и документов. Позже сделаю расширю список объектов. Для существующего кода пока работать не будет.
