### ISSUE TITLE
Проблема с подсказкой при открытии существующего кода

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#152]
Объект = Строка.Ссылка.ПолучитьОбъект();
Объект."Нет подсказки!!!"
Объект.Записать();

Строка.Ссылка - это пользовательский объект тип ...Ссылка

**Comment by salexdv** [comment]
Прошу проверить, осталась ли проблема после доработки.

**Comment by Evg-lylyk** [comment]
Проверил все работает, спасибо
