### ISSUE TITLE
В режиме СКД некоторые операторы заглавными буквами

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#153]
Вроде думали - решали что в языке СКД делать операторы с большой буквы прописными
сейчас помогает с заглавными аналогично запросу:
ИСТИНА, ЛОЖЬ, ВЫБОР, КОГДА, ИНАЧЕ, КОНЕЦ

**Comment by salexdv** [comment]
> Вроде думали - решали что в языке СКД делать операторы с большой буквы прописными
> сейчас помогает с заглавными аналогично запросу:
> ИСТИНА, ЛОЖЬ, ВЫБОР, КОГДА, ИНАЧЕ, КОНЕЦ

Разговор был только про функции. У ключевых слов регистр я не менял

**Comment by Evg-lylyk** [comment]
Здесь тоже лучше помять ведь шаблон выбор, вставдяет прописными

**Comment by salexdv** [comment]
Исправлено
