### ISSUE TITLE
При вызове метода setSelectionByLength не происходит прокрутки видимой области в тексте на выделение

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#155]
Есть большой текст и видимая область его находится в его начале. В другом элементе формы 1С я выполняю setSelectionByLength(1000, 1000), т.е. выделяю фрагмент за пределами видимой области текста. При этом выделение корректно устанавливается в тексте, но видимая область текста не сдвигается так, чтобы отобразить выделение. Ожидал, что как и у всех подобных редакторов при этом произойдет прокрутка видимой области в такое положение, чтобы начало выделения стало видимым.

**Comment by salexdv** [comment]
Доработал. Прошу проверить.

**Comment by tormozit** [comment]
Не заработало

**Comment by tormozit** [comment]
Заработало. 
Но на мой взгляд это все же скорее ошибка чем фича. Каретка (текстовый курсор) всегда должна быть видна, когда фокус ввода в текстовом поле. А тут он в невидимую область уходит, т.е. пользователь не видит куда он будет вводить символ.

**Comment by salexdv** [comment]
Нет, это не ошибка. Метод выполнял ровно одну задачу, которая описана в его названии. Ты сам пишешь, что видимая область находится в самом начале, а в другом элементе ты вызываешь метод. Непонятно, как тогда пользователь меняет область ему в данный момент невидимую.

**Comment by tormozit** [comment]
ПолеТекстовогоДокумента и ПолеВвода работает так как я описал. Выделение вне видимой области чаще всего используется при поиске строки в тексте. Например ты то же самое делаешь по команде "найти следующее/предыдущее".
