### ISSUE TITLE
После ввода строки "если" к ней справа сразу дописывается "конецесли"

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#157]
После ввода строки "если" к ней слева сразу дописывается "конецесли". Такая проблема появился в сегодняшних доработках.

![изображение](https://user-images.githubusercontent.com/11896251/119885675-ccce1b80-bf3a-11eb-933e-00df308ee4c5.png)

**Comment by salexdv** [comment]
Внес изменение, теперь дописываться не будет

**Comment by tormozit** [comment]
Заработало.

**Comment by salexdv** [comment]
Можно добавить автозакрытие для круглых и квадратных скобок. Как думаешь, удобно так будет?

**Comment by tormozit** [comment]
Пробовал такую фичу в снегопате или турбоконфе. Не понравилось. Часто были нежелательные срабатывания.

**Comment by salexdv** [comment]
Сделаю опционально
