### ISSUE TITLE
Неожиданно выделяется весь текст при выделении мышкой заголовка окна изменений текста

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#158]
Если зажать и удерживать левую кнопку мыши в области заголовка ("changes" или что то на русском) окна изменений текста и затем увести ее влево за пределы окна, то неожиданно выделяется весь текст. Ожидал, что выделения текста снаружи от окна изменений - не будет происходить.
![изображение](https://user-images.githubusercontent.com/11896251/119889721-9c3cb080-bf3f-11eb-9e55-151b9a6537e5.png)

**Comment by tormozit** [comment]
Аналогичная проблема и с окном детальной информации по строке списка автодополнения

![изображение](https://user-images.githubusercontent.com/11896251/119930337-eea1bf80-bf87-11eb-8b14-34acdb4612da.png)

**Comment by tormozit** [comment]
Цвет выделения тут кстати совсем не желтый. Также при этом меняется цвет у статусной строки

![изображение](https://user-images.githubusercontent.com/11896251/119930566-5ce68200-bf88-11eb-84e6-caf60c41d815.png)

**Comment by tormozit** [comment]
Аналогичная проблема и с выделением текста в статусной строке

**Comment by salexdv** [comment]
Это проблема поля HTML-документа, а не редактора.
