### ISSUE TITLE
При выборе кликом мышки слова из списка автодополнения после обработки события стирается весь текст строки правее каретки

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#159]
Допустим каретка стоит перед скобкой и я вызываю список автодополнения. В нем я кликом выбираю элемент.

![изображение](https://user-images.githubusercontent.com/11896251/119890601-b62ac300-bf40-11eb-9bcf-fafa6a838a1e.png)

При этом вызывается событие EVENT_ON_SELECT_SUGGEST_ROW и выполняется мой обработчик:

```
	РедакторHTML = ПолеТекста.ЭлементФормы.Документ.defaultView;
	РедакторHTML.hideSuggestionsList();
	КончитьОбработкуКоманды();
	РазобратьТекущийКонтекст();
	СтрокаТаблицыСлов = ТаблицаСлов.Найти(ЧистоеСловоСпискаПодсказкиHTML(ВыбранноеСлово), "Слово");
	Если СтрокаТаблицыСлов = Неопределено Тогда
		Возврат;
	КонецЕсли; 
	Если ирОбщий.СтрНачинаетсяСЛкс(Триггер, "force-") Тогда
		ПараметрЗакрытия = Прав(Триггер, 1);
	Иначе
		ПараметрЗакрытия = Истина;
	КонецЕсли; 
	ВставитьВыбранноеСловоАвтодополнения(СтрокаТаблицыСлов, мКонкретныйТипКонтекста, мСтруктураТипаКонтекста,, ПараметрЗакрытия);
	УстановитьГраницыВыделения();
	Если ПараметрЗакрытия = "." Тогда
		РедакторHTML.triggerSuggestions();
	КонецЕсли; 
	Если мОткрытьСправкуПоПараметру = Истина Тогда
		#Если ТолстыйКлиентОбычноеПриложение Тогда
			ОткрытьСправкуПоПараметру(, Ложь); 
		#Иначе
			РедакторHTML.triggerSigHelp();
		#КонецЕсли
	КонецЕсли; 
```
Он вставляет правильный текст (это становится понятно после нажатия CTRL+Z). Но сразу после этого редактор затирает его вставку и все окончание строки - даже тот текст, который был до этого (на картинке ";"). 

![изображение](https://user-images.githubusercontent.com/11896251/119890613-b88d1d00-bf40-11eb-9776-3117d149a628.png)

Вероятность что это делает мой код - очень мала, т.к. все вставки у меня идут через одно место в коде.

**Comment by salexdv** [comment]
Почему ты сразу не передаешь правильный текст, который надо вставить, ведь контекст, я так понимаю, тебе полностью известен?

**Comment by tormozit** [comment]
Я передаю сразу правильный текст и он вставляется. Но потом редактор его стирает и пишет выбранное слово из списка автодополнения.

**Comment by salexdv** [comment]
> Я передаю сразу правильный текст и он вставляется. Но потом редактор его стирает и пишет выбранное слово из списка автодополнения.

Я не про тот текст, который ты вставляешь при возникновении события `EVENT_ON_SELECT_SUGGEST_ROW `. Почему ты не передаешь правильный текст для вставки в `showCustomSuggestions`, чтобы редактор сам вставил сразу то, что нужно?

**Comment by tormozit** [comment]
Потому что мне нужно смещать каретку после вставки, т.е. нужно не просто вставлять текст, но и проводить более сложные операции.

**Comment by salexdv** [comment]
> Потому что мне нужно смещать каретку после вставки, т.е. нужно не просто вставлять текст, но и проводить более сложные операции.

Смещение каретки будет попроще вставки текста, как мне кажется

**Comment by tormozit** [comment]
Также анализ "Нужно ли добавлять скобки и сколько скобок и нужно ли смещать каретку и т.д." также требует вычислений, зависящих от типа каждого слова. Делать это перед отображением списка - неоправданное ожидание для пользователя.

**Comment by salexdv** [comment]
> Также анализ "Нужно ли добавлять скобки и сколько скобок и нужно ли смещать каретку и т.д." также требует вычислений, зависящих от типа каждого слова.

Я так понимаю, ты всё равно так или иначе делаешь эти вычисления, чтобы указать поле `kind` для передачи в `showCustomSuggestions`

**Comment by salexdv** [comment]
Если всё оставить, как есть, то единственное, что пока приходит на ум - это формировать событие `EVENT_ON_SELECT_SUGGEST_ROW` с некоторой задержкой, чтобы редактор успел вставить текст, до того, как ты будешь что-то менять из 1С

**Comment by salexdv** [comment]
Еще можно передавать пустое поле `text`, тогда вставки вообще не будет.

**Comment by tormozit** [comment]
> можно передавать пустое поле `text`, тогда вставки вообще не будет.

В моем случае это допустимо, т.к. я всегда вставляю выбранное слово сам. 
Убрал заполнение атрибута text при подготовке данных списка автодополнения. Проблема ушла.

Однако в редакторе она осталась.

**Comment by salexdv** [comment]
Нет в редакторе такой проблемы, или мы говорим о разном.
![Ar0V235Qw9](https://user-images.githubusercontent.com/6356534/120901878-02af8600-c646-11eb-8504-01139303fca4.gif)
Редактор вставляет ровно то, что ему передано для вставки, ничего он при этом не стирает.
Тут проблема асинхронного взаимодействия т.к. нет возможности из 1С прервать вставку. Событие EVENT_ON_SELECT_SUGGEST_ROW прилетает в 1С, ты вставляешь свой текст, но сразу после этого отрабатывает родное событие вставки выбранного значения. Видимо, оно происходит с некоторой задержкой, и ты в этот момент успеваешь вставить текст.

**Comment by tormozit** [comment]
> Нет в редакторе такой проблемы

Согласен. Я некорректно указал, что проблема осталась "для случая стандартной обработки". Она осталась только для случая собственной вставки и заполненного атрибута text у слов списка автодполнения.

**Comment by salexdv** [comment]
Я согласен, было бы классно при получении события подавлять сразу родную обработку, что-то вроде `preventDefault()`, но к сожалению, такой возможности нет.

**Comment by tormozit** [comment]
В общем резюмирую для остальных читателей. Нужно либо не заполнять атрибут text в собственных элементах списка автодополнения, либо не вставлять выбранное слово в событии EVENT_ON_SELECT_SUGGEST_ROW.
