### ISSUE TITLE
Метод setCustomSignatures в режиме языка запросов и выражений компоновки данных не меняет подсказку по вызову метода

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#160]
В обработке события EVENT_BEFORE_SIGNATURE общей для всех программных языков редактора передаю в режиме языка выражений компоновки данных в метод setCustomSignatures описание метода ВычислитьВыражениеСГруппировкойМассив
```
{
"ВычислитьВыражениеСГруппировкойМассив": [
{
"label": "(Выражение, ВыраженияПолейГруппировки, ОтборЗаписей, ОтборГруппировок)",
"parameters": [
{
"label": "Выражение",
"documentation": "Обяз.: Да;  Возвр.: ?\nТип: \nОписание: "
},
{
"label": "ВыраженияПолейГруппировки",
"documentation": "Обяз.: Да;  Возвр.: ?\nТип: \nОписание: "
},
{
"label": "ОтборЗаписей",
"documentation": "Обяз.: Да;  Возвр.: ?\nТип: \nОписание: "
},
{
"label": "ОтборГруппировок",
"documentation": "Обяз.: Да;  Возвр.: ?\nТип: \nОписание: "
}
],
"documentation": ""
}
]
}
```
Событие вызывается. Мой код выполняется.
Но вижу это 
![изображение](https://user-images.githubusercontent.com/11896251/119935879-e601b700-bf90-11eb-8071-99beb33b72d2.png)
В режиме языка запросов аналогично.

При этом в режиме встроенного языка вижу ожидаемое свое описание метода.

![изображение](https://user-images.githubusercontent.com/11896251/119936370-bbfcc480-bf91-11eb-9cc4-ddddd24e61ea.png)

**Comment by salexdv** [comment]
Доработал. Проверь, пожалуйста.

**Comment by tormozit** [comment]
Не заработало. Теперь вообще перестала в этих режимах появляться подсказка по вызову метода

**Comment by salexdv** [comment]
Детальная информация явно из setCustomSignatures

![OeayiNVHpx](https://user-images.githubusercontent.com/6356534/120117443-ec14b500-c195-11eb-80dd-d18475c687d8.gif)

Возможно, из 1С по другому работает, я проверял только в браузере. Чуть позже посмотрю в режиме Предприятия.

**Comment by tormozit** [comment]
Может хотя бы вернуть как было? А то в мне релиз класть совсем без подсказки по вызову метода не хорошо как то.

**Comment by tormozit** [comment]
Исключил влияние своего кода. Проблема возникает именно после выполнения switchQueryMode() или switchDCSMode(). Попробовал закомментировать эти строки (оставить режим встроенного языка) и подсказка по вызову метода заработала во всех моих экземплярах редактора.

**Comment by salexdv** [comment]
Должно заработать

**Comment by tormozit** [comment]
Заработало.
Небольшая проблема - после ввода скобки появляется сразу обе подсказки - автодополнение и по вызову метода. Причем я при этом в событии EVENT_BEFORE_SHOW_SUGGEST вызываю hideSuggestionsList(). А список автодополнения (твой) все равно отображается.
![изображение](https://user-images.githubusercontent.com/11896251/120145360-0bd6c800-c1ec-11eb-8a18-eed6a4a8eb84.png)

**Comment by salexdv** [comment]
> Заработало.
> Небольшая проблема - после ввода скобки в большинстве случаев появляются сразу обе подсказки - автодополнение и по вызову метода.

Исправил

**Comment by tormozit** [comment]
Проблема ушла
