### ISSUE TITLE
При удалении символа слева от каретки выполняется вызов события EVENT_BEFORE_SHOW_SUGGEST

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#161]
При каждом удалении символа слева от каретки при открытом списке автодополнения выполняется вызов события EVENT_BEFORE_SHOW_SUGGEST. 
Предполагаю, что при ввода каждого символа редактор выбрасывает из списка те слова, которые не отвечают введенному пользователем фильтру. Поэтому когда пользователь "расширяет" фильтр путем удаления символа кнопкой Backspace, то ты снова выбрасываешь мне событие EVENT_BEFORE_SHOW_SUGGEST, чтобы получить полный список слов. 

Однако для меня это выливается в серьезные задержки, т.к. заполнение списка у меня выполняется 100-150мс и банальная операция "удалить ошибочно введенные последние N символов" для пользователя выливается в муки ожидания реакции программы длительностью N*[100:150мс]. 

Прошу сделать оптимизацию путем сохранения оригинального списка переданных мной слов и использование его при удалении последних символов.

![изображение](https://user-images.githubusercontent.com/11896251/120011499-06f4f700-bfe7-11eb-9c68-f144b9f69fee.png)

Кстати в этом случае params.trigger содержит Неопределено, а ожидалось "Backspace". Сейчас я даже отключить сам обработку этого события конкретно для этой ситуации не могу, т.к. не получаю признаков позволяющих однозначно ее выявить.
Кстати в этом случае params.ctrlKey почему то Истина. Тоже показалось немного странным.

**Comment by salexdv** [comment]
Что тебе мешает сохранить этот список на своей стороне и просто отдавать его, а не формировать заново? Можешь сделать соответствие, где ключом первые буквы слова, а в значении список. При EVENT_ON_SELECT_SUGGEST_ROW или через N сек очищаешь соответствие и всё. Это мало чем будет отличаться от хранения на стороне редактора за исключением издержек на генерацию события, но они минимальны.

**Comment by tormozit** [comment]
Сделаю хранение строки JSON у себя. Признак нажатия Backspace мне все равно хотелось бы получать от тебя, т.к. только в этом случае я буду его повторно использовать.

**Comment by salexdv** [comment]
> Признак нажатия Backspace мне все равно хотелось бы получать от тебя, т.к. только в этом случае я буду эту строку повторно использовать.

Почему? Ты разве не весь список формируешь сразу по первым буквам? Я предлагаю добавить событие EVENT_ON_BLUR_SUGGEST и тогда при его возникновении или при EVENT_ON_SELECT_SUGGEST_ROW ты точно будешь знать, что список больше не нужен

**Comment by tormozit** [comment]
По какому принципу ты будешь вызывать событие EVENT_ON_BLUR_SUGGEST?

**Comment by salexdv** [comment]
> По какому принципу ты будешь вызывать событие EVENT_ON_BLUR_SUGGEST?

При исчезновении списка подсказок (выбор элемента, или просто закрытие списка по Esc или отсутствию совпадений по фильтру). Пока это только теория.

**Comment by tormozit** [comment]
Такое событие мне не поможет, т.к. будут залипания списка и мне все равно придется городить свой анализ для ответа на вопрос "Надо ли перестраивать список?". 
Давай начнем с простого и понятного - передачи признака "Заполнение списка вызвано по нажатию Backspace". Пока только эта ситуация вызывает ощутимый дискомфорт ("тормоза").

**Comment by salexdv** [comment]
> Такое событие мне не поможет, т.к. будут залипания списка и мне все равно придется городить свой анализ для ответа на вопрос "Надо ли перестраивать список?".
> Давай начнем с простого и понятного - передачи признака "Заполнение списка вызвано по нажатию Backspace". Пока только эта ситуация вызывает ощутимый дискомфорт ("тормоза").

Это я постараюсь сделать. Никак не пойму зачем ты перестраиваешь список. Ты его не сразу формируешь целиком?

**Comment by tormozit** [comment]
Список я формирую сразу целиком. Однако решение о его перестроении/=перезаполнении я не принимал ранее, т.к. твое событие приходило достаточно редко и потому не вызывало дискомфорта. За исключением рассматриваемой тут ситуации. Чтобы всегда правильно принимать решение о том, нужно ли обновлять/=перестраивать/=перезаполнять список, нужно сравнивать весь текст (исключая текущее слово) в момент его последнего построения и в момент решения о новом перестроении. Например можно использовать хеш фукнкцию от старого и нового состояния. Но текст может быть большим и потому каждый раз ее вычислять будет накладно.

**Comment by salexdv** [comment]
> При каждом удалении символа слева от каретки при открытом списке автодополнения выполняется вызов события EVENT_BEFORE_SHOW_SUGGEST.

Только что проверил и в браузере и в 1С. Событие `EVENT_BEFORE_SHOW_SUGGEST` вызывается только при появлении списка.

![Wnm7WAdWMt](https://user-images.githubusercontent.com/6356534/120116200-a81eb180-c18f-11eb-817f-33a87a196ab3.gif)

**Comment by tormozit** [comment]
Да. Не совсем все условия я описал. Надо установить каретку в конец слова. Вызывать список автодополнения. Нажимать клавишу Backspace.

**Comment by salexdv** [comment]
> Да. Не совсем все условия я описал. Надо при закрытом списке автодополнения установить каретку в конец слова. Вызывать список автодополнения. Нажимать клавишу Backspace.

Это всё меняет. Логика работы редактора тут понятна и генерация `EVENT_BEFORE_SHOW_SUGGEST` выглядит вполне ожидаемо.
Можешь рассказать, как ты строишь список например, для слов *запро* и *за*, список будет одинаковым и в первом и во втором случае?

**Comment by tormozit** [comment]
Я строю полный список сразу. Я его не фильтрую по фрагменту слова левее каретки до точки. Это делает только твой редактор.

**Comment by salexdv** [comment]
> Я строю полный список сразу. Я его не фильтрую по фрагменту слова левее каретки до точки. Это делает только твой редактор. Состав моего списка зависит грубо говоря только от того что находится от начала текста до ближайшей точки слева от каретки и от всех целых инструкций после каретки.

То есть для слов `запро`, `за` и `закр` список у тебя 100% будет одинаковым?

**Comment by tormozit** [comment]
> То есть для слов `запро`, `за` и `закр` список у тебя 100% будет одинаковым?

Да, если остальной текст совпадает.

**Comment by salexdv** [comment]
> > То есть для слов `запро`, `за` и `закр` список у тебя 100% будет одинаковым?
> 
> Да, если остальной текст совпадает.

Понял. Буду думать, как сделать оптимально.

**Comment by salexdv** [comment]
Расширил список триггеров, которые будут приходить в параметрах события, теперь там есть `backspace`. Попробуй.

**Comment by tormozit** [comment]
Задержка стала меньше, но все равно заметна. Основное время уходит на выполнение метода 
showCustomSuggestions()
![изображение](https://user-images.githubusercontent.com/11896251/120146923-830d5b80-c1ee-11eb-9766-b2b5d227abf2.png)

**Comment by salexdv** [comment]
> Задержка стала меньше, но все равно заметна. Основное время уходит на выполнение метода
> showCustomSuggestions()

Ну с этим я уже вряд ли что-то сделаю. Хранить список на своей стороне я не могу. Вернее хранить могу, но не могу однозначно определить, когда нужно его показывать т.к. не знаю всего контекста. Ты на своей стороне формируешь весь список сразу, а кто-то, возможно, формирует по первым буквам, поэтому отдавать список должна 1С-ка. Единственное, что могу предложить - это добавить какой-нибудь метод, который будет говорить редактору, что надо показать предыдущий список, например, `showPreviousCustomSuggestions()`

**Comment by tormozit** [comment]
Да. Мою проблему метод showPreviousCustomSuggestions() решит.

**Comment by salexdv** [comment]
> Да. Мою проблему метод showPreviousCustomSuggestions() решит.

Добавил. Попробуй.

**Comment by tormozit** [comment]
Метод showPreviousCustomSuggestions работает как ожидалось. Он выполняется в 2 раза быстрее, чем showCustomSuggestions() с передачей готовой строки JSON. Стало лучше.
Однако визуально все равно заметны пропуски "кадров", т.е. паузы в отрисовке списка автодополнения и удаления символов. Хотя по замеру в 1С уже достаточно быстро отработает наш код.
Похоже это возникает потому, что редактор обновляет картинку по хитрому алгоритму, адапатирующемуся к скорости изменения текста.

Сценарий этот не частый. Поэтому оставшееся неудобство можно считать приемлемым, хотя и заметным.

**Comment by tormozit** [comment]
После использования метода showPreviousCustomSuggestions() заметил беду.
В пустом поле я ввел строку 
`Мета`
и каретка находится справа от нее. Нажимаю CTRL+SPACE. Появляется список автодополнения. Нажимаю многократно Backspace до удаления всех букв. Ввожу букву любую, например 
`М`
Нажимаю CTRL+SPACE. При этом событие вывывается и но окно списка автодополнения не появляется. Если удалить весь текст и нажать CTRL+SPACE, то окно автодополнения появляется. Также если убрать и вернуть фокус с полю и затем нажать CTRL+SPACE, то окно автодополнения появляется.

**Comment by tormozit** [comment]
Еще иногда появляется иконка открытия подробной информации 
![изображение](https://user-images.githubusercontent.com/11896251/120223900-ffce2300-c24a-11eb-9280-865218389c0d.png)
Похоже что окно вроде создается, но почему то не рисуется.

**Comment by tormozit** [comment]
Кажется еще вчера такой беды не было. Появилась она кажется сегодня утром с первыми правками.

**Comment by salexdv** [comment]
> Еще иногда при таком нажатии CTRL+SPACE без появления списка автодополнения появляется иконка открытия подробной информации в таком месте, как будет спискок на самом деле отображается
> Похоже что окно вроде создается, но почему то не рисуется.

Воспроизвести такое не смог, но есть предположение, почему такое могло происходить. Внес изменения.

**Comment by salexdv** [comment]
> Заметил новую беду. Проявляется даже без вызова showPreviousCustomSuggestions().
> В пустом поле я ввел строку
> `М`
> и каретка находится справа от нее. Нажимаю CTRL+SPACE. Появляется список автодополнения. Нажимаю Backspace при открытом списке автодополнения. Символ удаляется. Каретка сдвигается левее. Список автодополнения исчезает.
> Далее снова ввожу любую букву, например опять
> `М`
> и каретка находится справа от нее. Нажимаю CTRL+SPACE. При этом событие вызывается и мой код как обычно вызывает showCustomSuggestions(), но окно списка автодополнения не появляется. Если удалить весь текст и нажать CTRL+SPACE, то окно автодополнения появляется. Также если убрать и вернуть фокус с полю и затем нажать CTRL+SPACE, то окно автодополнения появляется.

У себя не смог такое воспроизвести.

**Comment by tormozit** [comment]
Похоже ты мне в параметре trigger стал слать что то новое.
Например в пустом тексте ввожу 
`м`
Событие приходит и в триггере "4". Это умышленно или какая то ошибка?

**Comment by salexdv** [comment]
> Похоже ты мне в параметре trigger стал слать что то новое.
> Например в пустом тексте ввожу
> `м` (русская)
> Событие EVENT_BEFORE_SHOW_SUGGEST приходит и в триггере строковое значение "4". Это умышленно или какая то ошибка?

Нет, это не ошибка, там может быть любая буква, вызвавшая появление подсказки. Еще может быть `space`, `backspace`, `.`
У меня нет инструмента, чтобы отслеживать все триггеры, поэтому я просто сохраняю код последней клавиши и преобразовываю его в триггер при формировании события. Иным способом передать тебе `backspace` я просто не могу.

**Comment by tormozit** [comment]
Оказалось все проблемы возникли из-за изменившегося алгоритма установки значения триггера. Цифры у меня игнорировались и Неопределено играло важную роль
```

		Если Ложь
			Или Триггер = Неопределено // Вызов явный
			Или Триггер = "." И Последние2Символа <> ".."
			Или ЯзыкПрограммы <> 0 И Триггер = "&" И Последние2Символа <> "&&"
			Или ЯзыкПрограммы = 0 И Триггер = """" И Последние2Символа <> """"""
			Или ирОбщий.ЛиИмяПеременнойЛкс(Триггер) // Иначе слишком часто вызывается затратное обновление списка слов локального контекста
			Или ЯзыкПрограммы = 0 И ирОбщий.СтрокиРавныЛкс(ПоследнееСлово, "новый")
			Или ЯзыкПрограммы = 0 И ирОбщий.СтрокиРавныЛкс(ПоследнееСлово, "new")
		Тогда 
			Если Триггер = "backspace" Тогда
				мРазрешенаПодсказкаHTML = Истина;
				РедакторHTML.showPreviousCustomSuggestions();
				мРазрешенаПодсказкаHTML = Ложь;
			Иначе
				ФормаВызовМетода = ФормаВызовМетода();
				Если ФормаВызовМетода.Открыта() Тогда
					ФормаВызовМетода.Закрыть();
				КонецЕсли; 
				КончитьОбработкуКоманды();
				РазобратьТекущийКонтекст();
				Если ЯзыкПрограммы = 0 И Триггер = """" Тогда
					ПоказатьСписок = мЭтоСтроковыйЛитерал;
				Иначе
					ПоказатьСписок = Не (мКонтекст = "" И Триггер = ".");
				КонецЕсли; 

```

**Comment by salexdv** [comment]
> Оказалось все проблемы возникли из-за изменившегося алгоритма установки значения триггера. Цифры у меня игнорировались и Неопределено играло важную роль.
> Прошу пояснить новую логику наполнения тригера.

В триггер может передаваться любой символ, вызвавший появление подсказки. Заранее известные значения:
1. `space` (CTRL+SPACE)
2. `backspace`
3.  `.` - точка
4. `"` - двойная кавычка
5. Пробел
6. Для языка запросов и СКД `(`, `&`

Не думаю, что тебе надо обрабатывать что-то кроме этих значений.

**Comment by tormozit** [comment]
Можно ли как то вернуть обратно заполнение триггера, но добавить только BackSpace?
Вместо буквы "П" мне приходит "%". А спецсимволы я игнорирую умышленно, чтобы не делать лишний заполнений списка.

**Comment by salexdv** [comment]
> Можно ли как то вернуть обратно заполнение триггера, но добавить только BackSpace?

Сделал

**Comment by tormozit** [comment]
Заработало.
