### ISSUE TITLE
При вводе хххххххххххххххххххххххх список автодополнения показывает слово

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#162]
Для строки
`хххххххххххххххххххххххх` 
получаю непустой список
![изображение](https://user-images.githubusercontent.com/11896251/120022302-e764cb00-bff4-11eb-829e-b43627ad66c7.png)

Это так и задумано?

**Comment by tormozit** [comment]
А вот еще интереснее пример. Для строки
`Длинношеее`
получаю список, в котором слова не содержат "ш"
![изображение](https://user-images.githubusercontent.com/11896251/120022763-88ec1c80-bff5-11eb-8219-81f3dd183775.png)

**Comment by tormozit** [comment]
Тут тоже непонятна логика
![изображение](https://user-images.githubusercontent.com/11896251/120023315-49720000-bff6-11eb-8308-4b7045b04a28.png)

**Comment by salexdv** [comment]
К сожалению, это неотключаемое поведение редактора. Видимо, некая защита от опечаток. Ничего с этим сделать нельзя.

**Comment by tormozit** [comment]
Надо бы задокументировать алгоритм фильтрации и сортировки списка хотя бы в общих чертах.

**Comment by salexdv** [comment]
> Надо бы задокументировать алгоритм фильтрации и сортировки списка хотя бы в общих чертах.

Я даже monaco/VSCode не нашел нормального описания этого алгоритма.
