### ISSUE TITLE
Переключение из любого языка в любой

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#163]
В документации отсутствует функция switchDCSMode. Неплохо бы ее там указать.
Также было бы здорово в одном месте где то описать, как установить каждый из поддерживаемых программных языков, независимо от текущего состояния редактора: 
- встроенный язык
- язык запросов
- язык выражений СКД

Например я не знаю простого способа переключиться из режима языка запросов в режим встроенного языка. Нашел только такой 
```
	РедакторHTML.queryMode = Ложь;
	РедакторHTML.DCSMode = Ложь;
	РедакторHTML.switchLanguageMode();
```
Иными словами сейчас многие методы переключения языка корректно работают только при первом вызове, т.е. могут не работать после вызова других методов переключения языка.

![изображение](https://user-images.githubusercontent.com/11896251/120108389-a3490600-c16d-11eb-9920-b461f60c6fba.png)

**Comment by tormozit** [comment]
После вызова 	
`РедакторHTML.compare(Текст2, Истина, Истина, Истина);`
вызов
		```
РедакторHTML.switchLanguageMode();
```
Не включает подсветку встроенного языка

**Comment by salexdv** [comment]
`switchQueryMode`, `switchDCSMode` и `switchXMLMode` работают в обе стороны т.е. это переключение из текущего режима в указанный и обратно. Если из режима редактирования кода ты вызвал `switchQueryMode`, то чтобы вернуться обратно из режима запроса надо опять вызвать `switchQueryMode`
```js
// Тут мы находимся в режиме редактирования кода
switchQueryMode();
// Теперь в режиме редактирования запроса
switchDCSMode();
// Теперь в режиме СКД
switchDCSMode();
// Теперь опять в режиме запроса
switchQueryMode();
// Вернулись в режим редактирования кода
```

**Comment by tormozit** [comment]
Так это же много лишних вычислений - в 2 раза больше чем можно было бы сделать. Не хорошо как то. Сейчас я сделал без этих двойных переключений. Но после переключения в режим XML переключения перестают выполняться корректно.

```
	РедакторHTML.queryMode = Ложь;
	РедакторHTML.DCSMode = Ложь;
	ПодменюСинтаксис = ЭлементыФормы.ДействияФормы.Кнопки.Синтаксис.Кнопки;
	ПодсветкаСинтаксиса = ВариантСинтаксиса <> "Нет";
	РежимXML = Ложь;
	Если ВариантСинтаксиса = ПодменюСинтаксис.ВстроенныйЯзык.Имя Тогда
		РедакторHTML.switchLanguageMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.ЯзыкЗапросов.Имя Тогда
		РедакторHTML.switchQueryMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.ЯзыкКомпоновки.Имя Тогда
		РедакторHTML.switchDCSMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.XML.Имя Тогда
		РежимXML = Истина;
	КонецЕсли; 
	РедакторHTML.compare(Текст2, Истина, ПодсветкаСинтаксиса, РежимXML);
```

**Comment by salexdv** [comment]
> Так это же много лишних вычислений - в 2 раза больше чем можно было бы сделать. Не хорошо как то. Сейчас я сделал без этих двойных переключений. Но после переключения в режим XML переключения перестают выполняться корректно.

Режимы появились не сразу. Сначала был только режим кода, потом появился режим запроса, потом всё остальное. Логика была и остается такая, что в одном окне работает максимум 2 режима, и не происходит переключение между всеми возможными режимами. Режим XML надо дорабатывать, он вообще был реализован для того чтобы просто показывать подсветку в отдельном окне, и при повторном вызове `switchXMLMode` не учитывается режим СКД

**Comment by tormozit** [comment]
Проблема для меня не острая. Текущий вариант переключения, хотя и не красив, но работает приемлемо. Поэтому это замечание на будущее.
