### ISSUE TITLE
Режим сравнения текстов не позволяет перемещать каретку клавиатурой

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#165]
Поле HTML документа после вызова метода [compare()](https://github.com/salexdv/bsl_console/blob/master/docs/compare.md)  у меня находится в режиме сравнения текстов "сторона-к-стороне" (side-by-side). Также я включил для него режим readOnly.
Указателем мыши я могу в нем перемещать каретку (текстовый курсор). Но с клавиатуры (клавишами Вверх/Вниз/Влево/Вправо/СлСтр/ПрСтр) почему то не удается его перемещать. Хочется чтобы можно было перемещать и с клавиатуры.

![изображение](https://user-images.githubusercontent.com/11896251/120331391-64928780-c2f6-11eb-9a16-e11ed1d74aff.png)

**Comment by salexdv** [comment]
Такое действительно наблюдается в поле HTML-документа. У тебя с первого вызова `compare` это случается или после второго? У себя я наблюдал такое поведение только после второго вызова. Сразу открывается редактор в двустороннем или одностороннем режиме, не столь важно, и прокрутка нормально работает. При втором вызове она ломается. Не думаю, что это настолько сильное неудобство, ради которого стоит писать программную обработку нажатия клавиш.

**Comment by tormozit** [comment]
Ну тут проблема то шире. В этом окне клавиатурой не столько перемещаться нужно, сколько делать поиск, включая поиск выделенного слова. Все это у меня не работает.

**Comment by salexdv** [comment]
Я не знаю, почему в 1С редактор начинает себя так вести. Никаких причин для такого поведения я не вижу и с трудом могу себе представить сколько времени нужно потратить, чтобы наделать костылей, которые заставят режим сравнения работать  так, как это должно. Если причину найду, то обязательно её устраню.

**Comment by tormozit** [comment]
В стандартном редакторе еще и закладки работают - F2, ALT+F2.

**Comment by tormozit** [comment]
Еще CTRL+A не работает, а в стандартном сравнителе работает.

**Comment by salexdv** [comment]
> Еще CTRL+A не работает, а в стандартном сравнителе работает.

В текущем тоже работает. Открывай сравнение каждый раз в новом окне и будет нормально

**Comment by tormozit** [comment]
CTRL+A не работает сразу после открытия нового окна формы 1С .
```
Процедура РедакторHTMLДокументСформирован(Элемент)
	
	Инфо = Новый СистемнаяИнформация();
	РедакторHTML = ЭлементыФормы.РедакторHTML.Документ.defaultView;
	РедакторHTML.init(Инфо.ВерсияПриложения);
	РедакторHTML.minimap(Ложь);
	РедакторHTML.setReadOnly(Истина);
	РедакторHTML.updateText(Текст1);
	ЭтаФорма.ТекущийЭлемент = ЭлементыФормы.РедакторHTML;
	РедакторHTML.editor.focus();
	ОбновитьСравнение();
	
КонецПроцедуры

Процедура ОбновитьСравнение()
	
	РедакторHTML = РедакторHTML();
	Если РедакторHTML = Неопределено Тогда
		Возврат;
	КонецЕсли;
	РедакторHTML.queryMode = Ложь;
	РедакторHTML.DCSMode = Ложь;
	РедакторHTML.switchLanguageMode();
	РедакторHTML.compare(Текст2, Истина, ПодсветкаСинтаксиса, РежимXML, Истина);

КонецПроцедуры

```

**Comment by salexdv** [comment]
Толстый клиент, последняя версия из dev. Работает и CTRL+A, и навигация кнопками и поиск.
Платформа 8.3.18.1334
![JFLXKsjAUc](https://user-images.githubusercontent.com/6356534/120430688-0e6a2680-c380-11eb-8c13-d59bae244421.gif)
[Консоль кода HTML_compare.zip](https://github.com/salexdv/bsl_console/files/6582296/HTML_compare.zip)

**Comment by tormozit** [comment]
Нашел разницу. Я еще сразу делаю 
`РедакторHTML.editor.focus();`
чтобы каретка появилась в тексте. Если закомментировать эту строку, то после первого вызова сравнения действительно клавиши работают.

**Comment by tormozit** [comment]
Панель поиска тут опять не закрывается клавишей Esc 
![изображение](https://user-images.githubusercontent.com/11896251/120433460-eaa8df80-c383-11eb-86d1-748f46b0e53e.png)

**Comment by salexdv** [comment]
> Панель поиска тут опять не закрывается клавишей Esc

Исправлю

**Comment by tormozit** [comment]
Esc заработал

**Comment by salexdv** [comment]
Сильно переработал обработку клавиш для управления поиском, чтобы поиск нормально работал и в обычном режиме, и в режиме сравнения. Прошу проверить работоспособность. В режиме сравнения CTRL+F3 и Esc должны управлять виджетом поиска на активной (левой или правой) стороне сравнения

**Comment by tormozit** [comment]
1. Теперь панель поиска стала закрываться с первого раза, а не со второго как было.
2. Панель поиска в режиме сравнения опять сдвигает текст вниз, что ты уже исправлял для обычного режима редактора.
![изображение](https://user-images.githubusercontent.com/11896251/120541137-2da19c00-c3f2-11eb-9f7d-c95dfaf05856.png)
3. Нажатие F3 при открытой/закрытой панели поиска в режиме сравнения обрабатывается платформой, т.е. работает неожиданно
![изображение](https://user-images.githubusercontent.com/11896251/120541454-925cf680-c3f2-11eb-9938-79a12b6b7d61.png)

**Comment by salexdv** [comment]
> 2. Панель поиска в режиме сравнения опять сдвигает текст вниз, что ты уже исправлял для обычного режима редактора.

Проверю.
> 3. Нажатие F3 при открытой/закрытой панели поиска в режиме сравнения обрабатывается платформой, т.е. работает неожиданно

Оно так  и работало. Мы это обсуждали тут #125

**Comment by salexdv** [comment]
> 2. Панель поиска в режиме сравнения опять сдвигает текст вниз, что ты уже исправлял для обычного режима редактора.

Исправил

**Comment by tormozit** [comment]
> Оно так и работало. Мы это обсуждали тут #125

Сделал в этой форме аналогичное контекстное меню. Заработало, но только для левой половины текста. Методы nextMatch() и previousMatch() не учитывают активную половину сторону.

**Comment by salexdv** [comment]
> > Оно так и работало. Мы это обсуждали тут #125
> 
> Сделал в этой форме аналогичное контекстное меню. Заработало, но только для левой стороны (текста). Методы nextMatch() и previousMatch() не учитывают активную сторону.

Учитывают. Если бы этого не было, то `CTRL+F3` нормально не работало. Скорее всего тут проблема в том, что при срабатывании кнопки контекстного меню активная сторона редактора теряет фокус, а именно по наличию фокуса я определяю для какой половины должны работать `nextMatch` и `previousMatch`

**Comment by salexdv** [comment]
> > > Оно так и работало. Мы это обсуждали тут #125
> > 
> > 
> > Сделал в этой форме аналогичное контекстное меню. Заработало, но только для левой стороны (текста). Методы nextMatch() и previousMatch() не учитывают активную сторону.
> 
> Учитывают. Если бы этого не было, то `CTRL+F3` нормально не работало бы. Скорее всего тут проблема в том, что при срабатывании кнопки контекстного меню активная сторона редактора теряет фокус, а именно по наличию фокуса я определяю для какой половины должны работать `nextMatch` и `previousMatch`

**Comment by tormozit** [comment]
Тогда нужно реализовать хранение последней активной стороны даже при потере фокуса.

**Comment by salexdv** [comment]
> Может реализовать хранение последней активной стороны даже при потере фокуса?

Скорее всего других вариантов и нет

**Comment by salexdv** [comment]
Сделал определение по курсору и добавил саму индикацию курсора. Индикация только показывает текущую строку, она не ведет себя так, как индикация в редакторе для сравнения в 1С

**Comment by tormozit** [comment]
Заработало. С двумя индикаторами удобнее чем с одним.
