### ISSUE TITLE
В режиме сравнения текстов команда перехода к следующему различию не отражается в левом тексте

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#166]
Поле HTML документа после вызова метода [compare()](https://github.com/salexdv/bsl_console/blob/master/docs/compare.md) у меня находится в режиме сравнения текстов "сторона-к-стороне" (side-by-side). Также я включил для него режим readOnly.

Кнопкой на форме вызываю метод nextDiff() (следующее различие). При этом если активен (имеет фокус ввода) правый текст, то по изменению положения каретки и легкой подсветке текущей строки рамкой можно замечать это "следующее различие". Но если активен (имеет фокус ввода) левый текст, то каретка в нем при выполнении команды не перемещается и с ней легкая подсветка текущей строки. Таким образом в левом тексте вообще невозможно понять, какое различие сейчас является текущим.

Ожидаю, что при выполнении команды "следующее/предыдущее различие" в левом тексте будет перемещаться каретка.

![изображение](https://user-images.githubusercontent.com/11896251/120332461-70cb1480-c2f7-11eb-9b35-72794670927e.png)

**Comment by salexdv** [comment]
> Ожидаю, что при выполнении команды "следующее/предыдущее различие" в левом тексте будет перемещаться каретка.

Перемещение каретки я сделать могу, но оно, к сожалению, практически не добавит информативности. Можно сделать опциональную индикацию, что-то вроде такого:
![editor](https://user-images.githubusercontent.com/6356534/120371226-2e68fe00-c31e-11eb-8a3b-d1f0e08b1838.png)

**Comment by tormozit** [comment]
Для начала хочется единообразия поведения правого и левого текстов. Более явный индикатор текущей строки тут действительно будет очень полезен.

**Comment by salexdv** [comment]
Добавил дополнительный параметр в функцию `compare`, который позволяет включить индикацию, как на скриншоте выше.
Позиционирование тоже сделал, но толку от него мало.

**Comment by tormozit** [comment]
Заработало. Пока я не увидел причин, почему пользователь может захотеть НЕ видеть новый дополнительный индикатор. Предлагаю его сделать включенным всегда.

**Comment by salexdv** [comment]
> Заработало. Пока я не увидел причин, почему пользователь может захотеть НЕ видеть новый дополнительный индикатор. Предлагаю его сделать включенным всегда.

Для начала нужно посмотреть, как оно будет работать. Если никаких ошибок и нареканий не будет, тогда включу.

**Comment by tormozit** [comment]
Сразу после вызова compare() в обработчике ДокументСформирован у меня идет вызов nextDiff(). При этом всегда происходит позиционирование на первом различии, но новый индикатор в половине случаев остается на первой строке текста, т.е. не перемещается на первое разлчие. Но потом при вызове nextDiff() вроде бы всегда перемещается.

![изображение](https://user-images.githubusercontent.com/11896251/120390275-2fa62500-c336-11eb-96ff-e4ba0e61a1af.png)

**Comment by salexdv** [comment]
> Сразу после вызова compare() в обработчике ДокументСформирован у меня идет вызов nextDiff(). 

Этого делать не нужно. При вызове `compare()` происходит позиционирование на первом различии. Тут проблема в том, что редактор еще не успел отрисовать изменений, а ты уже вызвал `nextDiff()` и редактор еще не знает, где позиционироваться. То, что документ сформирован в 1С еще не значит, что редактор сделал всю работу, которую должен был сделать.

**Comment by tormozit** [comment]
Без вызова nextDiff поведение остается таким же - маркер остается на первой строке.

**Comment by salexdv** [comment]
Должно заработать нормально. В толстом клиенте почему-то медленнее происходит вывод.

**Comment by tormozit** [comment]
Да. Теперь сработало 5 из 5 раз.
