### ISSUE TITLE
Окно списка автодополнения обрезается, если выходит за нижнюю границу поля HTML

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#167]
Если каретка находится близко к нижней границе поля HTML то окно списка автодополнения не корректнирует свою высоту и отображается со стандартной высотой. Поэтому оно выходит за видимую пользователю область и пользователь лишается многих удобств, например возможности всегда видеть активную строку. Ожидал что высота окна списка автодополнения не будет больше видимой области.

Например вижу

![изображение](https://user-images.githubusercontent.com/11896251/120357335-007bbd80-c30e-11eb-9552-13cb757b4e5b.png)

Нажимаю на клавиатуре "стрелка вниз" и перестаю видеть активную строку списка

![изображение](https://user-images.githubusercontent.com/11896251/120357343-02de1780-c30e-11eb-84e8-2257b12fa96f.png)

**Comment by salexdv** [comment]
С этим ничего не поделать.

**Comment by salexdv** [comment]
> Тут только одна строка видна
> А тут вообще не видно списка

Это всё, конечно, печально, но я писал выше, что ничего внятного с этим сделать нельзя. Редактор сам решает, как ему показать список. Если он считает, что его можно уместить в верхней части, то он отрисует его там, если нет, то увы.
Если очень, надо то можешь поиграть с опциями. Там где ты меняешь `customOptions` можешь добавить что-то такое:
```js
suggestFontSize: '10px',
suggestLineHeight: '12px',
```
Результат при этом, как мне кажется, будет так себе.

Еще можешь добавить в **decorations.css** строку
```css
.editor-widget.suggest-widget .tree {
    max-height: 100px;
}
```
