### ISSUE TITLE
Прошу включить символ "&" в множество фильтрующих список автодополнения для языков запросов и выражений компоновки

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#170]
Сейчас символ "&" не применяется фильтром списка автодополнения. Хочется чтобы он применялся (считался частью имени с точки зрения фильтра).
![изображение](https://user-images.githubusercontent.com/11896251/120900118-c1b27400-c63b-11eb-8e18-27ca46f6663c.png)

**Comment by salexdv** [comment]
Простого способа сделать это нет. Остается только разбираться в ядре самого редактора. Делать этого не хочется т.к. результат и затраты времени плохо предсказуемы.
