### ISSUE TITLE
Некорректная вставка имени параметра в режиме языка запросов

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#171]
В режиме языка запросов вставляем параметр из списка автодополнения. В событии EVENT_ON_SELECT_SUGGEST_ROW ловим выбор слова и вставляем его в коде 1С. Но если слово было полное, то после моей вставки редактор вставляет его поверх моего со смещением 

Если в тексте было неполное слово, то проблемы нет

![изображение](https://user-images.githubusercontent.com/11896251/120900321-e529ee80-c63c-11eb-8887-cd8f75869a38.png)

![изображение](https://user-images.githubusercontent.com/11896251/120900227-60d76b80-c63c-11eb-9d86-c3b861f1318a.png)

Если в тексте слово уже полное, то возникает двойной символ "&". Причем если закомментировать код моего обработчика события EVENT_ON_SELECT_SUGGEST_ROW, то проблема остается.

![изображение](https://user-images.githubusercontent.com/11896251/120900228-60d76b80-c63c-11eb-8856-cd8bc61b36ee.png)

![изображение](https://user-images.githubusercontent.com/11896251/120900229-61700200-c63c-11eb-9ea2-6bf8014d665d.png)

Если еще раз повторить выбор и вставку, то получим еще сильнее беду

![изображение](https://user-images.githubusercontent.com/11896251/120900409-4ea9fd00-c63d-11eb-8bc3-3c582779ccef.png)

![изображение](https://user-images.githubusercontent.com/11896251/120900416-5c5f8280-c63d-11eb-8c3d-178ce7c42155.png)

**Comment by salexdv** [comment]
Я уже предлагал вариант тут #159 и предложу еще раз. Может тебе передавать пустое поле `text` в `showCustomSuggestions`, раз уж ты всё равно занимаешься вставкой?

**Comment by salexdv** [comment]
> Я уже предлагал вариант тут #159 и предложу еще раз. Может тебе передавать пустое поле `text` в `showCustomSuggestions`, раз уж ты всё равно занимаешься вставкой на своей стороне?

**Comment by tormozit** [comment]
> 
> 
> Я уже предлагал вариант тут #159 и предложу еще раз. Может тебе передавать пустое поле `text` в `showCustomSuggestions`, раз уж ты всё равно занимаешься вставкой на своей стороне?

Убрал заполнение атрибута text при подготовке данных списка автодополнения. Проблема ушла. 
Однако в твоем редакторе она осталась. Достаточно в список автодополнения добавить элемент с text='&П1'

**Comment by salexdv** [comment]
> > Я уже предлагал вариант тут #159 и предложу еще раз. Может тебе передавать пустое поле `text` в `showCustomSuggestions`, раз уж ты всё равно занимаешься вставкой на своей стороне?
> 
> Убрал заполнение атрибута text при подготовке данных списка автодополнения. Проблема ушла.
> Однако в редакторе она осталась. Достаточно в список автодополнения добавить элемент с text='&П1'

Пока не вижу в этом проблемы. Да, редактор вставляет всё, что передано в поле `text`, не его забота анализировать, что перед вставляемым куском находится похожий. Сам я когда подсказываю параметры запроса не передаю символ & для вставки т.к. он является триггером, по которому выскакивает список подсказок, и при выборе параметра из списка амперсанд уже будет напечатан.

**Comment by tormozit** [comment]
Я так понимаю ты пользователю показываешь полный список всех слов, когда он уже явно указал "только параметры"? Это мне тоже кажется не очень хорошим подходом https://github.com/salexdv/bsl_console/issues/170

**Comment by salexdv** [comment]
> Я так понимаю ты пользователю показываешь полный список всех слов (не только параметров), когда он уже явно указал "только параметры"? Это мне тоже кажется не очень хорошим подходом #170

Сразу после амперсанда я показываю только параметры и во вставляемый текст передаю имя параметра без &

**Comment by salexdv** [comment]
Можно посмотреть, запустив test_query.html и набрав амперсанд

**Comment by tormozit** [comment]
У тебя параметры получаются отделены от остальных слов (таблицы, функции, ключевые слова), доступных в выражениях. Т.е. общий список у тебя невозможно увидеть, чтобы просто пробежаться по нему глазами и например понять, откуда удобнее будет взять нужное значение.

**Comment by salexdv** [comment]
> У тебя параметры получаются отделены от остальных слов (таблицы, функции, ключевые слова), доступных в выражениях. Т.е. общий список у тебя невозможно увидеть, чтобы просто пробежаться по нему глазами и например понять, откуда удобнее будет взять нужное значение.

Всё так
