### ISSUE TITLE
Некорректное раскрытие окна изменений блока на последней строке в тексте

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#172]
По клику на маркере изменений слева от текста в последней его строке окно изменений блока открывается вверху поля текста, а ожидалось его появление внизу.
![изображение](https://user-images.githubusercontent.com/11896251/120914742-c2cdba80-c6a8-11eb-9315-c217338c7e80.png)

**Comment by salexdv** [comment]
Исправлено

**Comment by tormozit** [comment]
Маркер (прямоугольная кнопка) уезжает вниз при раскрытии изменений на последней строке. На остальных строках такого не происходит. В VSCode на последней строке маркер не уезжает.

![изображение](https://user-images.githubusercontent.com/11896251/120963526-6f23a580-c76a-11eb-9c0b-1d83b403269b.png)

![изображение](https://user-images.githubusercontent.com/11896251/120963516-6b901e80-c76a-11eb-9532-9ea46b870322.png)

**Comment by salexdv** [comment]
> Маркер (прямоугольная кнопка) уезжает вниз при раскрытии изменений на последней строке. Поэтому сразу скрыть окно изменений нельзя, т.к. надо перемещать указатель далеко вниз или вправо.
> На остальных строках такого не происходит. В VSCode на последней строке маркер не уезжает.

Так и задумано. В VSCode маркер не уезжает, потому что разрешена прокрутка ниже последней строки. И толку от такого поведения мало т.к. виджет появляется всё равно так, что нужно потом прокручивать к нему, чтобы посмотреть изменения.
![joN2xIBwAV](https://user-images.githubusercontent.com/6356534/120964636-46041480-c76c-11eb-8bfa-84138793ad4b.gif)
