### ISSUE TITLE
Как узнать количество различий найденных в режиме сравнения текстов (compare)?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#173]
Хочу вывести пользователю явный индикатор хотя бы наличия/отсутствия и лучше количества различий в сравниваемых текстах. Есть ли такая функция?

**Comment by salexdv** [comment]
Добавил функцию `getDiffCount()`. Она возвращает количество различий, как при вызове `compare()`, так и при вызове `setOriginalText()`
