### ISSUE TITLE
При наличии в строке свертки и маркера изменений кликом нажимаются оба

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#174]
![изображение](https://user-images.githubusercontent.com/11896251/120935434-5e901280-c70b-11eb-9b51-37be5acf864f.png)

![изображение](https://user-images.githubusercontent.com/11896251/120935436-6059d600-c70b-11eb-9128-0432dafc6984.png)

**Comment by salexdv** [comment]
Такое действительно наблюдается, если нажимать где-то посередине между ними. Можно сделать кликабельную область маркера изменений меньше, но тогда это будет очень неудобно, надо будет выцеливать, чтобы открыть виджет изменений. Сейчас, как мне кажется, есть разумный компромисс между удобством и "ложными" срабатываниями. VSCode, например, ведет себя точно также.

**Comment by tormozit** [comment]
Все же часто промахиваюсь, хотя понимаю природу проблемы. Поэтому все же прошу попробовать решить проблему.
Вот иллюстрация расстояния, на котором при удалении указателя нажатие будет выполняться на обе кнопки

![изображение](https://user-images.githubusercontent.com/11896251/121508906-cb96f700-c9ee-11eb-9677-0d337963a488.png)

Считаю это явным неудобством и плохо продуманным интерфейсным решением Monaco.

Предлагаю 
1. Область, в которой активируется (увеличивается размер) маркер изменения при приближении указателя, уменьшить. Сам размер активированного (увеличенного) маркера оставить какой он сейчас.
2. Область, в которой сохраняется активность (увеличенный размер) маркер изменения при удалении указателя, сократить до области из п.1. Сам размер активированного (увеличенного) маркера оставить какой он сейчас.

**Comment by salexdv** [comment]
Попробуй сейчас

**Comment by tormozit** [comment]
Теперь перекрестная нажимаемая область стала достаточно маленькой и ложных срабатываний стало заметно меньше. В то же время трудностей с наведением на маркер изменения я не испытываю. Теперь размеры этих областей на мой взгляд действительно можно назвать разумным компромиссом.
