### ISSUE TITLE
Редактор перехватывает CTRL+D , но делает при этом ничего

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#175]
В форме 1С есть команда с сочетанием клавиш CTRL+D, но когда активно поле редактора, то это сочетание не срабатывает.
Что редактор должен делать при нажатии CTRL+D? Если ничего, то было бы здорово освободить это сочетание.

**Comment by salexdv** [comment]
В редакторе есть команда, назначенная на такое сочетание, но просто так она не отключается. Попробуй через `disableKeyBinding`

**Comment by tormozit** [comment]
> В редакторе есть команда, назначенная на такое сочетание

Я и хотел в том числе узнать, что за команда?

**Comment by salexdv** [comment]
> Я и хотел в том числе узнать, что за команда?

Трудно сказать. Название команды на русском звучит как "Добавить выделение в следующее найденное совпадение"

**Comment by tormozit** [comment]
> Попробуй через `disableKeyBinding`

Попробовал 
`РедакторHTML.disableKeyBinding(2048+68)`
проблема осталась.

**Comment by tormozit** [comment]
Попробовал
`РедакторHTML.disableKeyBinding(2048+34);`
проблема осталась. События EVENT_KEY_BINDING_* не возникло.

**Comment by salexdv** [comment]
> Попробовал
> `РедакторHTML.disableKeyBinding(2048+34);`
> проблема осталась. События EVENT_KEY_BINDING_* не возникло.

`disableKeyBinding(2082)`

**Comment by tormozit** [comment]
> `disableKeyBinding(2082)`

Так ты тоже самое написал. 2048+34=2082

**Comment by salexdv** [comment]
> > `disableKeyBinding(2082)`
> 
> Так ты тоже самое написал. 2048+34=2082

Перед тем, как написать я проверил. В браузере после вызова `disableKeyBinding(2082)` при нажатии `CTRL+D` генерируется событие `EVENT_KEY_BINDING_2082`. Если этого не происходит в 1С, значит сочетание просто не доходит до редактора

**Comment by tormozit** [comment]
Мне в 1С в режиме языка запросов при нажатии CTRL+D приходит только событие EVENT_QUERY_CONSTRUCT

**Comment by salexdv** [comment]
> Мне в 1С в режиме языка запросов при нажатии CTRL+D приходит только событие EVENT_QUERY_CONSTRUCT. Видимо это для команды открытия конструктора запросов.

Совсем я забыл про это. `CTRL+D` как раз и вызывает `EVENT_QUERY_CONSTRUCT` и в параметрах передает текст запроса

**Comment by tormozit** [comment]
Можно как то отключить эту привязку, чтобы заработал родной механизм вызова нажатия кнопки 1С?
Понятно что есть костыль в виде обработки события EVENT_QUERY_CONSTRUCT , но уж очень некрасиво это.

**Comment by salexdv** [comment]
> С учетом свеже выявленного факта можно как то отключить эту привязку, чтобы заработал родной механизм вызова нажатия кнопки 1С ну или хотя бы событие EVENT_KEY_BINDING_2082? Понятно что есть костыль в виде обработки события EVENT_QUERY_CONSTRUCT , но уж очень некрасиво это.

Это не костыль. У редактора есть родное контекстное меню, один из пунктов в котором привязан к `CTRL+D`. При выборе пункта или нажатии сочетания вызывается событие в 1С.

Насчет отключения надо подумать, как это сделать.

**Comment by salexdv** [comment]
Перед вызовом функции инициализации `init()` можно установить опцию 
```js
setOption('disableContextQueryConstructor', true);
```
тогда сочетание `CTRL+D` перехвачено не будет.

Установка опции `disableContextCommands` отключит создание контекстного меню, а также перехват всех его команд:
* Форматирование `ALT+SHIFT+F`
* Добавить комментарий `CTRL+/`
* Удалить комментарий `CTRL+SHIFT+/`
* Установить закладку `ALT+F2`
* Следующая закладка `F2`
* и возможных других команд

**Comment by tormozit** [comment]
Вызвал 
`setOption('disableContextQueryConstructor', true);`
Теперь нажатие CTRL+D стало выделять текущее слово. Теперь понятна его родная функция Monaco. 
Однако выполнение 
`disableKeyBinding(2082)`
по-прежнему делает в 1С ничего - события EVENT_KEY_BINDING_2082 не возникает и срабатывает штатная функция Monaco (выделение слова)

**Comment by salexdv** [comment]
![xenK7IyicG](https://user-images.githubusercontent.com/6356534/121233068-e9534780-c89a-11eb-91d7-822c5c091ad2.gif)
[Консоль кода HTML_2082.zip](https://github.com/salexdv/bsl_console/files/6618630/HTML_2082.zip)

**Comment by tormozit** [comment]
Заработало.
У меня был единый метод, которым я отключал нужные мне сочетания клавиш редактора. Но оказалось он не вызывался в этом сценарии.  Пришлось разделить его.
