### ISSUE TITLE
Нестабильное отображение пользовательской подсказки по вызову метода

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#176]
Проблема давняя. Но сегодня удалось найти ее достаточно надежное воспроизведение.
Имею текст
```
а = Новый ТаблицаЗначений;
а.Колонки.Добавить("пара", Новый ОписаниеТипов());
```
Открываю его в свеже инициализированном поле редактора. Каретка сразу стоит между скобок. Нажимаю CTRL+SHIFT+SPACE. Срабатывает событие EVENT_BEFORE_SIGNATURE и отрабатывает мой код
`РедакторHTML.setCustomSignatures(ВариантыСинтаксиса);`
[Строка из переменной ВариантыСинтаксиса](https://github.com/salexdv/bsl_console/files/6610920/Clip_250884.txt)
При этом открывается подсказка по вызову метода со стандартным содержанием

![изображение](https://user-images.githubusercontent.com/11896251/121062411-b8591100-c7cd-11eb-804c-a2f2530212a6.png)

Нажимаю CTRL+SHIFT+SPACE еще раз. Все повторяется, но уже открывается подсказка по вызову метода с моим содержанием

![изображение](https://user-images.githubusercontent.com/11896251/121062975-6b296f00-c7ce-11eb-92ed-fc44731fe0f9.png)

Повторные нажатия CTRL+SHIFT+SPACE всегда отображают мое содержимое.
Однако если удалить "("

![изображение](https://user-images.githubusercontent.com/11896251/121063229-b93e7280-c7ce-11eb-8ad8-be192a7061fc.png)

и напечатать снова, то отобразится опять стандартное содержимое подсказки.

![изображение](https://user-images.githubusercontent.com/11896251/121062411-b8591100-c7cd-11eb-804c-a2f2530212a6.png)

**Comment by salexdv** [comment]
В этом поведении всё логично, кроме последнего шага про
> Однако если удалить "("

Такое поведение у себя я воспроизвести не смог.

Вызов `setCustomSignatures()` сам по себе не приводит к появлению подсказки по вызову метода, как это реализовано в `showCustomSuggestions()`. Если после установки своих описаний ты не вызываешь `triggerSigHelp()`, то при первой подсказке редактор и будет себя вести так, как ты описал. При повторном вызове пользовательские описания уже есть и показываются уже они.

**Comment by salexdv** [comment]
Могу предложить добавить 3 опции. Например, `disableNativeSuggestions`, `disableNativeSignatures` и `disableNativeHovers`. При их установке в `true` соответственно не будут показываться стандартные подсказки, но будут генерироваться события.

**Comment by tormozit** [comment]
Теперь сделал обработку события аналогично EVENT_BEFORE_SHOW_SUGGEST:
```
	Если мРазрешеноПодсказкаМетодаHTML = Истина Тогда 
		мРазрешеноПодсказкаМетодаHTML = Ложь;
		Возврат;
	КонецЕсли; 
	РедакторHTML = ПолеТекста.ЭлементФормы.Документ.defaultView;
	РедакторHTML.hideSignatureList();
        РедакторHTML.setCustomSignatures(ирОбщий.ОбъектВСтрокуJSONЛкс(ВариантыСинтаксиса));
        мРазрешеноПодсказкаМетодаHTML = Истина;
        РедакторHTML.triggerSigHelp();
```
Почти все проблемы ушли. Осталось только первое срабатывание. При нем окно не появляется, хотя код отрабатывает.

**Comment by tormozit** [comment]
> Могу предложить добавить 3 опции. Например, `disableNativeSuggestions`, `disableNativeSignatures` и `disableNativeHovers`. При их установке в `true` соответственно не будут показываться стандартные подсказки, но будут генерироваться события.

Да. Кажется тогда работа с этими событиями станет прямее и понятнее.

**Comment by tormozit** [comment]
Новые опции заработали. После их включения я выключил вызовы скрытия штатных списков. Однако в остальном схема работы не изменилась - первый раз обрабатываю событие с формированием содержания подсказки и вызываю явно отображение окна подсказки, а следующий вызов события игнорируют.

**Comment by salexdv** [comment]
> а следующий вызов события игнорируют

Что это значит?

**Comment by tormozit** [comment]
В слове "игнорируют" буква "т" была лишней. Исправил. 
Значит, что событие вызывается 2 раза вместо 1. Первый раз его вызываешь ты, а второй уже я и его обработку в этом случае мне уже надо НЕ делать.
