### ISSUE TITLE
Клавиши курсора Up/Down захватываются окном подсказки по вызову метода, если в ней несколько сигнатур

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#177]
```
УстановитьПривилегированныйРежим(истина);
Параметры = Новый Структура("RUB", Справочники.Валюты.ПустаяСсылка());
```
![изображение](https://user-images.githubusercontent.com/11896251/121070523-7fbe3500-c7d7-11eb-9dac-47704fffff05.png)

Ожидал что только сочетания CTRL+Up/Down будут переключать сигнатуры. А по факту и Up/Down тоже переключают. Хотелось бы убрать этот захват.

**Comment by salexdv** [comment]
Навигация стрелками интуитивнее, чем стрелки + CTRL. Это родное поведение редактора, которое я трогать не буду.

**Comment by tormozit** [comment]
Прошу рассмотреть еще один аргумент. Пусть есть текст
```
УстановитьПривилегированныйРежим(истина);
Параметры = Новый Структура("RUB", Справочники.Валюты.ПустаяСсылка());
ТЗ = НайтиПоСсылкам(ирОбщий.БыстрыйМассивЛкс(Параметры.RUB));
```
Каретка стоит на первой строке. Нажимаю CTRL+SHIFT+SPACE. Открывается подсказка по вызову метода.

![изображение](https://user-images.githubusercontent.com/11896251/121127546-98a80400-c832-11eb-838f-23f5e42c4b95.png)

Нажимаю клавишу "Вниз". Каретка переходит на следующую строку и попадает в вызов конструктора с двумя сигнатурами (вариантами).

![изображение](https://user-images.githubusercontent.com/11896251/121127765-efadd900-c832-11eb-8cda-ac929cd0c8c8.png)

Нажимаю клавишу "Вниз". Каретка неожиданно не двигается, но переключаются сигнатуры.
Считаю что в этом сценарии вероятность что пользователь захочет двигать каретку вниз заметно выше, чем то, что он хочет переключать сигнатуры.

Если все еще считаешь, что текущее поведение правильно, то сделай хотя бы возможность мне устранить это неудобство.

**Comment by salexdv** [comment]
> Если все еще считаешь, что текущее поведение правильно, то сделай хотя бы возможность мне устранить это неудобство.

Это придумали ребята из Microsoft. Количество пользователей у VSCode, наверно, больше будет, чем пользователей у наших консолей и конфигуратора. Они считают такое поведение правильным. Мне оно тоже не кажется ошибочным. Исправить его, не залезая в дебри ядра нельзя.

Вот как это работает в самой последней версии monaco:
![QoC55yRUHm](https://user-images.githubusercontent.com/6356534/121128445-13bdea00-c834-11eb-9e36-607d52c24d88.gif)

**Comment by tormozit** [comment]
Переключение сигнатур в коде 1С заметно менее частотная операция, чем в других языках. Если уж возникла такая потребность, то первым делом пользователь вспомнит как это делалось в конфигураторе и попробует. И у него сразу получится. Не вижу тут потери удобства по отношению к встроенному редактору.

Если отключать привязку этих клавиш в этом случае сложно, то возможно получится отключить автовызов подсказки по вызову метода при смене вызываемого метода при перемещении каретки. Т.е. в моем примере после перехода на следующую строку сделать, чтобы окно подсказки по вызову метода закрылось. Но важно оставить его, если следующая строка также относится к текущему вызову метода.

**Comment by salexdv** [comment]
> Если отключать привязку этих клавиш в этом случае сложно, то возможно получится отключить автовызов подсказки по вызову метода при смене вызываемого метода при перемещении каретки.

Невозможно однозначно определить, вызвана подсказка через смещение каретки на строку вниз или нет. Можно отследить, что последней была нажата Up/Down, но это ничего не дает т.к. есть еще `CTRL+Up/Down`. В теории, конечно, можно построить велосипед из всяких перехватчиков, но не стоит оно того.
