### ISSUE TITLE
Не работает подсказка при указании конструктора новый без скобок в конце

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#180]
С = Новый Структура;
С. <Подсказка не работает>
----
С = Новый Структура();
С. <Работает>
Еще говорил что для 1С более привычна запись без ()
Например когда пишешь Новый ТаблицаЗначений скобки вставляет

**Comment by salexdv** [comment]
Скобки никак не влияют на появление подсказки. Только что проверил
![UXvewojWPI](https://user-images.githubusercontent.com/6356534/121302146-ec355300-c901-11eb-8458-568f15c38a2c.gif)

**Comment by Evg-lylyk** [comment]
![Проблема с подсказкой](https://user-images.githubusercontent.com/48444742/121305066-cca02980-c905-11eb-94f7-74f9a22571a0.gif)
Походу проблема с одной буквой может на анг. языке вставляется

**Comment by salexdv** [comment]
> Походу проблема с одной буквой может на анг. языке вставляется

Может проблема с переменной `С`? Как это можно воспроизвести?

**Comment by Evg-lylyk** [comment]
С буквой М (русской) такая же проблема. В Туллкит набираю код и вызываю подсказку

**Comment by salexdv** [comment]
Ошибка [исправлена](https://github.com/salexdv/bsl_console/commit/b1fea6464d3b097891f25055da8149d1ee81cbc7)
