### ISSUE TITLE
Клик ниже последней строки текста не перемещает каретку

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#181]
Встроенный редактор перемещает каретку при клике ниже последней строки.
Было

![изображение](https://user-images.githubusercontent.com/11896251/121487943-435b2680-c9db-11eb-87ea-e5e0a3324169.png)

Стало после клика

![изображение](https://user-images.githubusercontent.com/11896251/121487955-46561700-c9db-11eb-81bd-c271911b849e.png)

В твоем редакторе каретка не меняет положение по горизонтали. А ожидалось, что изменит на то, которое соответствует положению указателя.
Также должно работать выделение в последней строке при перемещении указателя ниже последней строки с зажатой левой кнопкой мыши.

**Comment by salexdv** [comment]
Из известных мне редакторов ни один не ведет себя так, как ты описал. Опций, включающих такое поведение в monaco я не видел.

**Comment by tormozit** [comment]
В конфигураторе 1С все редакторы текста ведут себя так.

**Comment by tormozit** [comment]
В Visual studio редактор кода ведет себя также. Я даже не смог вспомнить среды разработки, где бы редактор вел себя также как Monaco.
