### ISSUE TITLE
Неожиданный вызов события EVENT_BEFORE_SIGNATURE

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#182]
Отображение встроенной подсказки по вызову метода отключено. В обработчике события EVENT_BEFORE_SIGNATURE устанавливаю свое содержание подсказки и, отключив генерацию события, вызываю показ ее окна, а затем включаю генерацию события.
```
РедакторHTML.setCustomSignatures(ирОбщий.ОбъектВСтрокуJSONЛкс(ВариантыСинтаксиса));
РедакторHTML.enableBeforeShowSuggestEvent(Ложь);
РедакторHTML.triggerSigHelp();
РедакторHTML.enableBeforeShowSuggestEvent(Истина);
```
При этом у меня постоянно вызывается событие EVENT_BEFORE_SIGNATURE как будто решение о его вызове принимается после завершения обработки события. А окно подсказки естественно не отображается. Если закомментировать вызов triggerSigHelp(), то циклический вызов события не происходит.

Аналогичный подход к подсказке автодополнения работает корректно, т.е. самовызова события EVENT_BEFORE_SHOW_SUGGEST не происходит.

**Comment by salexdv** [comment]
Тут явно проблема асинхронности. `triggerSigHelp` еще не отработал, а `enableBeforeShowSuggestEvent` уже выполнился. Пока могу предложить устанавливать `enableBeforeShowSuggestEvent` с некоторой задержкой со стороны редактора.

**Comment by tormozit** [comment]
Ну я то пока вернулся на старую схему - с собственным флагом, который подавляет следующую обработку события. Пока не стоит тогда тратить ресурсы на эту проблему. Может это событие еще долго другим не понадобится.
