### ISSUE TITLE
Некорректное определение вызываемого метода и номера его параметра подсказкой по вызову метода

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#183]
`ТЗ = НайтиПоСсылкам(ирОбщий.БыстрыйМассивЛкс(Параметры.RUB),,,);`
![изображение](https://user-images.githubusercontent.com/11896251/121772475-362a6d00-cb7e-11eb-8156-732e7752581c.png)

В показанной позиции редактор некорректно определяет вызываемый метод - БыстрыйМассивЛкс вместо НайтиПоСсылкам

![изображение](https://user-images.githubusercontent.com/11896251/121772484-4b9f9700-cb7e-11eb-9f49-27a93cfde301.png)

Мой анализатор определяет все корректно. Могу ли я как то передать через параметры правильный метод и номер параметра?

**Comment by tormozit** [comment]
Разобрался. Номер параметра у тебя начинается с 0, что необычно. Номер параметра у тебя определяется правильно. Но окно подсказки не открывается. Буду искать причину дальше.

**Comment by tormozit** [comment]
Обошел проблему через передачу в качестве имени метода того некорректного слова, которое пришло в параметре. Но хорошо бы исправить определение имени метода в редакторе.

**Comment by tormozit** [comment]
Тут и номер параметра редактор определяет неверно
```
а = Новый ТаблицаЗначений;
а.Колонки.Добавить("пара", Новый ОписаниеТипов(
```
![изображение](https://user-images.githubusercontent.com/11896251/121786507-ee7d0300-cbc8-11eb-9a71-098d063d89a1.png)

Мой анализатор верно определил здесь номер параметра.

**Comment by salexdv** [comment]
В связи с другой проблемой дорабатывал определение вызываемого метода и номера его параметра. Можешь проверить, актуальна ли сейчас данная ошибка?

**Comment by salexdv** [comment]
> Проблема актуальна
> 
Точно используется последняя версия исходников?
У меня вот так:

![tTAERXjKkh](https://user-images.githubusercontent.com/6356534/135825731-952d9c85-75d6-4bd6-9f8a-e26ccd210c2e.png)
