### ISSUE TITLE
Прошу показывать в подсказке по вызову метода имя метода и имя сигнатуры

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#184]
Если внутри выражения вызова метода расположен вызов метода, то иногда становится сложно понимать, к какому методу относится подсказка по вызову метода. Поэтому прошу показывать имя метода в этой подсказке и расположить первым

![изображение](https://user-images.githubusercontent.com/11896251/121772952-835c0e00-cb81-11eb-9c1f-1818c5c0e5b8.png)

Также у метода может быть несколько сигнатур и при их переключении хочется видеть название текущей сигнатуры. Например у конструктора объекта "Структура" они называются
- На основании фиксированной структуры
- По ключам и значениям

**Comment by tormozit** [comment]
Пока прикрутил отображение имени метода и сигнатуры через свойство documentation. Неудобство в том, что если описание параметра достаточно большое, то переданные таким образом имени метода и сигнатуры не отображаются, т.к. располагаются в самом низу текста подсказки.

![изображение](https://user-images.githubusercontent.com/11896251/121788531-9947ee00-cbd6-11eb-9f7b-a56230276233.png)

**Comment by salexdv** [comment]
Заголовок подсказки - это обычная строка. Мне неизвестен способ сделать его хотя бы многострочным, чтобы в первой строке выводить имя метода. Могу предложить только такой вариант:
![editor](https://user-images.githubusercontent.com/6356534/122383696-baf8fa80-cf73-11eb-913c-418f59c88fd1.png)

**Comment by tormozit** [comment]
Да. Это уже лучше. Но не всегда. Иногда имя метода будет очень длинным, а нужно оно по большому счету только чтобы в сложных выражениях понимать, внутри вызова какого из нескольких методов находится каретка. Поэтому предлагаю
1. Уменьшить размер шрифта этой подсказки по умолчанию и сделать этот размер настраиваемым.
2. Имя метода показывать с обрезкой до 20 символов, включая "..." либо дать возможность отображаемое имя передавать явно через API.

**Comment by salexdv** [comment]
> 2. Имя метода показывать с обрезкой до 20 символов, включая "..." либо дать возможность отображаемое имя передавать явно через API.

Ты и так передаешь `label` в `setCustomSignatures`. Можешь вместо вот этого
```json
{
"label": "(Включить [Булево])",
}
```
передать это
```json
{
"label": "ОписаниеТипов(Включить [Булево])",
}
```

**Comment by salexdv** [comment]
> 1. Уменьшить размер шрифта этой подсказки по умолчанию и сделать этот размер настраиваемым.

Отдельной опции для размера шрифта в окне подсказки по вызову метода нет. Тут только с **decorations.css** играть

**Comment by tormozit** [comment]
По п. 2 согласен - свойства label достаточно. 
Про изменение размера штрифта не смог пока найти имя элемента стиля. Еще шрифт сейчас используется моноширинный. А для такой подсказки это явно не нужно и потому просто расточительно. Очень хотелось бы многоширинный шрифт.

**Comment by tormozit** [comment]
Все мои попытки влиять на шрифт  (размер, семью и прочее) через стили окончились неудачей. Пробовал например так
```
	//РедакторHTML.setFontSize(13);
	//РедакторHTML.setFontFamily("Lucida Console");
```
```
	.editor-widget parameter-hints-widget {
		font-size: 10px;
	}
```
При этом шрифт в этом окне упорно продолжают использовать стандартные параметры.

**Comment by salexdv** [comment]
Как изменить шрифт через стили описал тут #194

**Comment by tormozit** [comment]
Появилась проблема.

![изображение](https://user-images.githubusercontent.com/11896251/122679210-a9715600-d1f2-11eb-86fc-1b6452288d4c.png)

**Comment by salexdv** [comment]
Проверю

**Comment by salexdv** [comment]
Воспроизведение проблемы

```js
setCustomSignatures(`{
    "ЗначениеВСтрокуВнутр": [
        {
            "label": "ЗначениеВСтрокуВнутр(Значение) [Строка]",
            "documentation": "Получает системное строковое представление переданного объекта",
            "parameters": [
                {
                    "label": "Значение",
                    "documentation": "Значение, представление которого необходимо получить"
                }
            ]
        }
    ]
}`)
```

**Comment by salexdv** [comment]
Проблема наблюдается и в самой последней версии monaco editor.

![ZbcVBtlCTu](https://user-images.githubusercontent.com/6356534/182431040-a1d34b2d-7c8e-4f35-8fa8-889754702995.png)

Причём проблема только при использовании кириллицы. Английские названия функции и параметров такого глюка не вызывают.

**Comment by salexdv** [comment]
Проблема устранена
