### ISSUE TITLE
Вызов метода editor.layout() иногда не перемещает строку состояния

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#187]
Убрал в целях эксперимента automaticLayout:true и вместо этого начал явно вызывать 	
`РедакторHTML.editor.layout();`
При этом строка состояния иногда обновляет свое положение
![изображение](https://user-images.githubusercontent.com/11896251/121781862-676f6100-cbaf-11eb-9a29-040767a006d1.png)

**Comment by salexdv** [comment]
Проверю

**Comment by salexdv** [comment]
Добавил перерисовку. Проверь, пожалуйста.

**Comment by tormozit** [comment]
Заработало
