### ISSUE TITLE
В подсказке по вызову метода отображается 2 переноса строки вместо одного

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#188]
Передаю описание сигнатуры редактору
```
{
"установитьпривилегированныйрежим": [
{
"label": "(Включить [Булево])",
"parameters": [
{
"label": "Включить [Булево]",
"documentation": "Обяз.: Да;  Возвр.: ?\nТип: Булево\nОписание: Определяет, будет ли включен привилегированный режим: \r\n - Истина - включить режим; \r\n - Ложь - выключить режим."
}
],
"documentation": ""
}
]
}
```
Он ее отображает так

![изображение](https://user-images.githubusercontent.com/11896251/121786976-f1c5be00-cbcb-11eb-8417-ebef683a9572.png)

Ожидал 1 перенос строки, а вижу 2.

**Comment by tormozit** [comment]
Обошел проблему удалением символов возврата каретки (\r) из текста. Но тот же текст в полях 1С отображался корректно и без их удаления.

**Comment by salexdv** [comment]
Не наблюдаю указанной проблемы. Скопировал код из первого сообщения и вызвал `setCustomSignatures`

![editor](https://user-images.githubusercontent.com/6356534/122387045-21cbe300-cf77-11eb-90de-201c435d82b1.png)

**Comment by tormozit** [comment]
Вероятно разница между отображением в моем и твоем случае вызвана размером шрифта. Обрати внимание на перенос слова "режим" в твоем снимке на следующую строку. Переписал свой код и как то обошел эту проблему.
