### ISSUE TITLE
Событие EVENT_ON_ACTIVATE_SUGGEST_ROW иногда вызывается для всех строк списка сразу

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#190]
Ищу способ стабильного воспроизведения. Но уже наблюдал это 6 раз. Включаю замер производительности в отладчике. Открываю список автодополнения в консоли кода путем нажатия CTRL+Space. В списке при этом из кода передаю 1000 слов. Список показывается в редакторе и через 3 секунды останавливаю замер в отладчике. Вижу в замере что строка обработки события EVENT_ON_ACTIVATE_SUGGEST_ROW  выполнена 1000 раз. Похоже эти вызовы начинают идти асинхронно уже после открытия списка.
```
ИначеЕсли Событие.event = "EVENT_ON_ACTIVATE_SUGGEST_ROW" Тогда
	ПолеТекстаАлгоритма.РедакторHTML_ПриАктивацииСтрокиАвтодополнения(Событие.params.trigger, Событие.params.focused, Событие.params.row_id);
```

**Comment by tormozit** [comment]
Нашел воспроизведение. После открытия списка автодополнения нужно переключить его в режим отображаения детальной информации по строке и навести указать на какую нибудь строку списка.

![изображение](https://user-images.githubusercontent.com/11896251/121805417-e322e980-cc53-11eb-9f87-f8559f16f203.png)

**Comment by salexdv** [comment]
Посмотрю, что можно с этим сделать

**Comment by tormozit** [comment]
При 
`enableSuggestActivationEvent(Истина, Истина);`
проблема не наблюдается

**Comment by salexdv** [comment]
Проблема не наблюдается

**Comment by tormozit** [comment]
После первого с тех пор моего обновления из твоей ветки пришлось перейти на новый API и описанная здесь проблема снова вернулась. Вот модификация кода для нового API, с которой наблюдается эта проблема
```
				//РедакторHTML.enableSuggestActivationEvent(Истина, Истина);  // Второй параметр включает отображение типов для всех слов списка автодополнения https://github.com/salexdv/bsl_console/issues/119
				РедакторHTML.setOption("generateSuggestActivationEvent", Истина);
				РедакторHTML.setOption("alwaysDisplaySuggestDetails", Истина);
```

**Comment by tormozit** [comment]
Заработало после переделки на 
//РедакторHTML.enableSuggestActivationEvent(Истина, Истина);  // Второй параметр включает отображение типов для всех слов списка автодополнения https://github.com/salexdv/bsl_console/issues/119
				РедакторHTML.setOption("generateSuggestActivationEvent", Истина);
				РедакторHTML.setOption("alwaysDisplaySuggestDetails", **Ложь**);

**Comment by tormozit** [comment]
Попробовал 
`РедакторHTML.setOption("alwaysDisplaySuggestDetails", **Ложь**);`
Тоже не помогло

**Comment by tormozit** [comment]
Но теперь проблема немного изменилась.
При первом в жизни редактора открытии списка она всегда не проявляется. А вот начиная со второго открытия наблюдается всегда независимо от отображения окна детальной информации по текущему элементу списка.

![изображение](https://user-images.githubusercontent.com/11896251/202512033-4d076253-1173-4f75-8d19-66e4b2950f82.png)

![изображение](https://user-images.githubusercontent.com/11896251/202512031-04b7e739-b226-4928-a5ca-2d3cc7584d10.png)

**Comment by tormozit** [comment]
Вернул обратно свой прошлогодний фикс в виде отключения обработчика onSuggestListMouseOver. Теперь не виснет.
