### ISSUE TITLE
Отмена редактирования после setLineContent() пропускает введенный вручную текст

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#191]
Ввожу точно нужное мне слово

![изображение](https://user-images.githubusercontent.com/11896251/121843486-fc2aa980-ccea-11eb-98ea-c2c862063873.png)

Нажимаю машинально ENTER. При этом моим кодом через функцию setLineContent() вставляется активное слово из списка автодополнения

![изображение](https://user-images.githubusercontent.com/11896251/121843554-2714fd80-cceb-11eb-928e-5667aa788bb3.png)

Понимаю, что ошибся. Нажимаю CTRL+Z. При этом введенный мной вручную текст не появляется, 

![изображение](https://user-images.githubusercontent.com/11896251/121843601-3c8a2780-cceb-11eb-88b2-aa09ffefbf9c.png)

Ожидал, что появится строка "\парта"

**Comment by tormozit** [comment]
Похоже тут мой код замешан. В оригинальном редакторе такого не происходит.

**Comment by tormozit** [comment]
Пример для воспроизведения. 
Ввести в первую строку текста какие то символы вручную.
Нажать кнопку "Тест".  Текст первой строки будет заменен.
Нажать CTRL+Z. Вручнуювведенный текст не появится.

[Консоль кода HTML_2082.zip](https://github.com/salexdv/bsl_console/files/6646307/HTML_2082.zip)

**Comment by salexdv** [comment]
Исправил. Должно работать нормально теперь.

**Comment by tormozit** [comment]
Заработало.
