### ISSUE TITLE
В режиме сравнения текстов (compare) не отображается статусная строка

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#192]
В режиме сравнения текстов вызываю
`	РедакторHTML.showStatusBar(Ложь);`
На мгновение статусная строка появляется и исчезает и далее ее не видно.

**Comment by salexdv** [comment]
Добавил строку состояния

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
Вызываю 
`showStatusBar(false)`
Но отрабатывает как будто в качестве значения параметра передал true.
![изображение](https://user-images.githubusercontent.com/11896251/122289036-f1466380-cefa-11eb-85ba-1caca0fbd4e5.png)

**Comment by tormozit** [comment]
Кстати заметил, что в этом режиме у тебя почему то работает как будто automaticLayout = true, хотя я его специально присвоил false. Сейчас получается независимо от значения флага automaticLayout при изменении размеров окна - полосы прокрутки сразу обновляются. Так и задумано?

**Comment by salexdv** [comment]
> Вызываю
> `showStatusBar(false)`
> Но отрабатывает как будто в качестве значения параметра передал true, т.е. все равно перекрывает полосу прокрутки

Доработал

> Кстати заметил, что в этом режиме у тебя почему то работает как будто automaticLayout = true, хотя я его специально присвоил false. Сейчас получается независимо от значения флага automaticLayout при изменении размеров окна - полосы прокрутки сразу обновляются. Так и задумано (это я про обозначенные тобой возможные проблемы производительности) ?

С этим сейчас тоже должно быть всё хорошо.

**Comment by tormozit** [comment]
Теперь статусная строка располагается корректно. 
Однако при изменении размеров поля его содержимое все еще автоматически перерисовывается при automaticLayout = false.

**Comment by salexdv** [comment]
> Теперь статусная строка располагается корректно.
> Однако при изменении размеров поля его содержимое все еще автоматически перерисовывается при automaticLayout = false.

Для режима сравнения automaticLayout всегда включен. Раньше он оставался включенным и при переключении обратно в режим редактирования кода, этот момент я исправил.

**Comment by tormozit** [comment]
Значит не так страшен это автообновление как это описывают.

**Comment by salexdv** [comment]
> Значит не так страшен это режим автообновления как это описывают.

В режиме сравнения я оставил этот флаг по двум причинам. Во-первых, изначально задумывалось, что режим сравнения будет в отдельном окне, размер которого можно будет изменять. Во-вторых, и что самое главное, в режиме сравнения не происходит никакого редактирования, а значит и нагрузка на редактор не такая большая.
