### ISSUE TITLE
Не удается подавить отображения подсказки удержания указателя в режиме сравнения текстов через опцию disableNativeHovers

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#193]
В режиме сравнения текстов вызываю
```
РедакторHTML.showStatusBar(Ложь);
РедакторHTML.setOption("disableNativeHovers", Истина); 
```
Но подсказка все равно появляется

![изображение](https://user-images.githubusercontent.com/11896251/122163385-c8cc5400-ce7d-11eb-83d4-0be0625b9e4c.png)

**Comment by salexdv** [comment]
Эти опции не задумывались для режима сравнения. Доработаю.

**Comment by salexdv** [comment]
> Эти опции не задумывались для режима сравнения. Доработаю.

Дело оказалось не в этом. При вызове функции compare фактически заново создается объект редактора и все свойства, ранее установленные через `setOption` уничтожаются
