### ISSUE TITLE
Как уменьшить расстояние между строками текста в редакторе?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#195]
Сейчас расстояние между строками слишком большое. Хотелось бы его сократить.
Встроенный редактор

![изображение](https://user-images.githubusercontent.com/11896251/122438829-cbc16480-cfa3-11eb-8392-ebff9637d848.png)

Редактор Monaco 

![изображение](https://user-images.githubusercontent.com/11896251/122439371-468a7f80-cfa4-11eb-92f4-bfc79ab5483a.png)

**Comment by salexdv** [comment]
customOptions: true -> lineHeight: 16

**Comment by tormozit** [comment]
заработало
