### ISSUE TITLE
В режиме сравнения текстов (compare) не работает включение отображения пробелов и табуляций

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#197]
Вызываю
`РедакторHTML.renderWhitespace(Истина);`
затем вызываю 
`РедакторHTML.compare(текст)`
Получаю
![изображение](https://user-images.githubusercontent.com/11896251/122620457-baf41a00-d09b-11eb-95c2-5ad83266a11e.png)

**Comment by salexdv** [comment]
`renderWhitespace` нужно вызывать после `compare`. При включении режима сравнения фактически создается новый редактор, который ничего не знает о тех опциях, которые были установлены ранее.

**Comment by tormozit** [comment]
Заработало.
Еще бы высоту строки изменить.

**Comment by salexdv** [comment]
> Заработало.
> Еще бы высоту строки изменить. Пробовал через
> `РедакторHTML.setFontSize(13);`
> не работает (до и после compare).

Вызывать нужно тоже после `compare`. Только что проверил в браузере, всё отрабатывает. В 1С проверить возможности пока нет.

**Comment by tormozit** [comment]
Я некорректно применил вызов для решения своей задачи
`setFontSize(13)`
Он устанавливает размер шрифта. 
А мне нужно высоту строки изменить. Как это сделать? Какой стиль установить?

**Comment by salexdv** [comment]
Добавлю отдельный метод для этого

**Comment by tormozit** [comment]
Заработало и в режиме сравнения
