### ISSUE TITLE
Подсказка по вызову метода заслонила область ввода редактора

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#199]
В поле HTML документа малой высоты вызываю подсказку по вызову метода

![изображение](https://user-images.githubusercontent.com/11896251/122638788-d8a69b00-d0fe-11eb-99ee-6aac428fe44e.png)

И перестаю видеть область ввода

![изображение](https://user-images.githubusercontent.com/11896251/122638791-db08f500-d0fe-11eb-8f75-948d91d215fa.png)

Использован стиль
```
	|.editor-widget.parameter-hints-widget .code {
	|	font-size: 13px !important;
	|	line-height: 15px;
	|}
	|.editor-widget.parameter-hints-widget .docs {
	|	font-size: 13px !important;
	|	line-height: 15px;
	|}
	РедакторHTML.showStatusBar(Ложь);
	РедакторHTML.renderWhitespace(Истина);
	РедакторHTML.setFontSize(13);
	РедакторHTML.setOption("autoResizeEditorLayout", Истина);
```

**Comment by salexdv** [comment]
Я на это влиять не могу. Редактор сам рассчитывает, как ему показывать подсказку.
