### ISSUE TITLE
Как добавить штатные сниппеты редактора в список автодополнения?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#200]
Редактор поставляется с набором сниппетов (snippets.js) . 
Как при выводе собственного списка автодополнения добавить их в список?
Как в событии EVENT_ON_SELECT_SUGGEST_ROW выполнить выбранный пользователем сниппет?

**Comment by salexdv** [comment]
> Как при выводе собственного списка автодополнения добавить их в список?

Сниппеты можно обновить через `updateSnippets`. На вход нужно JSON с объектом `snippets`, например:
```js
updateSnippets('{"snippets": {...}}', true)
```
где второй параметр отвечает за полную замену штатных.

> Как в событии EVENT_ON_SELECT_SUGGEST_ROW выполнить выбранный пользователем сниппет?

Выполнить никак. Он сам выполнится при выборе.
Про синтаксис можно почитать [тут](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

**Comment by tormozit** [comment]
В моем списке автодополнения штатные сниппеты не отображаются. Вызываю метод showCustomSuggestions() и вижу только свои слова

![изображение](https://user-images.githubusercontent.com/11896251/122811814-98e7db00-d2d9-11eb-95fc-0da6cce3f8bd.png)

Я пока не уверен, нужны ли они мне там. Поэтому хотелось получить способ отображать/скрывать их при отображении этого списка.

**Comment by salexdv** [comment]
> В моем списке автодополнения штатные сниппеты не отображаются. Вызываю метод showCustomSuggestions() и вижу только свои слова

Для `showCustomSuggestions` это действительно так, показывается только то, что было передано в метод. Доработаю структуру передаваемых данных, чтобы можно было и сниппеты туда же загрузить.

**Comment by salexdv** [comment]
Сниппет можно передать в `showCustomSuggestions` так:
```js
showCustomSuggestions(`{
    "Для каждого": {
        "name": "ДляКаждого",
        "text": "Для каждого $\{1:Переменная\} Из $\{2:Коллекция\} Цикл\\n\\t$0\\nКонецЦикла;",
         "kind": "Snippet",
         "detail": "",
         "documentation": ""
    }
}`);
```
Или всё таки нужна возможность показывать/скрывать штатные сниппеты при вызове `showCustomSuggestions`?

**Comment by tormozit** [comment]
Да. Хотелось бы и встроенные подключать.

**Comment by salexdv** [comment]
> Да. Хотелось бы и встроенные подключать.

Добавил опцию

```js
setOption('showSnippetsOnCustomSuggestions', true);
```

**Comment by tormozit** [comment]
Сниппеты в список добавляются. Но нет возможности при выборе (например нажатием ENTER) их в списке применить их. Ведь я использую свою обработку события EVENT_ON_SELECT_SUGGEST_ROW. Поэтому мне еще нужен метод, чтобы выполнить выбранный сниппет.

**Comment by salexdv** [comment]
> Поэтому мне еще нужен метод, чтобы выполнить выбранный сниппет.

Добавил. Проверь, пожалуйста.

**Comment by tormozit** [comment]
Набрал текст "если" и выбрать из списка шаблон "Если". Сработал мой обработчик события и я в нем взывал insertSnippet("Если"). При этом вставился текст "Если". В общем пока не заработала вставка.
![изображение](https://user-images.githubusercontent.com/11896251/132254377-b8595c3e-d2ab-403e-9fae-0913adcab755.png)

**Comment by salexdv** [comment]
> Набрал текст "если" и выбрал из списка шаблон "Если". Сработал мой обработчик события и я в нем вызвал insertSnippet("Если"). При этом вставился текст "Если". В общем пока не заработала вставка.

А какого поведения ты ожидал? В функцию надо передавать полный текст сниппета.

**Comment by salexdv** [comment]
```js
insertSnippent('Если ${1:Условие} Тогда\n\t$0\nКонецЕсли;')
```

**Comment by tormozit** [comment]
Я ожидал, что по имени сниппета (тому которое в списке видимо), смогу обозначить сниппет для выполнения. Как получить этот полный текст?

**Comment by salexdv** [comment]
А вот это интересный вопрос, ответа на который у меня пока нет. Постараюсь что-нибудь придумать и передать в событие `EVENT_ON_SELECT_SUGGEST_ROW`

**Comment by salexdv** [comment]
> Как получить этот полный текст? Я ожидал, что по имени сниппета (тому которое в списке видимо), смогу обозначить сниппет для выполнения.

Добавил в параметры события `EVENT_ON_SELECT_SUGGEST_ROW` поле `insert_text`

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
В режиме языка запросов почему то показываются сниппеты от встроенного языка
![изображение](https://user-images.githubusercontent.com/11896251/132452667-e33f5b84-ea83-4c07-b910-7b47610d1d86.png)

**Comment by salexdv** [comment]
Попробуй сейчас

**Comment by tormozit** [comment]
В режиме языка запросов чужие сниппеты пропали, но свои не появились (например для конструкции ВЫБОР).

**Comment by salexdv** [comment]
> В режиме языка запросов чужие сниппеты пропали, но свои не появились (например для конструкции ВЫБОР).

Вообще нет сниппетов в списке? У меня вот так показывается:

![suggest](https://user-images.githubusercontent.com/6356534/132458676-b4b1dff6-92b9-49c5-9c49-bda130820619.png)

**Comment by tormozit** [comment]
Да. Вообще сниппетов нет в режиме языка запросов.

**Comment by salexdv** [comment]
Можешь подсказать, как это воспроизвести или может ссылку на исходники сбросишь?

**Comment by tormozit** [comment]
Из-за предыдущей ошибки я отключил подключение сниппетов в режиме языка запросов и забыл включить обратно.

**Comment by tormozit** [comment]
В списке свойств объекта почему то отображаются сниппеты. Кажется нелогичным.

![изображение](https://user-images.githubusercontent.com/11896251/133454084-683a76cb-68f9-426d-bc96-ca2a3dda0583.png)
