### ISSUE TITLE
Зачем в методе updateText параметр range?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#203]
Метод updateText всегда очищает текст перед вставкой. Зачем тогда ему параметр range? Кажется его надо удалить.
```
  updateText = function(txt, range, usePadding) {

    readOnly = readOnlyMode;
    modEvent = generateModificationEvent;
    
    if (readOnly)
      setReadOnly(false);

    if (modEvent)    
      enableModificationEvent(false);

    eraseTextBeforeUpdate();
    setText(txt, range, usePadding);

    if (modEvent)    
      enableModificationEvent(true);

    if (readOnly)
      setReadOnly(true);

  }
```

**Comment by salexdv** [comment]
Этот параметр используется, например при обновлении текста запроса в режиме редактирования кода. Вместе с событием `EVENT_QUERY_CONSTRUCT` передается, как текст запроса, так и граница области, в которой этот текст находится.

**Comment by tormozit** [comment]
Но текст ведь всегда сначала очищается и только потом вставляется. В чем смысл указывать диапазон тогда?
