### ISSUE TITLE
Метод объекта не обнаружен (hideScrollX)

### ISSUE THREAD

**Issue by aleksandr-ermakov** [salexdv/bsl_console#204]
При открытии обработки
```
Метод объекта не обнаружен (hideScrollX)
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(790)}:	View().hideScrollX();
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(812)}:		ИнициализацияРедактора();
```
Платформа 8.3.17.1851
Обработка 0.2.6

**Comment by salexdv** [comment]
Не удалось воспроизвести данную ошибку. Попробуйте очистить каталог `%Temp%\bsl_console\` и запустить обработку заново. Видимо, что-то с исходниками случилось.

**Comment by aleksandr-ermakov** [comment]
Не удалось повторно воспроизвести через время, даже без очистки `%Temp%\bsl_console\` 
До этого воспроизводилось при каждом открытии на разных базах.
Возможно, это из-за перехода с версии на версию.
