### ISSUE TITLE
Клик по URL с зажатым CTRL не открывает гиперссылку и не вызывает события в API

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#206]
![изображение](https://user-images.githubusercontent.com/11896251/124350408-4a9dda80-dbfd-11eb-888e-8009c96099dc.png)

Хотелось бы открытие гиперссылки происходило или хотя бы нужно генерировать событие API EVENT_ON_LINK_CLICK. 

Сейчас событие API генерируется только при нажатии на гиперссылке "перейти по ссылке" во всплывающем окне. Стандартная обработка клика на гиперссылке во всплывающем окне и по гиперссылке с зажатым CTRL пытается открыть видимо адрес "about"

![изображение](https://user-images.githubusercontent.com/11896251/124353616-3dd6b200-dc10-11eb-81c2-a06df012a8af.png)

**Comment by salexdv** [comment]
Доработал. Сейчас событие должно генерироваться.

**Comment by tormozit** [comment]
Событие API EVENT_ON_LINK_CLICK заработало
