### ISSUE TITLE
Неоднозначное поле "ПланСчетов.Предопределенный"

### ISSUE THREAD

**Issue by aleksandr-ermakov** [salexdv/bsl_console#207]
Дано 1С:ERP Управление предприятием 2 (2.5.6.195)
 И обработка 0.2.6
Когда Открываем обработку 
Тогда Возникает ошибка 
```
{ВнешняяОбработка.КонсольКода.МодульОбъекта(175)}: Ошибка при вызове метода контекста (Выполнить)
					Выборка = Запрос.Выполнить().Выбрать();
по причине:
{(7, 2)}: Неоднозначное поле "ПланСчетов.Предопределенный"
<<?>>ПланСчетов.Предопределенный
```

Дело в том что у плана счетов `Международный` есть реквизит `ПланСчетов`.
Измените псевдоним таблице в запросе в функции `ОписатьКоллекциюОбъектовМетаданых()`.

**Comment by salexdv** [comment]
Ошибка исправлена. Обработка в релизе 0.2.6 обновлена. Спасибо!
