### ISSUE TITLE
После выбора некоторых слов из списка автодополнения не срабатывает ENTER для перевода строки

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#209]
Это происходит при включенном флаге generateSelectSuggestEvent
https://github.com/tormozit/RDT1C/issues/7

**Comment by tormozit** [comment]
Похоже это я как то поломал в https://github.com/salexdv/bsl_console/pull/205 . Разбираюсь

**Comment by tormozit** [comment]
Наверное все таки я не виноват, хотя моя правка тут играет роль.
Подозреваю что проблема возникает тут. Почему то окно списка автодополнения находится, хотя закрыто. Поэтому срабатывает мое подавление обработки ENTER.
```
  else if (e.keyCode == 3 && generateSelectSuggestEvent) {
      // Enter
      let element = document.querySelector('.monaco-list-row.focused');
      if (element) {
        e.preventDefault();
        e.stopPropagation();
        setTimeout(() => {
          generateEventWithSuggestData('EVENT_ON_SELECT_SUGGEST_ROW', 'selection', element);
        }, 10);
        // stopEventIfSuggestListIsClosed(e);
      }
    }
```

**Comment by salexdv** [comment]
Разберусь

**Comment by tormozit** [comment]
Еще один аргумент за мою версию. При каждом таком нажатии приходят события
Отладка. EVENT_ON_SELECT_SUGGEST_ROW
Отладка. EVENT_ON_ACTIVATE_SUGGEST_ROW
Отладка. EVENT_ON_ACTIVATE_SUGGEST_ROW

**Comment by tormozit** [comment]
Похоже как будто при нажатии ENTER очень быстро открывается список автодополнения из одной строки и сразу же происходит выбор элемента тем же единственным нажатием клавиши ENTER от пользователя.

**Comment by tormozit** [comment]
CTRL+Space тоже кстати перестает работать в этой ситуации - событие EVENT_BEFORE_SHOW_SUGGEST не приходит, а вместо него приход EVENT_ON_DETAIL_SUGGEST_ROW.

**Comment by salexdv** [comment]
После получения события EVENT_ON_SELECT_SUGGEST_ROW ты вставляешь у себя текст и вызываешь hideSuggestionsList?

**Comment by tormozit** [comment]
Да

**Comment by tormozit** [comment]
Временно отключил свою вставку текста и оставил только вызов hideSuggestionsList(). Проблема осталась.

**Comment by salexdv** [comment]
Попробуй сейчас, должно помочь. Мне этот кусок кода очень не нравится. Правильно всё-таки было бы передавать пустой вставляемый текст в showCustomSuggestions, тогда и генерацию события не надо было бы откладывать, и прерывать родное событие тоже не пришлось бы.

**Comment by tormozit** [comment]
Теперь окно автодополнения не закрывается при вызове hideSuggestionsList().

**Comment by salexdv** [comment]
Можешь скинуть конфигурацию для проверки?

**Comment by tormozit** [comment]
http://devtool1c.ucoz.ru/load/0-0-0-1-20 - CF , там твоего исправления нет. Макет редактора лежит в Обработка.ирПлатформа.Макет.MonacoEditor - там zip такой структуры 
![изображение](https://user-images.githubusercontent.com/11896251/127209216-3d13791f-e1a7-4ecf-bcfa-d5a836a6a2d2.png)

**Comment by salexdv** [comment]
Пока не очень понятно, из-за чего возникает такое поведение. Очень странно, что после закрытия возникает EVENT_ON_ACTIVATE_SUGGEST_ROW. Причина этого возникновения где-то тут
![SV0YM1aUD3](https://user-images.githubusercontent.com/6356534/127215980-aba24abd-95d8-4f20-92f8-4fefd25a04ac.png)
Если данный блок закомментировать, то повторной активации списка не происходит. Буду смотреть дальше

**Comment by tormozit** [comment]
Там из значимого кажется вызывается только
РедакторHTML.setLineContent(НомерСтроки, Текст); 
РедакторHTML.setSelection(НачальнаяСтрокаИлиПозиция, НачальнаяКолонкаИлиКонечнаяПозиция, КонечнаяСтрока, КонечнаяКолонка);

**Comment by tormozit** [comment]
В общем снова мы возвращаемся к этой сложной беде с моей собственной вставкой вместо штатной.
Я с самого начала (с мая 2021) использовал ее через
РедакторHTML.setLineContent()
Если эту вставку отключить, то проблемы не возникает. Возможно после этой вставки какой то триггер срабатывает и вызывает в непредусмотренном для него состоянии и неполностью активирует окно автодополнения?

**Comment by tormozit** [comment]
Если нажать клавишу Esc после выбора слова, то проблема исчезает.

**Comment by tormozit** [comment]
Можно как то отправить нажатие Esc программно в редактор его же средствами?

**Comment by tormozit** [comment]
Пока отправил нажатие ESC через WSH.SendKeys . Работает, но не красиво конечно.

**Comment by tormozit** [comment]
Нашел правильный способ закрытия списка автодополнения тут https://stackoverflow.com/questions/48786195/is-it-possible-to-close-the-auto-complete-suggestwidget-programmatically

**Comment by tormozit** [comment]
В https://github.com/salexdv/bsl_console/pull/211 сработало закрытие виджета через
`editor.trigger("editor", "hideSuggestWidget")`
Наверное и для других окон есть подобные команды, но быстро я не смог их найти.

**Comment by salexdv** [comment]
Нормальный способ закрытия я тоже нашел, но твой будет более правильным. Жаль, что нигде это не описано. В списке стандартных триггеров такого нет.
