### ISSUE TITLE
В языке запросов некорректно расставляюся свертки при отсутствии ключевого слова ИЗ

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#210]
http://devtool1c.ucoz.ru/forum/2-1922-1
В следующем запросе некорректно сворачивает текст при отсутствии слова ИЗ в запросе (сворачивает вместе с началом следующего слова ВЫБРАТЬ):
```
ВЫБРАТЬ
    1 КАК Номер,
    10 КАК Оборот
ПОМЕСТИТЬ Числа
ОБЪЕДИНИТЬ
ВЫБРАТЬ
    2,
    20
;
ВЫБРАТЬ
    Т1.Номер,
    500 - СУММА(Т2.Оборот)
    
ИЗ Числа КАК Т1
ВНУТРЕННЕЕ СОЕДИНЕНИЕ Числа КАК Т2
ПО Т1.Номер <= Т2.Номер
СГРУППИРОВАТЬ ПО
    Т1.Номер
```
![изображение](https://user-images.githubusercontent.com/11896251/127210072-6dfa640d-9353-4b10-9dfe-e331bbae5adc.png)

**Comment by tormozit** [comment]
Возможно будет полезна обкатанная функция разбивки текста пакета на отдельные запросы из подсистемы "Инструменты разработчика" Обработка.ирПлатформа.МодульОбъекта.РазбитьГрубоТекстПакетногоЗапросаНаТекстыЗапросов()

**Comment by salexdv** [comment]
Исправлено
