### ISSUE TITLE
Окно автодополнения открывается на мгновение в старом положении и сразу перескакивает в новое

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#212]
С самого начала использования редактора замечал некритичный, но неприятный эффект.
Берем демо обработку "Консоль кода". Пишем
`Док = Документы.`

![изображение](https://user-images.githubusercontent.com/11896251/127435270-5db7e652-9165-4045-95b8-1a17c71c9c7b.png)

После точки появляется окно автодополнения. Выбираем в нем любое слово и нажимает клавишу ENTER. Слово вставляется и окно закрывается.

![изображение](https://user-images.githubusercontent.com/11896251/127435271-cc7e142a-e31f-462a-a82d-fda58004d635.png)

Теперь нажимаем клавишу "." (точка). И на мгновение окно автодополнения появляется в последней позиции (около предыщуей точки) и даже кажется со старым содержимым и сразу же перескакивает в правильное положение и отображает новое содержимое. Пытался записать видео, но этот кадр не сложно поймать в 30 кадров/сек. Поэтому кадр скорее всего один и длится менее чем 1/30=30мсек.

![изображение](https://user-images.githubusercontent.com/11896251/127435272-a7c5ba37-7ff5-4ef4-b5db-d262513f560b.png)

Кажется, что это должно как то просто исправляться.

**Comment by salexdv** [comment]
На 60 кадрах/сек я ничего не заметил. Могу предположить, что это сделано для красоты, чтобы окно плавно смещалось из одной позиции в другую, но внутри 1С это не работает, или работает криво, или просто тормозит. В любом случае это очень низкий уровень редактора и погружаться туда нет желания.

**Comment by tormozit** [comment]
Кажется беда эта есть только в твоей версии редактора. В VSCode например такого не наблюдается. Какой либо анимации перемещения там я не увидел.

**Comment by salexdv** [comment]
Ты просто не пробовал запускать VSCode в 1С )). Я посмотрю, конечно, но не думаю, что получится с этим что-то сделать.

**Comment by salexdv** [comment]
В 1С я такое поймал, но вот в браузере тот же самый код отрабатывает нормально.
![rXqFcjpxgQ](https://user-images.githubusercontent.com/6356534/127447878-71a399f5-2142-42d4-a912-21e6cd82670a.gif)

**Comment by tormozit** [comment]
Да. В браузере я тоже не замечаю такого.

**Comment by salexdv** [comment]
Не нашел способа повлиять на такое поведение в 1С.
