### ISSUE TITLE
Не работает подсказка при вложенном использовании переменных

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#216]
например, Если в методе запроса УстановитьПараметр попытаться обратиться к списку справочников подсказка не вызывается.
![image](https://user-images.githubusercontent.com/36307272/128695427-083afc7f-aaa1-45ae-a761-77a10796f617.png)

В то же время если просто вызвать ту же подсказку без вложенного метода все работает
![image](https://user-images.githubusercontent.com/36307272/128695668-6add752d-7975-4002-9efc-2d68f2aeb396.png)

**Comment by salexdv** [comment]
Проблема устранена.
