### ISSUE TITLE
В редактировании текста пакета запросов выделять границы отдельных запросов

### ISSUE THREAD

**Issue by max-zhilin** [salexdv/bsl_console#218]
Было бы удобно видеть разделители между запросами в пакете в виде заполненного фона строки с ";".
Например, сейчас так обозначаются свернутые строки, бледно-желтым фоном.
![изображение](https://user-images.githubusercontent.com/10000429/130234013-955afe48-ebf5-4a2b-9fe9-cb04d0b17d0b.png)
Предлагаю запросы разделять бледно-зеленым фоном строки с ";".

Дополнительно в полосе вертикальной прокрутки разделители запросов показывать такой же зеленой риской (как позицию курсора, только бледно-зеленую).
![изображение](https://user-images.githubusercontent.com/10000429/130234721-b046bc38-b971-4da5-84c5-2aebd74ea552.png)

**Comment by salexdv** [comment]
Выделение разделителей запросов добавил. Включается через установку [опции](https://github.com/salexdv/bsl_console/blob/develop/docs/set_option.md)
```js
setOption('renderQueryDelimiters', true)
```

**Comment by Evg-lylyk** [comment]
> Выделение разделителей запросов добавил. Включается через установку [опции](https://github.com/salexdv/bsl_console/blob/develop/docs/set_option.md)
> 
> ```js
> setOption('renderQueryDelimiters', true)
> ```

Можешь скинуть как это выглядит

**Comment by salexdv** [comment]
> Можешь скинуть как это выглядит

Вот так

![delimiter](https://user-images.githubusercontent.com/6356534/130458796-73530583-722e-4579-993b-6fd202763a52.png)

Границы запроса видно и в основном окне редактора и на полосе прокрутки.

**Comment by tormozit** [comment]
Думаю что в полосе прокрутки они (синие отметки) слишком много места и внимания съедают. Я обычно полосу прокрутки использую для визуальной оценки числа вхождений выделенной строки. 
А вот выделение строки с ";" на первый взгляд выглядит хорошо. На мой вкус я бы оставил только его.

**Comment by max-zhilin** [comment]
Поддержу, на полосе прокрутки лучше сделать тонкой линией и более светлой.

**Comment by salexdv** [comment]
> Думаю что в полосе прокрутки они (синие отметки) слишком много места и внимания съедают. Я обычно пассивно полосу прокрутки использую для визуальной оценки числа и расположения вхождений выделенной строки.
> А вот выделение строки с ";" на первый взгляд выглядит хорошо. На мой вкус я бы оставил только его.



> Поддержу, на полосе прокрутки лучше сделать тонкой линией и более светлой.

К сожалению, нет возможности управлять высотой линий на полосе прокрутки. Постараюсь сделать выделение там менее заметным.

**Comment by salexdv** [comment]
Доработал. Получилось вот так:

![delimiter](https://user-images.githubusercontent.com/6356534/130550668-fa25a928-32f4-41d3-90f2-a8ec41f13d8a.png)

**Comment by tormozit** [comment]
В полосой прокрутки теперь ОК.
Попробовал эту опцию и в обычной форме цвет разделителя в тексте оказался слишком близким с цветом фона формы.
![изображение](https://user-images.githubusercontent.com/11896251/130560439-7f2ef05c-35ef-4dcd-aa32-56dd04335499.png)

**Comment by salexdv** [comment]
> Попробовал эту опцию. В обычной форме цвет разделителя в тексте оказался слишком близким к цвету фона формы. Предлагаю посмотреть в сторону другого оттенка.

Можешь предложить свой вариант цвета?

**Comment by tormozit** [comment]
Предлагаю менее броский зеленый
![изображение](https://user-images.githubusercontent.com/11896251/130562463-b669eb0b-a952-40c2-9c9d-8f5a23b5d183.png)

**Comment by salexdv** [comment]
> Предлагаю менее броский зеленый

Да, неплохой вариант :+1:

**Comment by tormozit** [comment]
Проверил на разных запросах. Теперь на мой вкус ОК.

**Comment by tormozit** [comment]
Выделение текст не отображается в такой строке
![изображение](https://user-images.githubusercontent.com/11896251/135091567-27ddb615-eaf5-436f-a08f-632a2b15af47.png)
