### ISSUE TITLE
Предлагаю в режиме сравнения текстов при активации строки в одной стороне активировать ее и в другой стороне

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#219]
Чтобы проще было сопоставлять строки, хочется подсветки общей горизонтали в обоих сторонах сравнения. Поэтому предлагаю при активации строки в одной стороне - активировать ту же по номеру строку в другой стороне, чтобы была видна рамка активной строки.

![изображение](https://user-images.githubusercontent.com/11896251/130343321-9b22893c-87b8-49fd-bd05-cf493e568852.png)

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
Подсветка одинакового родного номера строки в каждой стороне мало полезна. Более полезной будет подсветка строк обеих сторон на одной горизонтали, т.е. чтобы это была одна сквозная (с дыркой в середине) горизонтальная рамка на обе стороны.
Сейчас после первого же добавления/удаления строки она перестает быть обещей горизонталью
![изображение](https://user-images.githubusercontent.com/11896251/132937304-229eab51-a5e6-49a8-afb2-8299ef19eab1.png)

**Comment by salexdv** [comment]
> Более полезной будет подсветка строк обеих сторон на одной горизонтали, т.е. чтобы это была одна сквозная (с дыркой в середине) горизонтальная рамка на обе стороны.

Это как?

**Comment by tormozit** [comment]
![изображение](https://user-images.githubusercontent.com/11896251/132938612-066c1c70-8a1e-4058-8225-b4aac68198fb.png)

**Comment by tormozit** [comment]
Снова пришел к выводу, что удобнее подсвечивать просто одну горизонталь. Т.е. последнее пожелание актуально.
https://github.com/salexdv/bsl_console/issues/324
