### ISSUE TITLE
В тексте запроса равному "//" нажатие CTRL+SHIFT+Num"/" не убирает косые черты

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#226]
https://github.com/tormozit/RDT1C/issues/36
Установить текст запроса равным "//" и нажать CTRL+SHIFT+Num"/". Произойдет ничего, а ожидалось удаление "//".

**Comment by salexdv** [comment]
В браузере не воспроизводится, в управляемых формах не воспроизводится, в обычных формах (голая форма с HTML-полем) всё работает, как и ожидается. В инструментах разработчика ошибку наблюдаю. Не может быть дело на твоей стороне?

**Comment by tormozit** [comment]
Вызов метода selectedText("") делает ничего в этом случае. Ожидалось, что он заменит выделенный текст.

**Comment by salexdv** [comment]
> Вызов метода selectedText("") делает ничего в этом случае. Ожидалось, что он заменит выделенный текст.

`selectedText` без указания текста всего лишь возвращает текущее выделенное значение

**Comment by tormozit** [comment]
> Ты перехватываешь нажатия и сам что-то делаешь?
Да. Эти команды выполняются моим кодом.
Получается в API не продумана возможность очистки выделения. Предлагаю при передаче пустой строки очищать выделение, а при передаче Неопределено - возвращать текущее выделение.

**Comment by tormozit** [comment]
Реализовал в https://github.com/salexdv/bsl_console/pull/227

**Comment by salexdv** [comment]
Проблема решена?

**Comment by tormozit** [comment]
да
