### ISSUE TITLE
Прошу добавить загрузку структуры общего модуля через передачу JSON в метод updateMetadata или отдельный метод

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#231]

**Comment by salexdv** [comment]
Метод для загрузки структуры общих модулей [существует](https://github.com/salexdv/bsl_console/blob/develop/docs/parse_module.md). Правда, он пока не описан в readme текущей ветки.

**Comment by LevkinSergey** [comment]
Этот метод видел. ему на вход нужно передавать текст модуля. 
Я хочу анализ и сохранение структуры модуля сделать на этапе сборки. А при старте редактора или при выове события обновления метаданных, передавать структуру. 
Чтобы не хранить постоянно общие модули в какой то папке, а проанализировать их 1 раз

**Comment by salexdv** [comment]
> Этот метод видел. ему на вход нужно передавать текст модуля.
> Я хочу анализ и сохранение структуры модуля сделать на этапе сборки. А при старте редактора или при выове события обновления метаданных, передавать структуру.
> Чтобы не хранить постоянно общие модули в какой то папке, а проанализировать их 1 раз

Не очень понял идею. Можешь пояснить подробнее?

**Comment by LevkinSergey** [comment]
Идея делать анализ модулей 1 раз и потом использовать результаты анализа при работе в редактором.

Например, 
1. Запускаю обработку, которой указываю папку с конфигурацией выгруженной в файлы
2. Обработка пробегается по этой папке и анализирует общие модули, вычленяя экспортные процедуры и их описания
3. Записывает полученные описания для каждого модуля и для каждой процедуры в файл(или еще куда то)
4. При старте редактора открывает этот файл и загружает ранее проанализированные структуры общих модулей без вызова анализа кода

**Comment by salexdv** [comment]
>     2. Обработка пробегается по этой папке и анализирует общие модули, вычленяя экспортные процедуры и их описания

В конфигурации ERP, например, более 2500 модулей и обработка всех модулей занимает ~40-60 сек, но проблема даже не в этом. Я никак не могу взаимодействовать с файловой системой, поэтому реализовать вот это
> Записывает полученные описания для каждого модуля и для каждой процедуры в файл(или еще куда то)

я просто не имею возможности. Структуру модуля я могу получить только из 1С через `updateMetadata()`, либо через передачу полного текста модуля и его имени в `parseCommonModule()`.

В обработке, которая выложена в последем релизе есть загрузка общих модулей. Работает всё практически мгновенно. Для общих модулей реализована динамическая загрузка т.е. загрузка по требованию. Единственное, при инициализации редактору надо сразу скормить все глобальные модули и список всех общих неглобальных модулей. 

Если ты делаешь что-то неуниверсальное, то есть еще вариант перед загрузкой исходников записать структуру всех общих модулей в файл `bslMetadata.js`.

**Comment by LevkinSergey** [comment]
первые три пункта я реализую сам. Отдельно от редактора. Соответственно и анализ исходников тоже. Я использую этот инструмент https://github.com/1c-syntax/bsl-parser. Есть аналог для платформы.

Мне от редактора нужен только метод куда я смогу передать подготовленное описание

**Comment by salexdv** [comment]
> Мне от редактора нужен только метод куда я смогу передать подготовленное описание

Вот такой вызов загрузит всю готовую структуру

```js
updateMetadata(`{
    "ОбщегоНазначения":{...},
    "УправлениеСвойствами":{...},
    "МойПрекрасныйМодуль":{...}  
}`, 'commonModules.items')
```

**Comment by LevkinSergey** [comment]
> > Мне от редактора нужен только метод куда я смогу передать подготовленное описание
> 
> Вот такой вызов загрузит всю готовую структуру
> 
> ```js
> updateMetadata(`{
>     "ОбщегоНазначения":{...},
>     "УправлениеСвойствами":{...},
>     "МойПрекрасныйМодуль":{...}  
> }`, 'commonModules.items')
> ```

А в какие параметры описания метода передавать описание процедуры? properties?

**Comment by LevkinSergey** [comment]
Подсмотрю в методе parseModule. Спасибо

**Comment by salexdv** [comment]
Сейчас сделаю пример

**Comment by salexdv** [comment]
На примере одного модуля:

```js
updateMetadata(`{
  "ОбщегоНазначения": {
    "СообщитьПользователю": {
      "name": "СообщитьПользователю",
      "name_en": "СообщитьПользователю",
      "description": "Формирует и выводит сообщение, которое может быть связано с элементом управления формы.\n\n Параметры:\n  ТекстСообщенияПользователю - Строка - текст сообщения.\n  КлючДанных - ЛюбаяСсылка - объект или ключ записи информационной базы, к которому это сообщение относится.\n  Поле - Строка - наименование реквизита формы.\n  ПутьКДанным - Строка - путь к данным (путь к реквизиту формы).\n  Отказ - Булево - выходной параметр, всегда устанавливается в значение Истина.\n\n Пример:\n\n  1. Для вывода сообщения у поля управляемой формы, связанного с реквизитом объекта:\n  ОбщегоНазначенияКлиент.СообщитьПользователю(\n   НСтр(\"ru = 'Сообщение об ошибке.'\"), ,\n   \"ПолеВРеквизитеФормыОбъект\",\n   \"Объект\");\n\n  Альтернативный вариант использования в форме объекта:\n  ОбщегоНазначенияКлиент.СообщитьПользователю(\n   НСтр(\"ru = 'Сообщение об ошибке.'\"), ,\n   \"Объект.ПолеВРеквизитеФормыОбъект\");\n\n  2. Для вывода сообщения рядом с полем управляемой формы, связанным с реквизитом формы:\n  ОбщегоНазначенияКлиент.СообщитьПользователю(\n   НСтр(\"ru = 'Сообщение об ошибке.'\"), ,\n   \"ИмяРеквизитаФормы\");\n\n  3. Для вывода сообщения связанного с объектом информационной базы:\n  ОбщегоНазначенияКлиент.СообщитьПользователю(\n   НСтр(\"ru = 'Сообщение об ошибке.'\"), ОбъектИнформационнойБазы, \"Ответственный\",,Отказ);\n\n  4. Для вывода сообщения по ссылке на объект информационной базы:\n  ОбщегоНазначенияКлиент.СообщитьПользователю(\n   НСтр(\"ru = 'Сообщение об ошибке.'\"), Ссылка, , , Отказ);\n\n  Случаи некорректного использования:\n   1. Передача одновременно параметров КлючДанных и ПутьКДанным.\n   2. Передача в параметре КлючДанных значения типа отличного от допустимого.\n   3. Установка ссылки без установки поля (и/или пути к данным).",
      "detail": "Формирует и выводит сообщение, которое может быть связано с элементом управления формы.",
      "returns": "",
      "signature": {
        "default": {
          "СтрокаПараметров": "( \n\tЗнач ТекстСообщенияПользователю,\n\tЗнач КлючДанных = Неопределено,\n\tЗнач Поле = \"\",\n\tЗнач ПутьКДанным = \"\",\n\tОтказ = Ложь)",
          "Параметры": {
            "Знач ТекстСообщенияПользователю": "",
            "Знач КлючДанных": "",
            "Знач Поле": "",
            "Знач ПутьКДанным": "",
            "Отказ": ""
          }
        }
      }
    },
    "ЗначениеРеквизитаОбъекта": {
      "name": "ЗначениеРеквизитаОбъекта",
      "name_en": "ЗначениеРеквизитаОбъекта",
      "description": "Возвращает значения реквизита, прочитанного из информационной базы по ссылке на объект.\n Рекомендуется использовать вместо обращения к реквизитам объекта через точку от ссылки на объект\n для быстрого чтения отдельных реквизитов объекта из базы данных.\n\n Если необходимо зачитать реквизит независимо от прав текущего пользователя,\n то следует использовать предварительный переход в привилегированный режим.\n\n Параметры:\n  Ссылка    - ЛюбаяСсылка - объект, значения реквизитов которого необходимо получить.\n            - Строка      - полное имя предопределенного элемента, значения реквизитов которого необходимо получить.\n  ИмяРеквизита       - Строка - имя получаемого реквизита.\n  ВыбратьРазрешенные - Булево - если Истина, то запрос к объекту выполняется с учетом прав пользователя;\n                                если есть ограничение на уровне записей, то возвращается Неопределено;\n                                если нет прав для работы с таблицей, то возникнет исключение;\n                                если Ложь, то возникнет исключение при отсутствии прав на таблицу\n                                или любой из реквизитов.\n  КодЯзыка - Строка - код языка для мультиязычного реквизита.\n\n Возвращаемое значение:\n  Произвольный - зависит от типа значения прочитанного реквизита.\n               - если в параметр Ссылка передана пустая ссылка, то возвращается Неопределено;\n               - если в параметр Ссылка передана ссылка несуществующего объекта (битая ссылка), \n                 то возвращается Неопределено.",
      "detail": "Возвращает значения реквизита, прочитанного из информационной базы по ссылке на объект.\n Рекомендуется использовать вместо обращения к реквизитам объекта через точку от ссылки на объект\n для быстрого чтения отдельных реквизитов объекта из базы данных.\n\n Если необходимо зачитать реквизит независимо от прав текущего пользователя,\n то следует использовать предварительный переход в привилегированный режим.",
      "returns": "",
      "signature": {
        "default": {
          "СтрокаПараметров": "(Ссылка, ИмяРеквизита, ВыбратьРазрешенные = Ложь, КодЯзыка = Неопределено)",
          "Параметры": {
            "Ссылка": "",
            "ИмяРеквизита": "",
            "ВыбратьРазрешенные": "",
            "КодЯзыка": ""
          }
        }
      }
    }
  }
}`, 'commonModules.items');
```

**Comment by LevkinSergey** [comment]
то, что нужно

**Comment by salexdv** [comment]
В примере не заполнены описания переменных функций, а вообще и их можно передать
```json
"Параметры": {
    "Знач ТекстСообщенияПользователю": "Тут описание переменной ТекстСообщенияПользователю",
    "Знач КлючДанных": "Тут описание переменной КлючДанных",
    "Знач Поле": "Тут описание переменной Поле",
    "Знач ПутьКДанным": "Тут описание переменной ПутьКДанным",
    "Отказ": "Тут описание переменной Отказ"
  }
```

**Comment by Evg-lylyk** [comment]
Зачем идти этим путем не понимаю, у всех конфигурации которые меняются каждый чуть ли не каждый день, как появится новая функция моего модуля, а если я добавил расширение!?
Держать в памяти вся описание! Ради чего что пользователь вызвал подсказку по 5 модулям.

**Comment by Evg-lylyk** [comment]
Еще и нужно делать парсинг, уже все сделано

**Comment by salexdv** [comment]
> Еще и нужно делать парсинг, уже все сделано

Парсинг у меня простейший. Думаю, что его можно улучшить, чтобы получать более точное описание.

**Comment by Evg-lylyk** [comment]
> > Еще и нужно делать парсинг, уже все сделано
> 
> Парсинг у меня простейший. Думаю, что его можно улучшить, чтобы получать более точное описание.

Согласен, думаю он улучшится по мере задействования этой фичи, там простое описание

**Comment by LevkinSergey** [comment]
> Зачем идти этим путем не понимаю, у всех конфигурации которые меняются каждый чуть ли не каждый день, как появится новая функция моего модуля, а если я добавил расширение!?
> Держать в памяти вся описание! Ради чего что пользователь вызвал подсказку по 5 модулям.

Основное на мой взгляд неудобство использования метода с парсингом модулей онлайн - это 

- накладные затраты каждый раз при работе с модулем на парсинг. Получается это нужно делать каждый раз в разрезе сеанса. 
- необходимость держать копию файлов текущей конфигурации на диске и всех ее расширений. А оно занимает много места
- Разбирать модули нужно на клиенте. Учитывая тенденции к асинхронному выполнению всех файловых методов в платформе на клиенте, это точно не будет очень быстро. 
- Проблема с актуализацией файлов модулей точно так же не решается, как и с единоразовым разбором. Его нужно актуализировать руками или точно так же писать скрипт.

Единственное где на первый взгляд это удобно применять -  это разработка с использованием EDT. Тогда исходники все равно хранятся на диске.

Метод с единоразовым разбором обладает двумя недостатками на мой взгляд:

- Актуализация данных разбора модулей. 
- Хранение данных разбора. Они могут занимать значительное место на диске.

**Comment by Evg-lylyk** [comment]
В ERP всего модулей ~2500 и сколько из них будет использоваться в консоли кода 10. В динамическом разборе 2490 модулей никогда не загрузятся и не будут висеть в памяти на диске.
"накладные затраты каждый раз при работе с модулем на парсинг" они копеечные загружается только нужный модуль и есть повтИсп
"необходимость держать копию файлов текущей конфигурации на диске и всех ее расширений. А оно занимает много места" можно выгрузить только модули и держать только их а если уже есть на диске достаточно указать папку
"Проблема с актуализацией файлов модулей точно так же не решается, как и с единоразовым разбором. Его нужно актуализировать руками или точно так же писать скрипт."
Тут общее, + если использовать путь пользователь твоих инструментов не должен знать ни про какую обработку актуализации

Все аргументы по поводу скорости, выше пишут что работает почти мгновенно.
Динамическое считывание уже доказало свою эффективность, метаданные прекрасно так работают принцип тотже.

**Comment by Evg-lylyk** [comment]
ИМХО существующий метод более простой еще и более функциональный и удобный.
Разницу в скорости эффективности никто не заметит так и сейчас работает комфортно

**Comment by salexdv** [comment]
> * Разбирать модули нужно на клиенте. Учитывая тенденции к асинхронному выполнению всех файловых методов в платформе на клиенте, это точно не будет очень быстро.

Вот демонстрация загрузки модулей на клиенте на лету
![cp1vP5d4RC](https://user-images.githubusercontent.com/6356534/132213222-5aa3f00e-3d5b-4978-a7b8-97f11ff7933e.gif)

Возможно, при загрузке очень больших модулей будет наблюдаться небольшое подтормаживание, но, на мой взгляд, это работает вполне быстро.

**Comment by LevkinSergey** [comment]
> > * Разбирать модули нужно на клиенте. Учитывая тенденции к асинхронному выполнению всех файловых методов в платформе на клиенте, это точно не будет очень быстро.
> 
> Вот демонстрация загрузки модулей на клиенте на лету
> ![cp1vP5d4RC](https://user-images.githubusercontent.com/6356534/132213222-5aa3f00e-3d5b-4978-a7b8-97f11ff7933e.gif)
> 
> Возможно, при загрузке очень больших модулей будет наблюдаться небольшое подтормаживание, но, на мой взгляд, это работает вполне быстро.

Выглядит достойно. Буду разбираться.
