### ISSUE TITLE
Подробный парсинг описания процедур общих модулей

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#232]
В большинства функций общих модулей хорошее описание, например

// Преобразует строковое представление УИД в ссылку на объект текущей информационной базы.
// Сначала выполняется поиск УИД в регистре публичных идентификаторов.
// При удачном поиске возвращается ссылка из регистра, при неудачном
// возвращается либо ссылка с исходным УИД (если она еще не сопоставлена),
// либо выполняется генерация новой ссылки со случайным УИД.
// И в том и в другом случае в регистре публичных идентификаторов создается запись.
// 
// Параметры:
//  УИДОбъектаXDTO       - Строка - Уникальный идентификатор объекта XDTO, для которого необходимо 
//                                  получить ссылку соответствующего объекта информационной базы.
//
//  ТипЗначенияОбъектаИБ - Тип - Тип объекта информационной базы, которому должна соответствовать
//                               получаемая ссылка.
//
//  КомпонентыОбмена     - Структура - Содержит все необходимые данные, инициализированные при начале
//                                     выполнения обмена (ПКО, ПКПД, ПОД и т.д.).
//
// Возвращаемое значение:
//  Ссылка на объект информационной базы.
// 
Функция СсылкаОбъектаПоУИДОбъектаXDTO(УИДОбъектаXDTO, ТипЗначенияОбъектаИБ, КомпонентыОбмена) Экспорт

Хотелось бы подробного разбора описания, параметров и их типов, возвращаемых значений

**Comment by salexdv** [comment]
Добавил парсинг описания параметров.
С возращаемым значением пока ничего не делал, да и не уверен, что это очень нужно. Если взать в качестве примера тот код, который ты представил выше, тогда описание функции с возвращаемым значением будет выглядеть так:
`СсылкаОбъектаПоУИДОбъектаXDTO(УИДОбъектаXDTO, ТипЗначенияОбъектаИБ, КомпонентыОбмена): Ссылка на объект информационной базы`
Не очень-то лаконично. Кроме того, возвращаемое значение и сейчас можно увидеть т.к. в полное описание функции (значок детальной информации в списке подсказок) и так включается всё описание функции, в котором можно увидеть в том числе и тип возращаемого значения.
