### ISSUE TITLE
Добавить возможность у объекта метаданных указывать экспортные методы объекта и менеджера

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#233]
![image](https://user-images.githubusercontent.com/36307272/132217374-9b9e57a1-741b-4dc8-8a9d-f0221a518867.png)

**Comment by salexdv** [comment]
Реализовал загрузку модулей объектов и модулей менеджеров. Расширен список параметров, которые могут присутствовать в событии [`EVENT_GET_METADATA`](https://github.com/salexdv/bsl_console/blob/develop/docs/get_metadata_event.md). Добавлена функция [`parseMetadataModule`](https://github.com/salexdv/bsl_console/blob/develop/docs/parse_metadata_module.md) для загрузки модулей.
В ветке под webpack соответствующий функционал появится в ближайшее время.

**Comment by salexdv** [comment]
@LevkinSergey, ветку под webpack доработал. Теперь там тоже должно работать. Примеры реализации нужны?

**Comment by LevkinSergey** [comment]
@salexdv Проверил сборку под webpack. В основном все работает. Проблем с событиями модуля менеджера нет. Парсинг работает.
Но события по модулям объекта прилетают только по справочникам.

**Comment by salexdv** [comment]
> @salexdv Проверил сборку под webpack. В основном все работает. Проблем с событиями модуля менеджера нет. Парсинг работает.
> Но события по модулям объекта прилетают только по справочникам.

Проверю

**Comment by LevkinSergey** [comment]
в последней версии работает
