### ISSUE TITLE
Предлагаю доработать шаблон (snippet) "Для...по...Цикл"

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#235]
![изображение](https://user-images.githubusercontent.com/11896251/133880010-0d5e1a5a-195c-4397-b42f-73396d0b4009.png)

Сейчас шаблон (snippet) вставляет текст
```
Для Счетчик По Ограничение Цикл
КонецЦикла;
```
Я предлагаю вставлять
```
Для Счетчик = 1 По Ограничение Цикл
КонецЦикла;
```
т.к. обычно значение начинается с 1. Кажется так будет удобнее.

**Comment by salexdv** [comment]
Доработал

**Comment by tormozit** [comment]
Заработало
