### ISSUE TITLE
Выделение текста игнорирует текст в строке с разделителем отдельных запросов пакета

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#237]
https://github.com/salexdv/bsl_console/issues/218
Выделение текста не отображается в такой строке
![изображение](https://user-images.githubusercontent.com/11896251/135091567-27ddb615-eaf5-436f-a08f-632a2b15af47.png)

**Comment by salexdv** [comment]
К сожалению, нормального способа повлиять на такое поведение нет.
