### ISSUE TITLE
Сломалось повторное выполнение compare()

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#239]
https://github.com/salexdv/bsl_console/issues/168
```bsl
Если ВариантСинтаксиса = ПодменюСинтаксис.ВстроенныйЯзык.Имя Тогда
		РедакторHTML.switchLanguageMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.ЯзыкЗапросов.Имя Тогда
		РедакторHTML.switchQueryMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.ЯзыкКомпоновки.Имя Тогда
		РедакторHTML.switchDCSMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.XML.Имя Тогда
		РедакторHTML.switchXMLMode();
	КонецЕсли; 
	РедакторHTML.compare(Текст2, Истина, ПодсветкаСинтаксиса, Истина);
```
Первый вызов - ОК. Второй вызов даже без изменения параметров (ВариантСинтаксиса) очищает поле HTML

![изображение](https://user-images.githubusercontent.com/11896251/137528641-fceaf911-b487-4dd8-ba9b-211c0b3e22bb.png)

**Comment by salexdv** [comment]
Как выглядел этот вызов 
```bsl
РедакторHTML.compare(Текст2, Истина, ПодсветкаСинтаксиса, Истина)
```
до того, как я удалил параметр?

**Comment by tormozit** [comment]
> Как выглядел этот вызов
```

	РежимXML = Ложь;
	Если ВариантСинтаксиса = ПодменюСинтаксис.ВстроенныйЯзык.Имя Тогда
		РедакторHTML.switchLanguageMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.ЯзыкЗапросов.Имя Тогда
		РедакторHTML.switchQueryMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.ЯзыкКомпоновки.Имя Тогда
		РедакторHTML.switchDCSMode();
	ИначеЕсли ВариантСинтаксиса = ПодменюСинтаксис.XML.Имя Тогда
		РежимXML = Истина;
	КонецЕсли; 
	РедакторHTML.compare(Текст2, Истина, ПодсветкаСинтаксиса, РежимXML, Истина);
```

**Comment by tormozit** [comment]
Обновился. Теперь опять не переключается подсветка синтаксиса.

**Comment by salexdv** [comment]
Мне надо переписать функции, которые переключают языки. После этого тебе надо будет вызывать только `switchLanguageMode()` и передавать туда идентификатор языка. Текущий подход с вызовом `switchQueryMode`, `switchDCSMode` и `switchXMLMode` т.к. эти функции работают как переключатели туда и обратно и двойной выбор, например XML, всё равно всё будет ломать. Как сделаю, отпишусь.

**Comment by salexdv** [comment]
При использовании [новой функции](https://github.com/salexdv/bsl_console/issues/241#issuecomment-957146672) для переключения режима должно работать правильно.
