### ISSUE TITLE
Новый подход к переключению режима (языка) редактора

### ISSUE THREAD

**Issue by salexdv** [salexdv/bsl_console#241]
В начале разработки консоли был только режим редактирования кода, затем появился режим редактирования языка запросов и переключение между этими режимами было реализовано с помощью функции `switchQueryMode`. Затем появился режим СКД и XML, а также соответствующие им функции `switchDCSMode` и `switchXMLMode`. Логика переключения при этом осталась старая т.е. изначально редактор загружается в режиме редактирования кода, а затем с помощью одной из упомянутых выше функций переключается в нужный режим и обратно. Предполагалось, что в одном окне работает максимум 2 режима, а именно режим редактирования встроенного языка и еще один из поддерживаемых.

В данный момент такой подход неудобен т.к. иногда сценарии использования консоли предполагают использование всех режимов в одном окне, например, #163 #239. При использовании функций-переключателей довольно непросто сделать корректное переключение из любого режима в любой, в том числе при использовании режима сравнения `compare`

Необходимо реализовать функцию, которая будет переключать режим редактора в любой из поддерживаемых режимов.
Например,
```js
setLanguageMode('bsl_query'); // Переключение в режим языка запросов
setLanguageMode('dcs_query'); // Переключение в режим языка СКД
setLanguageMode('xml'); // Переключение в режим XML
setLanguageMode('bsl'); // Переключение в режим встроенного языка
```
Такой подход позволит без проблем переключаться между режимами. Функции `switchQueryMode`, `switchDCSMode`, `switchXMLMode`, а также `switchLanguageMode` будут признаны устаревшими и через некоторое время будут удалены.

Возможно, будут какие-либо предложения или замечания от @GenVP, @tormozit, @Evg-lylyk?

**Comment by salexdv** [comment]
Реализовал функцию [setLanguageMode](https://github.com/salexdv/bsl_console/blob/develop/docs/set_language_mode.md) для переключения из любого режима в любой. Функции `switchQueryMode`, `switchDCSMode`, `switchXMLMode`, а также `switchLanguageMode` признаны устаревшими и через некоторое время будут удалены.

**Comment by tormozit** [comment]
Проверил. Все работает.
