### ISSUE TITLE
Поддержка символа # в имени временной таблицы

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#242]
Оказывается # может содержатся в имени вт, я думал что оно подчиняется правилу всех идентификаторов.
Может даже начинаться с решетки
ВЫБРАТЬ
	_ДемоБанковскиеСчета.Ссылка КАК Ссылка
ПОМЕСТИТЬ ##123
ИЗ
	Справочник._ДемоБанковскиеСчета КАК _ДемоБанковскиеСчета

Сейчас заметил что неверна подцветка для приведенного примера, посмотри у себя внутри может есть другие проблемы

**Comment by salexdv** [comment]
Указанный выше пример должен теперь раскрашиваться корректно, но пока не удалось сделать нормальные правила для следующих случаев:
1. Имя временной таблицы на новой строке
```bsl
ВЫБРАТЬ
	Товары.Ссылка КАК Ссылка
ПОМЕСТИТЬ
	##врем_таб_###_#
ИЗ
	Справочник.Товары КАК Товары
```
2. Временная таблица, как источник
```bsl
ВЫБРАТЬ
	врем_там__.Ссылка КАК Ссылка
ИЗ
	##врем_там_###_# КАК врем_там__
```

**Comment by salexdv** [comment]
Решено
