### ISSUE TITLE
Не показывать подсказку в комментарии

### ISSUE THREAD

**Issue by ivanov660** [salexdv/bsl_console#243]
Есть проблема, подскажите как исправить. Сходу не нашел решения.

**Как есть**
1. Редактирую текст 
2. Добавляю начало комментария и пишу комментарий
3. Всплывает подсказка

**Как требуется**
1. Редактируется текст
2. Добавляю начало комментария и пишу комментарий
3. подсказка не всплывает

![image](https://user-images.githubusercontent.com/24763549/139457563-ace9c822-a0b6-4331-9725-2d944ef70310.png)

**Comment by salexdv** [comment]
Исправил. Теперь в комментариях подсказка показываться не будет.

**Comment by tormozit** [comment]
По CTRL+SPACE и CTRL+SHIFT+SPACE внутри комментария прошу оставить работу автодополнения и подсказки по вызову метода, если это не сложно.

**Comment by salexdv** [comment]
> По CTRL+SPACE и CTRL+SHIFT+SPACE внутри комментария прошу оставить работу автодополнения и подсказки по вызову метода, если это не сложно. Или хотя бы оставь генерацию соответствующих событий API. В комментариях иногда приходится писать/обновлять элементы программного кода.

Подумаю, как это лучше реализовать.

**Comment by ivanov660** [comment]
На мой взгляд, звучит довольно странно желание редактировать в комментариях. Получается какая-то подмена понятий код и комментарий, не встречал такого поведения в других редакторах кода.

**Comment by tormozit** [comment]
Принимаю странность в чужом восприятии желания редактировать в комментариях. В моем редакторе кода так уже 15 лет работает. Вреда от этого нет. А польза кому то есть, включая меня. Взять тот же EDT - в комментариях есть автодополнение.
