### ISSUE TITLE
Некорректное форматирование выделенного кода Alt+Shift+F

### ISSUE THREAD

**Issue by PerlAmutor** [salexdv/bsl_console#245]
Пользуюсь "Инструментами Разработчика" от Tormozit. Выделил код в Консоли Кода, нажал Alt+Shift+F и почему-то отформатировался весь модуль, да как-то криво, да и курсор перескочил в непонятное место.

https://user-images.githubusercontent.com/87958986/141330777-6aec381f-7cdc-4184-9ebc-056cb9f80593.mp4

[МодульБСП.zip](https://github.com/salexdv/bsl_console/files/7521775/default.zip)

**Comment by tormozit** [comment]
Текст приложи файлом

**Comment by salexdv** [comment]
Функция форматирования стала работать лучше, но пока нет возможности форматировать выделенный фрагмент. Также остается проблема с изменением позиции курсора после форматирования.

**Comment by PerlAmutor** [comment]
Пока как-то так:

![image](https://user-images.githubusercontent.com/87958986/143614697-a4dc373e-6fc1-49a3-8375-c6ecf10c5999.png)

**Comment by salexdv** [comment]
Точно используется последняя версия исходников из ветки `develop`?
Вот как  должно выглядеть форматирование того же модуля и того же фрагмента:
![J1NuTAb9Z7](https://user-images.githubusercontent.com/6356534/143618346-de96b81c-aaf1-42bc-99f9-d63337f98d2a.gif)

**Comment by PerlAmutor** [comment]
Использовал в онлайне - https://salexdv.github.io/bsl_console/src/index.html думал туда попадают последние изменения.

**Comment by salexdv** [comment]
> Использовал в онлайне - https://salexdv.github.io/bsl_console/src/index.html думал туда попадают последние изменения.

Изменения туда обычно попадают только после обновления ветки master. Сейчас обновил вручную, надо только сбросить кэш (CTRL+F5)

**Comment by salexdv** [comment]
Добавил поддержку форматирования для выделенного фрагмента
