### ISSUE TITLE
Замена строки целиком не находит слово из одной буквы

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#256]
Пытался в тексте
```bsl
А = Новый НастройкиКомпоновкиДанных;
Э = а.Отбор.Элементы.Добавить(Тип("ЭлементОтбораКомпоновкиДанных"));
Э.ЛевоеЗначение = Новый ПолеКомпоновкиДанных("");
Э.ПравоеЗначение = " ";
Сообщить(СтрДлина(А.Отбор.Элементы[0].ПравоеЗначение));
З = Новый ЗаписьXML;
З.УстановитьСтроку("");
СериализаторXDTO.ЗаписатьXML(З, а);
Стр = З.Закрыть();
ЧтениеXML = Новый ЧтениеXML;
ЧтениеXML.УстановитьСтроку(Стр);
Б = СериализаторXDTO.ПрочитатьXML(ЧтениеXML);
Сообщить(СтрДлина(Б.Отбор.Элементы[0].ПравоеЗначение));
```
Заменить все вхождения слова "А" целиком. Но редактор не нашел такие слова.

![изображение](https://user-images.githubusercontent.com/11896251/147413360-a19b14c1-8e71-41bf-843a-b4ec9d2b35fe.png)

![изображение](https://user-images.githubusercontent.com/11896251/147413361-466d83f8-67c2-4a90-a527-0191d634b53a.png)

**Comment by salexdv** [comment]
Проблема связанна вот с этим #103. После добавления пробела или символа табуляции в начале слова всё начинает работать без ошибок. Наблюдается только в 1С. На данный момент решения нет.
