### ISSUE TITLE
Не работает подсказка по табличным частям объекта

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#259]
Если табличные части передать в параметр "tabulars" объекта, они не отображаются в списке подсказок объекта. Приходится их добавлять как реквизит.

В коде не подсказываются как свойства, так и методы табличной части. В запросе по табличной части подсказываются поля объекта. Также в запросе заметил при попытке обращения к списку табличных частей в разделе **ИЗ** не выдает ни какой подсказки.

Поведение наблюдается и на windows и на linux

Пример кода
```
Спр = Справочники._ДемоНоменклатура.СоздатьЭлемент();
НС = спр.ДополнительныеРеквизиты.Добавить();
```

Пример запроса

```
ВЫБРАТЬ
	_ДемоЗаказПокупателя.Ссылка КАК Ссылка,
	_ДемоЗаказПокупателя.
	
ИЗ
	Документ._ДемоЗаказПокупателя.КонтактнаяИнформация КАК _ДемоЗаказПокупателя
```

**Comment by salexdv** [comment]
Поддержку табличных частей добавлю
