### ISSUE TITLE
Проблема с кодировкой на версии 8.3.16 #bug

### ISSUE THREAD

**Issue by glazachevpavel** [salexdv/bsl_console#262]
Я обнаружил, что обработка не запускается на моем ПК, в то время как спокойно работает на ПК соседа. Версии платформы одинаковые 8.3.16. После отладки обнаружил, что проблема заключается в том, что у меня на ПК, используется пользователь с кириллическими символами, соответственно путь до кэша содержит кириллицу (C:/Users/**Глазачев Павел**/AppData/Local/Temp/bsl_console/63777416011870.html)

И выдает такую ошибку: 
_Couldn't read a file:// file: file:///C:/Users/**%D0%93%D0%BB%D0%B0%D0%B7%D0%B0%D1%87%D0%B5%D0%B2%20%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB**/AppData/Local/Temp/bsl_console/63777416011870.html_

Есть ли моды борьбы с данной проблемой? Я имею желание в свою небольшую обработку внедрить эдитор, просто не хотелось бы, чтобы пользователи сталкивались с подобной проблемой...

P.s. На версии 8.3.19 все отлично отрабатывает, но вопрос по борьбе на 8.3.16 так и остается

**Comment by salexdv** [comment]
Напишите полную версию 8.3.16

**Comment by glazachevpavel** [comment]
8.3.16.1973

**Comment by glazachevpavel** [comment]
Для наглядности

![image](https://user-images.githubusercontent.com/97449684/148773065-aca3fc63-52d9-47e4-ae01-a035e9e13523.png)

**Comment by salexdv** [comment]
Это действительно глюк конкретного релиза платформы. Ошибка возникает с любыми файлами, в пути которых есть кириллица. Могу предложить вам два пути решения:
1. Если обработка, в которую вы собираетесь добавить редактор не тиражная, то можно распаковывать исходники в каталог, который не содержит кириллицы.
2. Собрать один файл index.html, используя ветку [webpack](https://github.com/salexdv/bsl_console/tree/webpack) и параметр maxChunks = 1 в файле webpack.config.js, а затем реквизиту, связанному с полем HTML присваивать адрес временного хранилища, в котором находятся двоичные данные полученного файла.

**Comment by glazachevpavel** [comment]
Спасибо большое! Вопрос закрыт, буду пробовать :)

**Comment by glazachevpavel** [comment]
А подскажите пожалуйста, я с горем пополам собрал сборку в 1 файл с помощью webpack, в 1с все работает отлично, только проблема в том, что собранный файл весит 7 МБ... Это нормально для web pack или я не правильно собрал?

**Comment by salexdv** [comment]
> А подскажите пожалуйста, я с горем пополам собрал сборку в 1 файл с помощью webpack, в 1с все работает отлично, только проблема в том, что собранный файл весит 7 МБ... Это нормально для web pack или я не правильно собрал?

Так и должно быть. Если посмотреть размер всех исходников, то примерно такой цифра и будет.

**Comment by glazachevpavel** [comment]
Еще раз спасибо, решил проблему веса, обычным сжатием ZIP, получился всего 1 МБ, каждый раз при использовании он распаковывается, получается очень быстро :)
