### ISSUE TITLE
Вопрос. Как правильно передать тип регистра сведений в customObject?

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#263]
Следующие типы не работают
регистрысведений._ДемоГрафикиРаботы
informationregisters._ДемоГрафикиРаботы
infoRegs._ДемоГрафикиРаботы
infoRegs.items._ДемоГрафикиРаботы

**Comment by salexdv** [comment]
infoRegs.<ИмяРегистра> должно работать
![chrome_Wijuxsq6xn](https://user-images.githubusercontent.com/6356534/149000723-d9988c11-97c9-40de-9a2e-a8c4f9b53e0c.gif)

**Comment by LevkinSergey** [comment]
В сборке под windows все работает.
Но в сборке под webpack не прилетает событие на получение метаданных по конкретному регистру. Событие на все регистры прилетает

**Comment by salexdv** [comment]
Проверю

**Comment by salexdv** [comment]
> В сборке под windows все работает. Но в сборке под webpack не прилетает событие на получение метаданных по конкретному регистру. Событие на все регистры прилетает

В сборке под webpack в linux или windows? Только что посмотрел в windows и тоже проблем не обнаружил.

**Comment by LevkinSergey** [comment]
в linux. В windows ее не использую, т.к. загрузка редактора выполняется заметно дольше

**Comment by salexdv** [comment]
> в linux. В windows ее не использую, т.к. загрузка редактора выполняется заметно дольше

Понял. Проверю.

**Comment by salexdv** [comment]
Должно заработать.
