### ISSUE TITLE
Реализовать подсказку по табличным частям объекта

### ISSUE THREAD

**Issue by salexdv** [salexdv/bsl_console#266]
Добавить подсказку по табличным частям объектов (Справочники, Документы, Обработки и т.д.), а также по реквизитам табличных частей.
#259

**Comment by salexdv** [comment]
Подсказка по табличным частям добавлена, правда, пришлось несколько поменять структуру хранения информации о табличных частях конкретного объекта метаданных. 
Теперь вместо вот такого объявления:
```json
"tabulars":{
  "ДополнительныеРеквизиты":{
      "ИмяРеквизита":{
         "name": "Имя дополнительного реквизита"
      },
      "ЗначениеРеквизита":{
         "name": "Значение реквизита",
         "ref": "catalogs.СтавкиНДС"
      }
  }
}
```
нужно передавать описание в следующем формате:
```json
"tabulars":{
  "ДополнительныеРеквизиты":{
     "properties":{
        "ИмяРеквизита":{
           "name": "Имя дополнительного реквизита"
        },
        "ЗначениеРеквизита":{
           "name": "Значение реквизита",
           "ref": "catalogs.СтавкиНДС"
        }
     }
  }
}
```

**Comment by LevkinSergey** [comment]
Просьба добавить данную фичу в ветку webpack

**Comment by salexdv** [comment]
> Просьба добавить данную фичу в ветку webpack

Сделаю в ближайшие дни
