### ISSUE TITLE
В версиях 0.2.8 и 0.2.9 возникает ошибка setOption

### ISSUE THREAD

**Issue by PRyzhov** [salexdv/bsl_console#269]
При открытии обработки на платформе 8.3.18.1741 (32) возникает ошибка:
`{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(364)}: Метод объекта не обнаружен (setOption)`
После нажатия Ok редактор позволяет вводить код в окно редактирования, но кнопки действий неактивны.

Дополнительно прикладываю Отчёт об ошибке сформированной платформой:
[Ошибка_20220201222726.zip](https://github.com/salexdv/bsl_console/files/7981420/_20220201222726.zip)

**Comment by salexdv** [comment]
Проверил версию 0.2.9 на указанном релизе платформы, ошибки не обнаружил. Попробуйте очистить каталог %Temp%\bsl_console\ и запустить обработку заново.

**Comment by PRyzhov** [comment]
Помогло. Спасибо 👍
