### ISSUE TITLE
Попробовать адаптивное растягивание чтобы окно монако растягивалось вмести с окном  html

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#27]

**Comment by salexdv** [comment]
Включить адаптивность можно немного изменив блок создания редактора в файле [editor.js](https://github.com/salexdv/bsl_console/blob/fdaca80844ea7ee8799bce8d82a2c501143da3ad/src/editor.js#L258)
```javascript
editor = monaco.editor.create(document.getElementById("container"), {
    theme: "bsl-white",
    value: getCode(),
    language: language.id,
    contextmenu: true,
    automaticLayout: true // <-- добавляем эту опцию
});
```
В основной ветке мне бы этого делать не хотелось т.к. в документации [явно указано](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#automaticlayout), что это может существенно сказаться на производительности.

**Comment by Evg-lylyk** [comment]
Спасибо, внедрил. Никаких проблем не заметил
