### ISSUE TITLE
Размер табуляции?

### ISSUE THREAD

**Issue by small-hamster** [salexdv/bsl_console#273]
Как управлять размером табуляции (tab-size/indent)?

**Comment by salexdv** [comment]
Размером табуляции можно управлять через опцию `tabSize`. К сожалению, эту опцию нельзя менять на лету. Для таких случаев предусмотрена заглушка [`customOptions`](https://github.com/salexdv/bsl_console/blob/13dc1f71c893cb8fe72cae0de0376733ed4e7ef6/src/editor.js#L1450). Перед загрузкой исходников заменяйте эту опцию, например, на `tabSize: 8` и редактор загрузится с нужным размером отступов.

**Comment by small-hamster** [comment]
Спасибо! То, что нужно! Наверное, можно добавить это в документацию? ;)
