### ISSUE TITLE
Раскраска кода после слеша перед кавычкой

### ISSUE THREAD

**Issue by JohnyDeath** [salexdv/bsl_console#274]
Имеем код:
```bsl
начКаталог = "D:\Temp\1\"; ЭтотКодНеДолженПодсвечиватьсяКакТекст = Неопределено;
```
Выглядит вот так:
![image](https://user-images.githubusercontent.com/5936030/163389591-9860f02d-2506-4e54-88bc-40b7a6ca1717.png)
без последнего слеша в пути - всё нормально
![Uploading image.png…]()

**Comment by salexdv** [comment]
Исправил.
