### ISSUE TITLE
Работа с шаблонами кода в линуксе 

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#278]
Если для редактора использовать метод setOriginalText с непустым параметром, то шаблоны возвращаются к стандартному набору шаблонов.

Например
```bsl
Редактор.clearSnippets();
Редактор.parseSnippets(ТекстШаблонов, Истина); 

//Все устанавливается и работает нормально
//При вызове
Редактор.setOriginalText(НепустойТекст);

Все шаблоны возвращаются к стандартной настройке
```

**Comment by salexdv** [comment]
Пробую воспроизвести, не получается. Можешь еще раз проверить, если такая ошибка на последних исходниках?

![Шаблоны](https://user-images.githubusercontent.com/6356534/176880490-7f616db4-5556-4341-9206-22f2e5fd6e76.png)

**Comment by LevkinSergey** [comment]
Попробуй не использовать между setOriginalText и clearSnippets() метод парсинга. Я его не использую в моем кейсе

Проверю на выходных как работает на новых исходниках

**Comment by LevkinSergey** [comment]
Проверю на выходных.

Но из опыта могу сказать - то что в браузере работает совсем не показатель. Движок 1С на линуксе очень своеобразный. 
Нужно именно на нем проверять.

**Comment by salexdv** [comment]
> Проверю на выходных.
> 
> Но из опыта могу сказать - то что в браузере работает совсем не показатель. Движок HTML в 1С на линуксе очень своеобразный. Нужно именно на нем проверять.

Всё так, но это обычно касается либо интерфейсных заморочек, либо каких-нибудь регулярных выражений. Простые функции, как правило и там и там отрабатывают нормально.

**Comment by LevkinSergey** [comment]
В текущем варианте ветки webpack поведение по прежнему ошибочное. Если есть оригинальный текст, то стандартные шаблоны доступны, хотя шаблоны очищались и недоступен загруженный шаблон. 

![Peek 2022-07-03 23-29](https://user-images.githubusercontent.com/36307272/177056273-0f99d432-662e-4e59-a9db-1cc82bc1d22c.gif)

Тестовый шаблон прикладываю
[Новый1.st.zip](https://github.com/salexdv/bsl_console/files/9035467/1.st.zip)

**Comment by salexdv** [comment]
Исправил.
