### ISSUE TITLE
Как можно передать обрабатываемый объект

### ISSUE THREAD

**Issue by ilyarudziak** [salexdv/bsl_console#282]
Добрый день. Подскажите, а есть возможность добавить в код обрабатываемый объект?
В запросе хочу передать ссылку, но не нашел такой возможности(
Или подскажите в каком месте лучше доработать, сделаю PR

**Comment by salexdv** [comment]
Речь о том, чтобы выводилась подсказка для какого-то своего объекта? Если да, тогда в [обработке](https://github.com/salexdv/bsl_console/releases/download/v0.3.0/console.epf) можно посмотреть "Примеры" - "Загрузить пользовательские объекты"

**Comment by ilyarudziak** [comment]
Постарался смоделировать 
![image](https://user-images.githubusercontent.com/18754334/169988433-5d569b05-d5c0-4031-a31f-d670f21cedf0.png)

**Comment by salexdv** [comment]
В текущей реализации только через НайтиПоНаименованию/НайтиПоКоду/НайтиПоНомеру/ПолучитьСсылку

**Comment by ilyarudziak** [comment]
Принято, спасибо
