### ISSUE TITLE
Подсчет номера параметра при подсказке по параметрам

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#286]
У меня старая версия редактора. Хотел узнать, исправлен ли некорректный подсчет номера параметра в следующей ситуации на последнем параметре.
`СлужебныйМодуль.НайтиСоздатьСсылочныйОбъектПоКлючу(Новый Структура("ЭтоГруппа, Наименование", Истина, НаименованиеРодителя),, Истина)`

**Comment by salexdv** [comment]
Если говорить про последний параметр `Истина` в функции `НайтиСоздатьСсылочныйОбъектПоКлючу`, то исправлен.
Если говорить про структуру, то там подсчет параметров не дорабатывал и считается, что их максимум два.
