### ISSUE TITLE
Некорректная раскраска строковых литералов после символа "\" во встроенном языке

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#289]
У меня старая версия. Прошу проверить в новой.
`СтрЗаменить(ПутьКФайлу, "bin\", "") + "docs\ru\V8Update.htm";`
![изображение](https://user-images.githubusercontent.com/11896251/189438705-f47c1c9b-0b2b-48ff-aed6-fdd4a8e77642.png)

**Comment by salexdv** [comment]
В новой выглядит так:

![UgZi9QMx40](https://user-images.githubusercontent.com/6356534/189718070-e135d5a9-6698-43cf-98b3-b4903a0fd80f.png)

**Comment by tormozit** [comment]
Проверил. Исправлено.
