### ISSUE TITLE
Вредный перехват CTRL+клик

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#290]
Я уже просил отключить перехват CTRL+клик. Ранее я приводил аргумент, что с текущим поведением невозможно выделить слово, как это происходит. Я этой возможность в конфигураторе пользуюсь очень часто. Ты предложил вместо этого использовать двойной клик. Это долго, но терпимо, хотя и мучительно при десятках выполнений подряд.
Теперь найдена еще одна проблема порожденная перехватом CTRL+клик. Я часто копирую строки путем
1. Выделить строку
2. Зажать CTRL и нажать мышь на выделенной строке и, удерживая кнопку, перетаскиваю строку.
Сейчас при этом редактор иногда копирует только одно слово.

В редакторе VS Code такой проблемы нет, хотя при зажатии кнопки мыши на таком слове происходит его линкификация, но перетаскивание отрабатывает корректно - перетаскивается весь изначально выделенный фрагмент.

Еще было бы здорово заиметь опцию отключения этой обработки CTRL+клик и получения стандартного для конфигуратора поведения - выделения слова.
[Вредный перехват CTRL+клик Monaco.zip](https://github.com/salexdv/bsl_console/files/9538585/CTRL%2B.Monaco.zip)

**Comment by salexdv** [comment]
Доработал. Сейчас поведение должно быть похоже на поведение в конфигураторе.

**Comment by tormozit** [comment]
Проверил. Исправлено.
