### ISSUE TITLE
При установке выделения за правой границей видимой области происходит некорректная горизонтальная прокрутка

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#291]
У меня старая версия редактора.

В тексте на встроенном языке есть очень длинная строка
`// В стандартной функции управления полнотекстовым поиском реализована возможность установки максимального размера объекта, индексируемого полнотекстовым поиском и количества фоновых заданий, используемых для выполнения индексирования.Для установки этих параметров предназначен диалог, который открывается при нажатии кнопки Дополнительные параметры, размещенной в форме стандартной функции. ДокументHTML`
Пользователь ищет фрагмент "ДокументHTML". 

Выделяю его в тексте через 
`РедакторHTML.setSelectionByLength(НачальнаяСтрокаИлиПозиция, НачальнаяКолонкаИлиКонечнаяПозиция);`
Получаю это 
![изображение](https://user-images.githubusercontent.com/11896251/189471199-c7d9d362-7333-4050-9b49-32edad3e7b5e.png)

Выделяю его в тексте через 
`РедакторHTML.setSelection(НачальнаяСтрокаИлиПозиция, НачальнаяКолонкаИлиКонечнаяПозиция, КонечнаяСтрока, КонечнаяКолонка);`
Получаю это
![изображение](https://user-images.githubusercontent.com/11896251/189471264-561ede41-e78e-4c0a-8737-b578bfa0d650.png)

**Comment by salexdv** [comment]
Сейчас должно работать нормально

**Comment by tormozit** [comment]
Проверил. Исправлено.
