### ISSUE TITLE
Хочу отображать показатели слева от кода аналогично замеру производительности в конфигураторе

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#296]
![изображение](https://user-images.githubusercontent.com/11896251/199553755-bf305a1b-ef66-4010-a435-d899bffb17c5.png)

**Comment by salexdv** [comment]
Только текст или текст с картинкой? Второе вряд ли возможно на текущей версии редактора

**Comment by tormozit** [comment]
текст

**Comment by salexdv** [comment]
Можно реализовать только вот в таком виде. Визуально номера строк и текст слева не будут отличаться (цвет, шрифт)
![line_num](https://user-images.githubusercontent.com/6356534/199659792-520d8f25-8280-4b0e-bff0-47d7d7a0e4b0.png)

**Comment by tormozit** [comment]
Мне нужно для этого https://www.hostedredmine.com/issues/953306 .  Поэтому колонок хотелось бы несколько.

**Comment by salexdv** [comment]
Реализовал попробуй вызвать так:

```js
setLineNumbersDecorations('["000.00%", "010.98%", "001.03%", "009.07%", "000.00%", "000.00%", "000.00%", "000.00%", "000.00%"]')
```

Функция принимает на вход массив в виде JSON. Первое значение в массиве (индекс 0) - показатель для первой строки, второе значение - для второй и т.д.

**Comment by salexdv** [comment]
> Мне нужно для этого https://www.hostedredmine.com/issues/953306 . Поэтому колонок хотелось бы несколько.

Несколько колонок сделать нельзя. Ты можешь просто отформатировать текст для каждой строки, чтобы это было похоже на колонки

**Comment by tormozit** [comment]
Проверил. Работает. 
Хорошо бы еще добавить автоматическую очистку декорации строки, если строка изменилась, и сдвиг декорации вместе со сдвигом строки текста, т.к. эти декорации жестко связаны по смыслу со своими строками. Если такое поведение сделать сложно, то лучше тогда просто сразу удалять все декорации при первом же изменении текста. Ну и в любом случае логичным кажется их очищать при вызове функции updateText().

**Comment by tormozit** [comment]
> Первое значение в массиве (индекс 0) - показатель для первой строки

Ошибка. По факту работает не так. Первое значение игнорируется. А второе выводится в первую строку. 
Исправил в своей ветке и отправил исправление в твою.

**Comment by tormozit** [comment]
Еще некорректно выводится декорация
`     :      :     :`
В обычном поле текста он выглядит нормально

![изображение](https://user-images.githubusercontent.com/11896251/199998786-35f99654-92d7-4e91-9987-b189c0860ecb.png)

А в твоем редакторе сжато, как будто свернуты пробелы

![изображение](https://user-images.githubusercontent.com/11896251/199999021-52454b74-1ea9-49e8-bdbd-ccd4f85aa962.png)

Вот непосредственно передаваемый в функцию текст JSON
[Clip_383284.txt](https://github.com/salexdv/bsl_console/files/9939293/Clip_383284.txt)

**Comment by tormozit** [comment]
Еще хочется чтобы подсветка текущей строки захватывала область декорации. 

![изображение](https://user-images.githubusercontent.com/11896251/200055452-5f2cf821-dd73-44b9-93d0-ce04a3454008.png)

**Comment by salexdv** [comment]
Заменил обычные пробелы на неразрывные и добавил расчет отступа, чтобы обеспечить выравнивание. Посмотри на результат, пожалуйста.

**Comment by salexdv** [comment]
> Еще хочется чтобы подсветка текущей строки захватывала область декорации.
> 
> ![изображение](https://user-images.githubusercontent.com/11896251/200055452-5f2cf821-dd73-44b9-93d0-ce04a3454008.png)

К сожалению, такое не получится сделать.

**Comment by tormozit** [comment]
> Заменил обычные пробелы на неразрывные и добавил расчет отступа

Проверил. Работает.

![изображение](https://user-images.githubusercontent.com/11896251/200128595-b732377d-6caa-4fb3-8571-609f81ff3554.png)
