### ISSUE TITLE
Добавить отображение в контекстной подсказке процедур объявленных в поле редактора

### ISSUE THREAD

**Issue by LevkinSergey** [salexdv/bsl_console#299]
![Peek 2022-11-12 21-00](https://user-images.githubusercontent.com/36307272/201488223-921e6e74-8db7-422b-85d9-1f73d0fa01cc.gif)

**Comment by LevkinSergey** [comment]
спасибо. 
Есть ли возможность слить изменения в ветку webpack?

**Comment by salexdv** [comment]
> спасибо. Есть ли возможность слить изменения в ветку webpack?

Да, сделаю в ближайшее время

**Comment by LevkinSergey** [comment]
> Да, сделаю в ближайшее время

Отлично

**Comment by salexdv** [comment]
> > Да, сделаю в ближайшее время
> 
> Отлично

@LevkinSergey Ближайшее время наконец настало )) Перенес всё в ветку webpack

**Comment by LevkinSergey** [comment]
@salexdv Отличная новость. Спасибо
