### ISSUE TITLE
Метод setContent генерирует событие EVENT_CONTENT_CHANGED

### ISSUE THREAD

**Issue by stolya** [salexdv/bsl_console#302]
Согласно описанию вызов метода должен не генерировать событие EVENT_CONTENT_CHANGED.
![image](https://user-images.githubusercontent.com/30523530/202556133-11c067c7-86fc-42a3-aa67-9e29149d3d1a.png)
![image](https://user-images.githubusercontent.com/30523530/202556292-4b2f4426-7e0a-431e-96c2-d9b2e1c2848b.png)

**Comment by salexdv** [comment]
Вызов `setContent` не генерирует указанное событие. Возможно, дело в чём-то другом. Можете показать код `SetContentBSL`?

**Comment by stolya** [comment]
![image](https://user-images.githubusercontent.com/30523530/206004217-c6da9c84-c0a4-41da-bd48-b9d43da20fbc.png)

**Comment by salexdv** [comment]
Такая проблема действительно наблюдается в старых версиях редактора. Если взять последние исходники, то генерации события происходить не будет.

**Comment by stolya** [comment]
Проблема воспроизводится на релизной версии 0.3.3 от 14.10.2022
![image](https://user-images.githubusercontent.com/30523530/206920072-4b157031-5c0e-49a4-acf1-f689ee1ef0df.png)

**Comment by salexdv** [comment]
Возьмите последние исходники из ветки develop, там такой проблемы нет.
