### ISSUE TITLE
Сайт paste1c.ru: возможность экспортировать все свои шаблоны в файл / в строку ЖСОН

### ISSUE THREAD

**Issue by john-doe-1c** [salexdv/bsl_console#308]
Добавил несколько своих шаблонов кода на сайт. В личном кабинете я вижу их список.

Хочу иметь возможность в один клик экспортировать все свое добавленное добро с сайта в файл-бекап (предположительно ЖСОН-массив структур - заголовок, описание, собственно тело кода).

Отсутствие такой возможности (по крайней мере для меня) - это основной сдерживающий фактор к тому, чтоб начать пополнять базу своих шаблонов там.

**Comment by salexdv** [comment]
Добавлю возможность экпорта

**Comment by salexdv** [comment]
@john-doe-1c, экспорт добавил
![paste1c_export](https://user-images.githubusercontent.com/6356534/227611504-f1202150-9ddf-49ab-ae11-2cc5e982360f.png)

**Comment by john-doe-1c** [comment]
Работает, спасибо!
