### ISSUE TITLE
Сайт paste1c.ru: возможность создавать многострочные описания при ручном наборе текста

### ISSUE THREAD

**Issue by john-doe-1c** [salexdv/bsl_console#309]
Сейчас при нажатии Ентер в поле ввода описания (текста) происходит публикация (создание / обновление) шаблона, что лишает меня возможности написать там многострочный текст.
При этом туда можно вставить многострочный текст из буфера обмена и такое описание в дальнейшем будет работать (показываться в многострочном режиме).

Хочу чтоб нажатие Ентер не публиковало шаблон кода, а переносило каретку в новую строку.
А публикацию шаблона можно переназначить, например, на Цтрл+Ентер.

В некоторых программах перенос каретки сделан через Шифт+Ентер, но это менее предпочтительный для меня вариант.
Если категорично не хочешь отнимать у "обычного" Ентера функцию публикации шаблона, то желательно сделать это сочетание настраиваемым:
- кто-то поставит себе обычный Ентер для публикации (как это сейчас и происходит), а Шифт+Ентер для переноса каретки
- кто-то поставит себе обычный Ентер для переноса каретки, а публикацию через Цтрл+Ентер

.

**Comment by salexdv** [comment]
@john-doe-1c, переделал на Ctrl+Enter

**Comment by john-doe-1c** [comment]
Работает, спасибо! Предлагаю еще добавить всплывашку для зеленой кнопки "Обновить" (и "Поделиться") с новым сочетанием.

**Comment by salexdv** [comment]
Что за всплывашка?

**Comment by john-doe-1c** [comment]
Всплывающая подсказка при наведении мышки. Чтоб у пользователя была возможность узнать, что у этой кнопки есть клавиатурный аналог.

**Comment by salexdv** [comment]
Сделал
