### ISSUE TITLE
Сайт paste1c.ru: поддержать многострочные описания в списке публикаций в личном кабинете

### ISSUE THREAD

**Issue by john-doe-1c** [salexdv/bsl_console#310]
Захожу в https://paste1c.ru/profile и вижу там описания публикаций без перевода строк, а хочется и там видеть их с переводом строк.
Пример: https://paste1c.ru/2fo3j50eta6r
![image](https://user-images.githubusercontent.com/75837433/227757351-f1370a36-f675-49b8-972f-f5ef36c8b41f.png)

**Comment by salexdv** [comment]
Доработал
![image](https://user-images.githubusercontent.com/6356534/228453605-97638704-0778-4c4d-942a-5c8681279b6a.png)

**Comment by john-doe-1c** [comment]
Проверил, работает, спасибо!
