### ISSUE TITLE
Сайт paste1c.ru: слишком маленькое поле ввода текста описания публикации

### ISSUE THREAD

**Issue by john-doe-1c** [salexdv/bsl_console#311]
Сейчас туда по высоте влезает только 3 строки.
Можно сделать чтобы высота сама увеличивалась при ручном наборе (и при вставке туда из буфера) длинных текстов?
Если это сложно или долго, то хотя бы просто увеличить ее до, скажем, 10 строк.

P.S. Ширина тоже всего 70 символов - хотелось бы 120 там иметь.

**Comment by john-doe-1c** [comment]
В идеале хочется такое поведение:
- если описание и код вместе влезают по высоте на мой экран, то не обрезать ни тот, ни другой, вертикального скролла нет, поля занимают по высоте столько сколько нужно по содержимому
- если не влезают вместе, то приоритет отдается коду, описание занимает не больше трети или даже четверти от общей высоты экрана

**Comment by salexdv** [comment]
Добавил изменение высоты описания

**Comment by john-doe-1c** [comment]
Нужно растягивать поле вручную каждый раз при публикации новых (или обновлении существующих) материалов?

**Comment by salexdv** [comment]
Доработал, теперь не нужно

**Comment by john-doe-1c** [comment]
А как это должно выглядеть? Я пока не смог ощутить какого-то эффекта.
У меня результат растягивания (большая высота поля) сохраняется только пока я нахожусь в рамках одной и той же публикации.
Стоит мне перейти по ссылке к другой публикации (или на главную страницу), то по зеленой кнопке ("Поделиться" / "Обновить") поле под описание снова отображается маленьким (две строки текста в высоту).

**Comment by salexdv** [comment]
> А как это должно выглядеть? Я пока не смог ощутить какого-то эффекта. У меня результат растягивания (большая высота поля) сохраняется только пока я нахожусь в рамках одной и той же публикации. Стоит мне перейти по ссылке к другой публикации (или на главную страницу), то по зеленой кнопке ("Поделиться" / "Обновить") поле под описание снова отображается маленьким (две строки текста в высоту).

Поле описания изменяет размер либо при печати, либо при вставке текста. Если текст в поле уже есть, то размер тоже подстраивается
![chrome_TBurj6Xr9w](https://user-images.githubusercontent.com/6356534/229842722-6a0d3d5b-b932-4009-9d33-44ee1ca7429d.gif)

**Comment by john-doe-1c** [comment]
Я пробовал вводить многострочный текст вручную и поле не растягивалось само. Проверил сейчас еще раз - теперь растягивается, спасибо!
P.S. Видимо изменения в коде сайта не сразу доходят до моего клиента (браузера). Я могу как-то вручную инициировать "применение" у себя в браузере этих "обновлений"?

**Comment by salexdv** [comment]
> Я могу как-то вручную инициировать "применение" у себя в браузере этих "обновлений"?

Изменения сами должны подтянуться. Если этого не произошло, можно обновить страницу через Ctrl+F5
