### ISSUE TITLE
Сайт paste1c.ru: показывать заголовок и описание у публикаций

### ISSUE THREAD

**Issue by john-doe-1c** [salexdv/bsl_console#312]
Я создал публикацию и поделился с кем-нибудь ссылкой, например: https://paste1c.ru/2fo3j50eta6r

Тот кто откроет ссылку увидит только сам код 1С, но не увидит заголовка и описания моей публикации (заголовок лишь частично будет виден на вкладке браузера).

Сейчас видимо только через зеленую кнопку "Поделиться" можно посмотреть загловок и описание, но читатель (любой кому я отправил ссылку) вряд ли когда-либо додумается или захочет нажимать эту кнопку.

Как насчет отображения заголовка публикации и ее описания всегда вместе с кодом (т.е. сразу и на той же странице)?

**Comment by salexdv** [comment]
Подумаю, как это лучше сделать

**Comment by salexdv** [comment]
Не очень хочется добавлять "лишние" элементы и загромождать страницу, поэтому для просмотра описания добавил вот такую кнопку
![image](https://user-images.githubusercontent.com/6356534/229043809-90ccfd25-b484-4996-b115-68ab020cd997.png)
Описание раскрывается при нажатии
![image](https://user-images.githubusercontent.com/6356534/229044022-c421a7a9-096b-4992-8e9b-3a4bb8698c5d.png)
Заголовок выводить пока не стал, если очень надо, добавлю

**Comment by john-doe-1c** [comment]
Предлагаю на кнопке разместить текст "Показать описание" и сделать его пунктирным подчеркиванием (типа как гиперссылка, но прерывистая, это будет сигнализировать о том что что-то при нажатии произойдет).
Без этого боюсь что неподготовленный пользователь, который впервые открывает сниппет на этом сайте, не догадается туда нажать...

**Comment by salexdv** [comment]
Готово
