### ISSUE TITLE
Ошибка "Метод объекта не обнаружен (init)" в linux

### ISSUE THREAD

**Issue by pila86** [salexdv/bsl_console#313]
Обработка `console.epf` не работает в linux. Возникает ошибка 
```
Метод объекта не обнаружен (init)
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(376)}:View().init(Инфо.ВерсияПриложения);
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(108)}:ИнициализацияРедактора();
```
Может у кого-нибудь есть версия обработки для linux, был бы очень благодарен.
Кириллицы в пути нет. Пробовал на ubuntu 22.10 и debian 11.

**Comment by salexdv** [comment]
Чтобы работало в linux, нужно собрать исходники из [этой](https://github.com/salexdv/bsl_console/tree/webpack) ветки и заменить макет в обработке.

**Comment by pila86** [comment]
Вроде получилось, спасибо! Правда вот не с первого раза, npm там что-то ругался то на одно, то на другое. Ну с горем пополам вроде удалось собрать.
