### ISSUE TITLE
Сайт paste1c.ru: убрать ограничение на интенсивность редактирования (кол-во запросов к сайту) уже существующих публикаций

### ISSUE THREAD

**Issue by john-doe-1c** [salexdv/bsl_console#314]
На сайте есть какой-то лимит на кол-во запросов в единицу времени (2 раза в минуту?).

Для новых публикаций (зеленая кнопка "Поделиться") я это ограничение не замечаю.
Вероятно оно полезно, т.к. позволяет в случае чего защищаться от вандалов / вредителей.

А вот _при редактировании_ уже существующих сниппетов - через зеленую кнопку "Обновить" - я постоянно натыкаюсь на этот лимит, когда "по горячим следам" многократно правлю один и тот же сниппет (код и/или описание).
Можно ли для сценария обновления отключить этот лимит или хотя бы смягчить до значения "1 запрос в 10 секунд"?

**Comment by salexdv** [comment]
Сделаю

**Comment by salexdv** [comment]
Готово
