### ISSUE TITLE
Предлагаю в демо обработку добавить простейший редактор запроса

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#317]
Пусть это будет кнопка, которая просто откроет отдельную форму с одним полем.
Это поможет быстро проверять оригинальное поведение в языке запросов в форме 1С.

**Comment by salexdv** [comment]
Обработка, выкладываемая в релизах имеет такую функцию
![image](https://user-images.githubusercontent.com/6356534/231083835-d3d44751-1a10-443c-bf41-1718f41f1a12.png)

**Comment by tormozit** [comment]
Мне показалось нелогичным искать это в подменю "Примеры". Теперь моя проблема решена. Но возможно не только у меня возникнет подобная сложность.
