### ISSUE TITLE
Не видно факта принадлежности строки ";" выделенной области между запросами пакета

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#319]
Поэтому может казаться что возникает разрыв выделения

```
выбрать 1
ПОМЕСТИТЬ вт
ОБЪЕДИНИТЬ
ВЫБРАТЬ ""
  ; //аываыва
  ;
ВЫБРАТЬ 2
```

![изображение](https://user-images.githubusercontent.com/11896251/230763747-8766deac-bb0b-46b0-9d19-8276f5d03a82.png)

**Comment by salexdv** [comment]
Если честно, не очень понял в чем проблема. Можешь подробнее объяснить?

**Comment by tormozit** [comment]
Выделенная область не должна иметь разрывов. Отображается она так, как будто строка №6 не входит в нее. Хотелось бы чтобы в ней выделение тоже было видно. Это особенно важно, если такая строка находится с края выделенной области.

**Comment by salexdv** [comment]
Редактор не позволяет выделять декорации. [Вот](https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAIYAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2SXGsXzoBtNlUc7JzE2-DhoNDFBSkDmlgvjP1KVtLQwdHRjhIeDx49tkFMDLg8b1ZhKomfU-9w2kA_D3MW4_oNk7QIk1mQL85HKSYHkRp3QU9cYcXB43cuykA7hkX15yecdhCcufisaHuhSdCgJIRFeiTdDaFqPDRZYELSIMSCyWgPB_L52XaYR6_FUmpgVVHcNpTwBFUIlRFIaUn_TEu6YEgblbTvRXcvBlrecA2jjlvJnVdG0yN562AJIHaHzf2-CzPlIxoyOubONw4uXX-Rbv9PUTHJ868O-0O1T4U3DpyHNiSgD14B35WkWfCn95X5fPE1DZX6wI7rAfujs6zMODVe872i4hBe89ju3rGI56Qei9Z5nvtTwmXyjNw-7Yzw0qv55PI9AtBylNK1PG3IEJwxsSrtGoas3oS08UhNL1CCVMNXLq9ij509c-iRf8Ul7jHcGVFHr8vdRu6XSnagRQTtJGmqAP1aWLsSrjrZO6haSvq39ObNlFIc5UNxVK4vCW70RVTcucch7TdUoY1WIEkTIf40ZENiRcRePcssM2fTn-vK3w) пример.
Единственное решение, которое я вижу это немного поменять принцип индикации разделителей запросов. Можно делать индикацию не в существующей строке, а делать разрывы специальными виджетами, которые не являются строками, но как по мне никакой выгоды в этом нет, с учетом того, что скорее всего при такой реализации разделители не будут видны на карте кода
![image](https://user-images.githubusercontent.com/6356534/231079001-47ae7447-e276-4cd2-8c13-8cbd292c57b1.png)

**Comment by tormozit** [comment]
Может быть тебе попробовать самому менять цвет декорации в зависимости от ее принадлежности выделенному диапазону?

**Comment by salexdv** [comment]
> Может быть тебе попробовать самому менять цвет декорации в зависимости от ее принадлежности выделенному диапазону?

Сделал
