### ISSUE TITLE
Проблема сортировки двух типов слова "Новый" в списке автодополнения

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#323]
У слова "Новый" во встроенном языке есть оператор и функция. 
```
Синтаксис (вариант 1):
Новый <Идентификатор типа>[(<Парам1>, <Парам2>, …)]
Синтаксис (вариант 2):
Новый(<Тип>[, <ПараметрыКонструктора>])
```
Поэтому я добавляю их оба в список доступных слов.
Но редактор кода в своем списке автодополнения всегда ставит функцию Новый() на первое место, хотя применяется она значительно реже оператора Новый. Хотелось бы на первое место поставить оператор.

Аналогичная проблема со словом "ВызватьИсключение".

Кстати, в родном списке доступных слов редактора отсутствует функция Новый(). Также и в редакторе модуля конфигуратора. Из-за этого многие программисты не знают, что такая функция существует.

![изображение](https://user-images.githubusercontent.com/11896251/236110813-1d7105f0-720e-4886-91f4-a8c7ed0e7a84.png)

**Comment by salexdv** [comment]
На сортировку можно повлиять, передав поле [sort](https://github.com/salexdv/bsl_console/blob/develop/docs/custom_suggestions.md) в подсказки
Функцию добавлю

**Comment by tormozit** [comment]
Да. С указанием свойства "sort" получилось решить проблему пересечений конструкций и методов следующим образом
```
Если СтрокаСлова.ТипСлова = "Конструкция" Тогда
	ПодсказкаСлова.Вставить("sort", "-1");
КонецЕсли;
```
