### ISSUE TITLE
Можно ли сделать более умную подсветку текущей строки в правом окне сравнения?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#324]
Сравнил 2 текста. Активировал в левом окне строку, для которой есть пара в правом окне. При этом в правом окне активировалась строка с тем же номером. А хотелось бы, чтобы в правом окне активировалась строка соответствующая левой строке по содержанию.

![изображение](https://user-images.githubusercontent.com/11896251/236632235-68ff1b85-91a5-4e12-a621-7581c829a2c7.png)

[Clip_437223.txt](https://github.com/salexdv/bsl_console/files/11412644/Clip_437223.txt)
[Clip_437224.txt](https://github.com/salexdv/bsl_console/files/11412645/Clip_437224.txt)

**Comment by salexdv** [comment]
@tormozit, проверь, пожалуйста

**Comment by tormozit** [comment]
Проверил. Работает.
