### ISSUE TITLE
paste1c.ru Ошибка - Необходимо заполнить «Код:»

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#332]
Пытался поделиться таким кодом
```
// Выбирает в массив элементы коллекции произвольным условием.
// Параметры:
//   Коллекция - Коллекция - произвольная коллекция
//   ВычисляемоеУсловие - Строка - логическое выражение на встроенном языке, где параметр "Э" дает доступ к элементу коллекции
//   А - Произвольное - значение параметра "А" для использования в условии
//   Б - Произвольное - значение параметра "Б" для использования в условии
//   В - Произвольное - значение параметра "В" для использования в условии
// При малом числе элементов заметно медленнее чем статический код. При 100 элементах сопоставима по скрорости с ним. При большем числе элементо даже быстрее него.
// Пример: ОтобратьКоллекциюВыражениемЛкс(Коллекция, "Э<>1 И Э<>А",, Среднее)
// Возвращаемое значение:
//   Массив - элементов коллекции
Функция ОтобратьКоллекциюУсловиемЛкс(Коллекция, ВычисляемоеУсловие, А = Неопределено, Б = Неопределено, В = Неопределено) Экспорт 
	Результат = Новый Массив;  
	_РежимОтладки = Ложь;
	Если _РежимОтладки Тогда // Можно менять на Истина в точке останова, например условием ирОбщий.ПрЛкс(_РежимОтладки, 1, 1)     
		Для Каждого Э Из Коллекция Цикл
			//Если Э <> 0 Тогда // Для сравнения скорости со статическим кодом
			Если Вычислить(ВычисляемоеУсловие) Тогда
				Результат.Добавить(Э);
			КонецЕсли; 
		КонецЦикла;
	Иначе
		// быстрый вариант
		Выполнить("
		|Для Каждого Э Из Коллекция Цикл
		|	Если " + ВычисляемоеУсловие + " Тогда
		|		Результат.Добавить(Э);
		|	КонецЕсли; 
		|КонецЦикла;");
	КонецЕсли;
	Возврат Результат;
КонецФункции
```
Но получаю каждый раз ошибку 
`Необходимо заполнить «Код:»`
![изображение](https://github.com/salexdv/bsl_console/assets/11896251/dad383ce-3371-4ef9-bf9d-0ab426c8704c)

**Comment by salexdv** [comment]
На на скрине нет кода или это только первая строчка пустая?

**Comment by tormozit** [comment]
На картинке показано состояние программы сразу после нажатия кнопки "Поделиться" в окне "Публикация кода"

![изображение](https://github.com/salexdv/bsl_console/assets/11896251/4c3cc832-0a8c-4e47-807f-cf4c68f806ff)

**Comment by salexdv** [comment]
На скриншоте окно, в котором опционально можно ввести краткое наименование и более подробно описание, но самого кода не видно. Он заполнен?
![image](https://github.com/salexdv/bsl_console/assets/6356534/9ce4e987-37a5-484b-972e-9b30e5ce0a46)

**Comment by salexdv** [comment]
Это окно не для кода. Весь код пишется в редакторе.
![image](https://github.com/salexdv/bsl_console/assets/6356534/ae8400a3-d410-4a4f-9909-63b1ffc680ef)

**Comment by tormozit** [comment]
Да. Теперь получилось. Затупил я. Видимо сказался прошлый инцидент из-за которого я пробовал много всего необычного в этих окнах.
