### ISSUE TITLE
Добавить поддержку вложенных пользовательских объектов (типов)

### ISSUE THREAD

**Issue by ViktorErmakov** [salexdv/bsl_console#34]
Описывал впервые произвольный объект в метаданных, столкнулся с глюком.
У меня структура, которая в себе содержи тоже 2 структуры.
Если я без них делаю свою структуру с разными типами данных, все ок, 
но как только добавляю структуры, все ломается.
На видео постарался показать что именно происходит.
В файле прикладываю структуру, ее можно будет задействовать везде, там ссылок на объекты нет.

![Change](https://user-images.githubusercontent.com/39617680/99156671-cfba9a80-26d3-11eb-9820-03fe62e8bc35.gif)
[СоставСтруктуры.txt](https://github.com/salexdv/bsl_console/files/5541441/default.txt)

Может и я что не так делаю, но очень странное поведение.
Посмотри пожалуйста.

**Comment by salexdv** [comment]
> Описывал впервые произвольный объект в метаданных, столкнулся с глюком.
> У меня структура, которая в себе содержи тоже 2 структуры.

Объекты, вложенные в другие объекты в чистом виде не поддерживаются. Это можно решить выносом объекта "СостояниеОбменаДанными" в корень пользовательских объектов и уже потом ссылаться на него через ref: customObjects.СостояниеОбменаДанными

Еще одна проблема в том, что у вложенных структур не задано поле "name"

**Comment by ViktorErmakov** [comment]
Еще одна проблема в том, что у вложенных структур не задано поле "name" - ты имеешь ввиду что мне не нужно name задавать? или то что я где то не задал?
По первому абзацу не совсем понял, но попробую реализовать, спасибо

**Comment by salexdv** [comment]
> Еще одна проблема в том, что у вложенных структур не задано поле "name" - ты имеешь ввиду что мне не нужно name задавать? или то что я где то не задал?

Я говорю вот об этом
![name](https://user-images.githubusercontent.com/6356534/99184909-8dd33800-2757-11eb-96b0-ea5c387f7fa6.png)

**Comment by salexdv** [comment]
> По первому абзацу не совсем понял, но попробую реализовать, спасибо

Примерно так:
![name2](https://user-images.githubusercontent.com/6356534/99185007-10f48e00-2758-11eb-9f2f-f907a36a54dd.png)

**Comment by ViktorErmakov** [comment]
> 
> 
> > Еще одна проблема в том, что у вложенных структур не задано поле "name" - ты имеешь ввиду что мне не нужно name задавать? или то что я где то не задал?
> 
> Я говорю вот об этом
> ![name](https://user-images.githubusercontent.com/6356534/99184909-8dd33800-2757-11eb-96b0-ea5c387f7fa6.png)

Ты знаешь, я делал по подобию твоих примеров
![изображение](https://user-images.githubusercontent.com/39617680/99185736-d7725180-275c-11eb-8b56-ae3677d968ba.png)
Вот файлик тестов что ты делал, у тебя тоже у структуры нет имени, только ref и параметры

**Comment by salexdv** [comment]
> Ты знаешь, я делал по подобию твоих примеров

В моем примере, как и не скриншоте выше, нет поля **name** только у корневых объектов. Если мы говорим о свойствах объекта (properties), а в твоем случае, это именно так, то name должен быть обязательно

**Comment by ViktorErmakov** [comment]
я тебя понял, спасибо учту.
Я так понял ты что то будешь реализовывать, мне делать как ты сказал, или подождать?

**Comment by salexdv** [comment]
> я тебя понял, спасибо учту.
> Я так понял ты что то будешь реализовывать, мне делать как ты сказал, или подождать?

Лучше подождать т.к. вынос вложенного объекта в корень всё равно на 100% не решает задачу

**Comment by salexdv** [comment]
Реализовано [тут](https://github.com/salexdv/bsl_console/commit/e18dbb9900ebcbd2e4978b411d9b68ddec2efdaa). Пример в тестах.
