### ISSUE TITLE
Консоль не позволяет запускать функции?

### ISSUE THREAD

**Issue by sudomango** [salexdv/bsl_console#342]
При попытке запустить в консоли код с функцией или процедурой мгновенно выдаёт ошибку: "Ожидается последовательность операторов". Вопрос - что я делаю не так или это ограничение системы?

![Screen_01](https://github.com/salexdv/bsl_console/assets/147604070/31c2b353-ffb9-4102-965b-ac095bdaed70)

**Comment by salexdv** [comment]
Процедуры и функции не поддерживаются т.к. весь код запускается через `Выполнить(...)`
