### ISSUE TITLE
В режиме языка запросов подсказка удержания (HOVER) появляется только на первом символе слова

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#345]
На остальных символах она не появляется. На параметрах запроса вообще не появляется (например &Ссылка). 
В отладчике 1С проверил.
Событие EVENT_BEFORE_HOVER вызывается стабильно. Вызов метода setCustomHovers() - на любом символе слова передаются одинаковые параметры. Таким образом с моей стороны все стабильно.

https://github.com/salexdv/bsl_console/assets/11896251/229f54aa-5e5e-4875-91a8-098aa949abd9

Когда то это точно работало на любом символе слова.
В режиме встроенного языка проблемы нет. Подсказка всплывает на любом символе слова.

**Comment by tormozit** [comment]
Нашел в этом поведении некоторую пользу. Так подсказка работает менее назойливо. И если сразу знать что она так работает, то возможно даже эта польза (с учетом исправления ее всплытия на параметре запроса) перевесит неудобство от усложнения прицеливания. 

Но самому догадаться как ее вызывать - очень сложно. Тем более в других режимах редактора она работает на любом символе слова.

**Comment by salexdv** [comment]
Исправил

**Comment by tormozit** [comment]
Проверил. Теперь работает.
