### ISSUE TITLE
При сравнении текстов хочется видеть разницу в непечатных символах

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#350]
При сравнении текстов хочется **опционально** видеть разницу в непечатных символах.
https://github.com/salexdv/bsl_console/blob/develop/docs/compare.md

Пример

Текст1:
```
Функция ВывестиРезультатКомпоновки(Предмет, 
	ФиксированныйОтбор = Неопределено, 
		ПравилоОтбора = Неопределено)
```

Текст2:
```
Функция ВывестиРезультатКомпоновки(Предмет, 
		ФиксированныйОтбор = Неопределено, 
		ПравилоОтбора = Неопределено)
```

![изображение](https://github.com/salexdv/bsl_console/assets/11896251/50f3bf8a-6c3a-42d8-8822-09fb81cc632a)

**Comment by salexdv** [comment]
Посмотрю, как это можно реализовать

**Comment by salexdv** [comment]
@tormozit , попробуй при создании редактора сравнения добавить опцию `ignoreTrimWhitespace: false`
![image](https://github.com/user-attachments/assets/489cf158-8d7d-478b-bf57-02b2a3cd5b19)

**Comment by tormozit** [comment]
Проверил так
```
	РедакторHTML = ЭлементыФормы.РедакторHTML.Документ.defaultView;
	РедакторHTML.init(Инфо.ВерсияПриложения);
	РедакторHTML.setOption("disableNativeHovers", Истина);
	РедакторHTML.setOption("ignoreTrimWhitespace", Ложь);
	РедакторHTML.updateText(Текст1);
```
Поведение не изменилось.

**Comment by salexdv** [comment]
> Проверил так

Так ничего не изменится. Это не опция обычного редактора, а опция редактора в режиме сравнения. Это только в файле изменить и посмотреть. Если всё будет, как надо, тогда сделаю таким поведение по умолчанию.

**Comment by tormozit** [comment]
Так заработало
```
     editor = monaco.editor.createDiffEditor(document.getElementById("container"), {
        theme: currentTheme,
        language: language_id,
        contextmenu: false,
        automaticLayout: true,
        scrollBeyondLastLine: false,
        renderSideBySide: sideBySide,
        ignoreTrimWhitespace: false,
```

**Comment by tormozit** [comment]
Включать этот режим по умолчанию не стоит. Вот пример почему 

![изображение](https://github.com/user-attachments/assets/2d629743-e915-4064-8b88-f7c5d6503bad)

Нужен именно переключатель этого режима в API, чтобы аналогично другим подобным сравнилкам включать его когда нужно будет. Поэтому я изначально именно опцию просил.
