### ISSUE TITLE
Переключить в режим редактирования запроса очищает код

### ISSUE THREAD

**Issue by Murenysh** [salexdv/bsl_console#36]
При переключении в режим редактирования запроса появляется вопрос:
При переключении в режим запроса текущий код будет очищен. Все равно продолжить?

Даже если ответить Нет,  код очищается.

**Comment by salexdv** [comment]
> Даже если ответить Нет, код очищается.

Проверю

**Comment by salexdv** [comment]
Исправлено в релизе [v0.2.2](https://github.com/salexdv/bsl_console/releases/tag/v0.2.2)
