### ISSUE TITLE
Реализовать программный интерфейс объектов ПолеТекстовогоДокумента и ТекстовыйДокумент

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#37]
Для того, чтобы этот объект можно было просто примерять/применять в существующих редакторах кода в формах 1С предлагаю реализовать соответствующие часто используемые их свойство и методы (по убыванию моей частоты)
- свойство ВыделенныйТекст (SelectedText) чтение и запись
- метод ПолучитьГраницыВыделения (GetTextSelectionBounds)
- метод УстановитьГраницыВыделения (SetTextSelectionBounds) 2 сигнатуры 
- метод КоличествоСтрок (LineCount)
- метод ПолучитьСтроку (GetLine)
- метод ЗаменитьСтроку (ReplaceLine)
Тогда можно будет минимальными изменениями существующем коде подключить твой редактор и оценить его пригодность для применения в конкретных условиях.

**Comment by salexdv** [comment]
> Для того, чтобы этот объект можно было просто примерять/применять в существующих редакторах кода в формах 1С предлагаю реализовать соответствующие часто используемые их свойство и методы

Пока реализовал в dev-ветке. Названия функций не совпадают с названиями из 1С.
| Функция                        | Описание                                                                                           |
| ------------------------------ | -------------------------------------------------------------------------------------------------- |
| `selectedText(text)`           | функция без параметров возвращает выделенный текст, с параметром - устанавливает                   |
| `getSelection()`               | возвращает [selection](https://microsoft.github.io/monaco-editor/api/classes/monaco.selection.html), аналог GetTextSelectionBounds|
| `setSelectionByLength()`       | устанавливает выделение, аналог первой сигнатуры SetTextSelectionBounds                            |
| `setSelection()`               | устанавливает выделение, аналог второй сигнатуры SetTextSelectionBounds                            |
| `getLineCount()`               | возвращает количество строк                                                                        |
| `getLineContent()`             | возвращает содержимое строки по её номеру, аналог GetLine                                          |
| `setLineContent()`             | устанавливает содержимое строки по её номеру, аналог ReplaceLine                                   |
