### ISSUE TITLE
Есть желание использовать шаблон от павла чистова

### ISSUE THREAD

**Issue by VolAll** [salexdv/bsl_console#44]
есть набор шаблонов https://chistov.pro/utilities/st83/
Хотелось бы его использовать.

**Comment by salexdv** [comment]
> есть набор шаблонов https://chistov.pro/utilities/st83/
> Хотелось бы его использовать.

Постараюсь что-нибудь придумать

**Comment by salexdv** [comment]
Добавил возможность загружать стандартные шаблоны кода 1С:Предприятия из файлов с расширением *.st
Для загрузки необходимо в функцию [parseSnippets](https://github.com/salexdv/bsl_console/blob/develop/docs/parse_snippets.md) передать текстовое содержимое файла шаблонов.

**Comment by salexdv** [comment]
Описал особенности реализации в документации к функции.
