### ISSUE TITLE
Не вставляется текст из буфера обмена

### ISSUE THREAD

**Issue by BProg-Gladkov** [salexdv/bsl_console#46]
Не получается вставить код из конфигуратора в консоль.
Копирую код в конфигураторе в буфер обмена. Вставляю - не работает.

Код скопированный в консоли так же можно вставить только в консоли.
Платформа 1С:Предприятие 8.3 (8.3.17.1851),
Windows. RDP.

**Comment by Evg-lylyk** [comment]
Эта проблема обозначена в Известные проблемы: https://github.com/salexdv/bsl_console#%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B
Выход использовать более свежие версии платформы в т.ч. 17

**Comment by salexdv** [comment]
Проблема известная. В ближайшие дни выйдет новый релиз, при использовании которого в последних версиях платформы все будет нормально.

**Comment by salexdv** [comment]
На последних версиях платформы в релизе [0.2.5](https://github.com/salexdv/bsl_console/releases/tag/v0.2.5) всё должно работать
