### ISSUE TITLE
Метод объекта не обнаружен (clearMetadata) в версии 0.2.5 

### ISSUE THREAD

**Issue by badyanov** [salexdv/bsl_console#48]
Привет! У меня в версии 0.2.5 появилась ошибка!

При открытии внешней обработки возникает следующая ошибка:
```
Метод объекта не обнаружен (clearMetadata)
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(758)}:		View().clearMetadata();
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(768)}:	ОбнулитьМетаданные();	
{ВнешняяОбработка.КонсольКода.Форма.Форма.Форма(788)}:		ИнициализацияРедактора();
```
![image](https://user-images.githubusercontent.com/45713348/110615064-101eb680-81a4-11eb-82d7-eefa8959047d.png)

При этом все элементы на командной панели остаются неактивными, ничего не работает

Платформа 1С:Предприятие 8.3 (8.3.16.1148) х64 (клиент-сервер)

Но!!! на свежей версии платформы 1С:Предприятие 8.3 (8.3.18.1289) ошибка при открытии не воспроизводится. Но через некоторое время сама собой, без каких-либо действий, появляется другая ошибка:

![image](https://user-images.githubusercontent.com/45713348/110615943-06498300-81a5-11eb-8ed1-2232341ee54f.png)

**Comment by salexdv** [comment]
Попробуйте закрыть 1С:Предприятие, удалите из  %TEMP% каталог bsl_console и запустить консоль снова.

**Comment by salexdv** [comment]
Подскажите еще, в какой конфигурации запускаете?

**Comment by badyanov** [comment]
> Попробуйте закрыть 1С:Предприятие, удалите из %TEMP% каталог bsl_console и запустить консоль снова.

Да, это помогло! Ошибки исчезли. Большое спасибо! Значит, можно закрывать Issue?


> Подскажите еще, в какой конфигурации запускаете?


Конфигурация ERP 2.4.9.70

**Comment by salexdv** [comment]
> Конфигурация ERP 2.4.9.70

А планы счетов стандартные или есть добавленные вами?

**Comment by badyanov** [comment]
> А планы счетов стандартные или есть добавленные вами?

Планы счетов полностью стандартные. Но, не знаю, имеет ли это значение или нет. Рег. учет в базе не ведется и отключен в функциональных опциях
