### ISSUE TITLE
При вводе новой строки учитывать оступ предыдущей

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#49]
При вводе новой строки в КОДЕ если в начале есть символ "|" начинать строку с него. В коде и запросе при вводе новой строки новую начинать с отступа равного предыдущей строке, отступом считать табуляцию и пробел

**Comment by salexdv** [comment]
> В коде и запросе при вводе новой строки новую начинать с отступа равного предыдущей строке, отступом считать табуляцию и пробел

Это и сейчас [так](https://i.imgur.com/3WtfkBN.gif) работает.

**Comment by Evg-lylyk** [comment]
Здорово, может учесть |

**Comment by salexdv** [comment]
> Здорово, может учесть |

С этим поработаю

**Comment by Evg-lylyk** [comment]
Проверил, работает
