### ISSUE TITLE
Некорректное масштабирование html-элементов при изменении размера формы

### ISSUE THREAD

**Issue by johnnythefrog** [salexdv/bsl_console#53]
Добрый день!
Заметил, что при изменении размеров формы и в тонком, и в толстом клиенте не меняется размер div'а, который является контейнером для редактора, и некоторых его вложенных элементов.
Помогло изменение скрипта editor.js.
На строке 605 добавил automaticLayout: true
В результате вся страница корректно подстраивается под размер окна формы.

Вот как у меня теперь выглядит создание editor'а
`editor = monaco.editor.create(document.getElementById("container"), {
	theme: "bsl-white",
	value: getCode(),
	language: language.id,
	contextmenu: true,
	wordBasedSuggestions: false,
	customOptions: true,
	automaticLayout: true
});`

**Comment by salexdv** [comment]
Здравствуйте! Это не ошибка, а намеренное поведение, писал об этом [тут](https://github.com/salexdv/bsl_console/issues/27).
Сейчас в editor.js есть [вот такая](https://github.com/salexdv/bsl_console/blob/f1153d919512be9a62bcfd1a8e0a7c3522ee8bd8/src/editor.js#L604) опция, которую перед загрузкой исходников в поле HTML документа можно менять на свои опции, в том числе и automaticLayout
