### ISSUE TITLE
На платформах до 8.3.18 команды копировать/вставить работают только в пределах окна редактора

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#55]
Где подробнее почитать про эту проблему?

**Comment by salexdv** [comment]
> Где подробнее почитать про эту проблему?

Я не нашел упоминания этой проблемы в ошибках платформы. На данный момент проблема решена. На всех релизах, начиная, с ноября-декабря 2020 года всё должно работать.

**Comment by tormozit** [comment]
Мне в первую очередь не понятно, в чем заключается эта проблема. Прошу пояснений.

**Comment by salexdv** [comment]
> Мне в первую очередь не понятно, в чем заключается эта проблема. Прошу пояснений.

В поле HTML-документа почему-то просто не приходят нажатия Ctrl+C/Ctrl+V/Ctrl+Z, поэтому эти сочетания клавиш приходится переназначать своим командам внутри редактора, но из-за этого эти же команды не срабатывают к другом окне.  При переназначении штатный буфер никак не задействован, отсюда и такое поведение.

**Comment by tormozit** [comment]
Правильно я понял, что перехват сочетаний клавиш твоим полем HTML не позволяет копировать в буфер обмена путем нажатия CTRL+C в других элементах управления материнского окна (формы 1С), когда они имеют фокус ввода?

**Comment by salexdv** [comment]
> Правильно я понял, что перехват сочетаний клавиш твоим полем HTML не позволяет копировать в буфер обмена путем нажатия CTRL+C в других элементах управления материнского окна (формы 1С), когда они имеют фокус ввода?

Нет. Перехват влияет только на то, что скопированный из поля HTML-документа текст нельзя вставить в другой элемент/окно и наоборот - текст, скопированный из другого элемента/окна нельзя вставить в окно редактора (поле HTML-документа). Копирование между любыми другими окнами и элементами работает без проблем.

**Comment by tormozit** [comment]
Теперь понял. Ты просто сделал свой локальный буфер обмена в рамках поля HTML документа.

**Comment by salexdv** [comment]
Да, все так
