### ISSUE TITLE
Хочу частично свой механизм заполнения и обработки выбора элемента списка подсказки/автодополнения

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#56]
Как я это вижу?

Пользователь сдвинул текстовый курсор или нажал сочетание клавиш для принудительного показа списка автодополнения. Возникает событие BeforeShowAutocompleteList, которое можно обработать в модуле формы 1С и в каких то параметрах передать 
1. JSON список с атрибутами слов (по сути таблицу). Тут я буду передавать сформированный своей логикой список слов.
2. Признак отказа от штатного заполнения (можно отдельно для каждой категории слов передавать признаки)
3. Признак изменения текста с последнего вызова события

При выборе (ENTER) элемента списка возникает событие OnListItemSelect, которое можно обработать в модуле формы 1С и в каких то параметрах передать 
1. Признак отказа от штатной обработки
2. Выбранный элемент с доступом ко всем его атрибутам

Сделаешь такое?

**Comment by salexdv** [comment]
> Сделаешь такое?

Постараюсь реализовать

**Comment by tormozit** [comment]
Аналогичные возможности мне потребуются для подсказки по вызову метода. Причем у меня в текущем варианте там выводится довольно много информации https://www.hostedredmine.com/issues/926254 . В твоем классическом (компактном) варианте отображения ее всю невозможно уместить. Поэтому мне также потребуется еще и функция для получения абсолютных координат точки под текстовым курсором для возможности отобразить своим кодом 1С там свое окно.

**Comment by tormozit** [comment]
Еще мне нужно событие OnFirstActivateRow (ПриПервойАктивацииСтроки) для списка автодополнения с возможностью передать уточненное описание атрибутов текущего слова. Например слово - это функция модуля и для расчет типа ее результата может быть тяжелым - 100мс, поэтому сразу я не вычисляю тип результата для всех элементов списка, а лишь при активации строки слова.

**Comment by salexdv** [comment]
> Еще мне нужно событие OnFirstActivateRow (ПриПервойАктивацииСтроки) для списка автодополнения, которое можно обработать в модуле формы 1С и параметрами с возможностью передать уточненное описание атрибутов текущего слова. Например слово - это функция модуля и расчет типа ее результата может быть тяжелым - 100мс, поэтому сразу я не вычисляю тип результата для всех элементов списка, а лишь при активации строки слова.

Ох, вот это совсем непросто будет. Ничего подобного в API monaco нет. Я постараюсь что-нибудь придумать, но ничего не обещаю.

**Comment by salexdv** [comment]
> Еще мне нужно событие OnFirstActivateRow 

Добавил в ветку develop функцию, которая включает генерацию такого события. Описание функции [тут](https://github.com/salexdv/bsl_console/blob/develop/docs/activation_event.md).

**Comment by salexdv** [comment]
Реализовал следующие события:

* EVENT_ON_ACTIVATE_SUGGEST_ROW - при активации пункта в текущем списке подсказок [(подробнее)](https://github.com/salexdv/bsl_console/blob/develop/docs/activation_event.md)
* EVENT_BEFORE_SHOW_SUGGEST - перед появлением списка подсказок [(подробнее)](https://github.com/salexdv/bsl_console/blob/develop/docs/before_suggest_event.md)
* EVENT_ON_SELECT_SUGGEST_ROW - при выборе пункта из списка подсказок [(подробнее)](https://github.com/salexdv/bsl_console/blob/develop/docs/select_suggest_event.md)

Добавил функцию **hideSuggestionsList**, с помощью которой можно скрыть текущий список подсказок. Например, её можно вызывать после события EVENT_BEFORE_SHOW_SUGGEST 
Свои подсказки можно показывать [вот так](https://github.com/salexdv/bsl_console/blob/master/docs/custom_suggestions.md).

**Comment by salexdv** [comment]
@tormozit, проверял?

**Comment by tormozit** [comment]
В выходные планирую попробовать

**Comment by tormozit** [comment]
Последний релиз я вижу от 02.03.2021. Где брать версию с новыми событиями?

**Comment by tormozit** [comment]
У меня eventData1C всегда Неопределено, хотя enableBeforeShowSuggestEvent(Истина) я вызывал.

**Comment by tormozit** [comment]
В событии EVENT_BEFORE_SHOW_SUGGEST вижу список слов в свойстве rows. Но не могу понять как заменить его на свой список из массива.

**Comment by tormozit** [comment]
Получилось показать свой список автодополнения. Немного смущает, что сначала твой код проводит анализ текста, затем я не даю показаться результату этого анализа и запускаю свой анализ и показываю уже его результаты. Получается постоянные бесполезные вычисления в твоем коде.

**Comment by tormozit** [comment]
В целом все заработало. Мелочи остались в отдельных заявках.
