### ISSUE TITLE
Сборка с electron

### ISSUE THREAD

**Issue by SergeyDjam** [salexdv/bsl_console#6]
Добрый день. Хотел узнать, есть ли возможность собрать в отдельное приложение с помощью electron или иных упаковщиков?

Я попробовал упаковать electron-packager или electron-builder но на выходе ничего рабочего не выходит

**Comment by salexdv** [comment]
В теории, наверное, это возможно. Сам я с такими технологиями, к сожалению, никогда не работал, поэтому однозначно не отвечу, извините. Постараюсь вникнуть в вопрос. А что вы задумали, если не секрет? Насколько я понимаю electron тянет весь webkit с собой и nodejs и сборка получается весьма увесистая всегда.

**Comment by salexdv** [comment]
Попробовал [данный](https://github.com/Microsoft/monaco-editor-samples/tree/master/electron-amd) пример. Запускается, но [не работает](https://i.imgur.com/HIBe97o.png) как положено. Думаю, что запустить можно, но bsl_console всё таки надо будет менять в нескольких, а может и многих местах.

**Comment by SergeyDjam** [comment]
> В теории, наверное, это возможно. Сам я с такими технологиями, к сожалению, никогда не работал, поэтому однозначно не отвечу, извините. Постараюсь вникнуть в вопрос. А что вы задумали, если не секрет? Насколько я понимаю electron тянет весь webkit с собой и nodejs и сборка получается весьма увесистая всегда.

Хотелось собрать в отдельное приложение, которое можно было бы запустить независимо от наличия и версии браузера в системе. Мне кажется это удобным, хотя и увесистым.

**Comment by salexdv** [comment]
Я мог бы попробовать сделать это, когда доделаю основные вещи, которые намечены, хотя мне кажется более удачным вариант сделать сайт, где будет данный редактор и где можно будет делиться кодом. Возможно Инфостарт запустить что-то подобное т.к. они знают о данной идее.

**Comment by SergeyDjam** [comment]
Ок, это не срочно, скорее как идея... А может и вообще никому не нужно..
Спасибо за ответ
