### ISSUE TITLE
Как изменить размер шрифта и сам шрифт?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#60]
Как изменить размер шрифта и сам шрифт?
Нашел только это https://stackoverflow.com/questions/48934163/monaco-editor-set-font-size Но применить не смог

**Comment by salexdv** [comment]
> Как изменить размер шрифта и сам шрифт?

Размер можно изменить так: 
```js
editor.updateOptions({fontSize: '18px'});
```
Шрифт так:
```js
editor.updateOptions({fontFamily: 'Tahoma'});
```
Ну или всё вместе вызвать:
```js
editor.updateOptions({fontSize: '18px', fontFamily: 'Tahoma'});
```

**Comment by tormozit** [comment]
Попробовал, но изменилось ничего
```
РедакторHTML.editor.updateOptions("{fontSize: '10px', fontFamily: 'Tahoma'}")
РедакторHTML.editor.updateOptions("{fontSize: '18px', fontFamily: 'Tahoma'}")
```

**Comment by salexdv** [comment]
Добавил функции setFontSize и setFontFamily
Из 1С можно вызвать так:
```js
View().setFontSize(16);
```

**Comment by tormozit** [comment]
Заработало. Можно как то свой шрифт (файл ttf) подключить туда?  http://htmlbook.ru/blog/svoi-shrift-na-stranitse

**Comment by salexdv** [comment]
> Через функции функции setFontSize и setFontFamily заработало. Можно как то свой шрифт (файл ttf) подключить туда? http://htmlbook.ru/blog/svoi-shrift-na-stranitse

Простого способа добавить свой шрифт нет
