### ISSUE TITLE
Кнопкой "Закрыть" панель замены в тексте не закрывается и в обычном приложении 1С редактор начинает сильно грузить процессор

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#61]
8.3.18
Загрузка процессора воспроизводится только в обычном приложении и не воспроизводится в управляемом приложении даже в обычной форме. А не закрытие панели поиска и замены воспроизводится в обоих типах приложений 1С, но не воспроизводится в браузерах.

Нажать CTRL+H. Откроется панель замены в тексте. Нажать в ней крестик (кнопка "Закрыть"). При этом панель не закроется и процесс приложения 1С будет сильно грузить ядро процессора (какой то фоновый поток бесконечно что то вычисляет) пока не закроешь редактор.

Думаю причина нагрузки на процессор может быть в платформе 1С. Описал тут https://partners.v8.1c.ru/forum/t/1993617/m/1993617 . Но если решить проблему закрытия панели поиска и замены, то возможно удастся ее обойти.

[Консоль кода HTML.zip](https://github.com/salexdv/bsl_console/files/6413321/HTML.zip)
![изображение](https://user-images.githubusercontent.com/11896251/116843363-63cbe000-abe8-11eb-8cbb-4f29d1a47446.png)
![изображение](https://user-images.githubusercontent.com/11896251/116850490-6e42a580-abf9-11eb-9d98-437cf678c86b.png)
![изображение](https://user-images.githubusercontent.com/11896251/116852813-ad72f580-abfd-11eb-9b45-8a53890939f1.png)

**Comment by salexdv** [comment]
В ветке [develop](https://github.com/salexdv/bsl_console/tree/develop) добавлены методы openSearchWidget и closeSearchWidget. При желании их можно вызывать программно. Также реализовано принудительное закрытие панели поиска при нажатии на "крестик" и при нажатии Esc. С последним, правда, срабатывает только со второго раза. Проблема тут явно не редактора т.к. в браузере таких проблем нет совсем.

**Comment by tormozit** [comment]
Теперь панель кнопкой "Крестик" сразу закрывается. А клавишей ESC с первого раза залипает и ест процессор в обычном приложении как раньше, но зато теперь на второе нажатие этой же клавиши панель закрывается. Когда панель скрыта или открыта в нормальном режиме, то загрузки процессора нет. Можно сказать что проблема больше остро не стоит, т.к. большинство пользователей думаю сами догадаются второй раз ESC нажать. Но было бы идеально, если бы и клавишей ESC она с первого раз закрывалась.

![изображение](https://user-images.githubusercontent.com/11896251/117207790-08bf0680-adfd-11eb-831f-53a9aaa696fa.png)

**Comment by salexdv** [comment]
Тут сложность в том, что нажатие на Esc, когда курсор находится в окне поиска, не генерирует события onKeyDown и, соответственно, его нельзя перехватить. Второе нажатие уже нормально перехватывается и обрабатывается
