### ISSUE TITLE
Изменить цвет фона выделения текста

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#62]
Сейчас цвет фона выделения текста получается смещением обычного цвета фона и потому выделение слабо заметно (особенно когда редактор не в фокусе). Хочу сделать его более заметным, например желтым. Как это сделать? 
Темную тему не использую.
![изображение](https://user-images.githubusercontent.com/11896251/116786957-2f520a00-aaaa-11eb-8bcb-c713fea4e473.png)

**Comment by salexdv** [comment]
Цвет выделения можно настроить, изменив вот [этот](https://github.com/salexdv/bsl_console/blob/aed5b9e42ebf0716d556582b147b623d83dc5119/src/bsl_language.js#L89) параметр

**Comment by tormozit** [comment]
В последнем комите не понял - умышленно или нет, но цвет выделения стал оранжевым при наличии фокуса и остался светло синим при отсутствии фокуса. Думаю что пока по умолчанию лучше оставить старый цвет выделения, т.к. он был согласован с остальными цветами. И если менять, то надо менять оба этих цвета в паре. Кстати где второй цвет задается (без фокуса)?

![изображение](https://user-images.githubusercontent.com/11896251/117208494-dcf05080-adfd-11eb-9632-5449ad589754.png)

![изображение](https://user-images.githubusercontent.com/11896251/117208495-dcf05080-adfd-11eb-807f-2e9565c0e65d.png)

**Comment by salexdv** [comment]
> В последнем комите не понял - умышленно или нет, но цвет выделения стал оранжевым при наличии фокуса и остался светло синим при отсутствии фокуса. Думаю что пока по умолчанию лучше оставить старый цвет выделения, т.к. он был согласован с остальными цветами. И если менять, то надо менять оба этих цвета в паре. Кстати где второй цвет задается (без фокуса)?

Цвет был заменен умышленно, но описанного поведения я не наблюдаю. Выглядит вот так:

![editor](https://user-images.githubusercontent.com/6356534/119338491-bdc83e80-bc98-11eb-93fe-8c40915cf8ee.png)

**Comment by tormozit** [comment]
Ты показал в один момент времени поле HTML, имеющее фокус ввода и 2 одинаковых фрагмента внутри него. А же показал 2 снимка одного поля в разные моменты времени: один с фокусом ввода, а другой - без. 
![изображение](https://user-images.githubusercontent.com/11896251/119348794-033f3880-bca6-11eb-98b1-a7a7f67fce94.png)

**Comment by tormozit** [comment]
Теперь цвет фона выделения во всех случаях стал согласованным - оттенки желтого.
