### ISSUE TITLE
Как правильно удалить описание языков платформы из редактора?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#63]
Мне по сути нужен редактор с подсветкой синтаксиса языков 1С, а анализировать текст и наполнять доступные методы, свойства, параметры я хочу сам. В связи с этим хочется полностью удалить штатную аналогичную информацию из редактора.
Я попробовал заменить содержимое файла bslGlobals.js на
```
define([], function () {
    bslGlobals = {
	"functions":{},
	"values":{}
	}
});
```
и на 
```
define([], function () {
    bslGlobals = {}
});
```
После чего у меня список подсказки стал выглядеть так 
![изображение](https://user-images.githubusercontent.com/11896251/116788247-3c262c00-aab1-11eb-8db3-1d1096300c33.png)
Есть сомнения что я правильно решил задачу.

**Comment by tormozit** [comment]
Оказалось что и без удаления описания языков - событие EVENT_BEFORE_SHOW_SUGGEST не вызывается.

**Comment by salexdv** [comment]
Тут возможны косяки т.к. изначально не было такой задумки. Для начала можно сделать следующее:
1. Изменить editor.js и убрать из загрузки лишние модули
![editor](https://user-images.githubusercontent.com/6356534/116966586-369b3280-acb9-11eb-934a-b868ef185d14.png)
2. Изменить bsl_language.js и заменить все провайдеры на пустые
![bsl_language](https://user-images.githubusercontent.com/6356534/116966640-516da700-acb9-11eb-9561-8c4cdafabc23.png)
Но тут надо быть осторожным. Например, completionProvider для bsl просто так заменить на пустой не получится т.к. там генерируется событие EVENT_BEFORE_SHOW_SUGGEST, которое тебе нужно, поэтому надо удалить только вызовы класса bslHelper. Если нужно сворачивание блоков кода, то лучше не трогать foldingProvider

**Comment by Evg-lylyk** [comment]
Поддержу, функция не грузить bslGlobals.js нужна

**Comment by tormozit** [comment]
На текущий момент у меня отпала потребность в запрошенной здесь возможности.
