### ISSUE TITLE
Функция selectedText(НовыйТекст) после замены выделенного текста оставляет его выделенным

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#64]
Подавляющее большинство текстовых редакторов снимают выделение после вставки (замены выделенного) текста. Присвоение значения свойству ВыделенныйТекст по сути и есть вставка текста. ПолеТекстовогоДокумента также снимает выделение после присвоения значения свойству ВыделенныйТекст. Причем границы выделения схлопываются на дальний край бывшего выделения. Прошу в метод selectedText добавить параметр, который позволит включать сохранение выделения после вставки, но по умолчанию он должен быть Ложь.

**Comment by salexdv** [comment]
Добавил дополнительный параметр и [описание](https://github.com/salexdv/bsl_console/blob/develop/docs/selected_text.md) функции

**Comment by tormozit** [comment]
Заработало
