### ISSUE TITLE
Нужно зафиксировать левую служебную вертикальную область с номерами строк

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#67]
Сейчас она уходит из области видимости при прокрутке вбок. В большинстве нормальных редакторов она остается всегда видимой (фиксированной).
![изображение](https://user-images.githubusercontent.com/11896251/116796950-46fcb300-aae9-11eb-8aab-e107781a4154.png)

**Comment by salexdv** [comment]
Это проблема не редактора, а поля HTML-документа в 1С. Попробуйте сразу после инициализации редактора вызывать
```js
View.hideScrollX()
```

**Comment by tormozit** [comment]
Да. Я эту заявку открыл еще до разбора ситуации с наличием полос прокрутки внутренних и внешних. После ее https://github.com/salexdv/bsl_console/issues/80 решения проблема из текущей заявки стала неактуальной.
