### ISSUE TITLE
Как показать неотфильтрованный список автодополнения?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#73]
Хочу иногда показывать пользователю полный список, как это делает конфигуратор - без фильтрации и в алфавитном порядке. Это полезно для 
- быстрой замены слова на соседа из полного списка (например значения перечисления)
- ранее пользователь ошибся и выбрал соседа вместо правильного слова, а теперь хочет исправить свой выбор
- переименовали окончание слова вне редактора и теперь нужно заменить его на новое слово

Если же в твоей подсказке я вызываю ее справа от какого то слова, то при отображении списка он всегда фильтруется по этому слову. 
Как вариант можно сделать при открытом списке подсказки при нажатии CTRL+ALT+SPACE переключить формирование списка в режим "без фильтрации". Удобнее было бы повесить это на нажатие CTRL+SPACE, но на нем сейчас находится переключение отображения свойств слова.

![изображение](https://user-images.githubusercontent.com/11896251/116810185-f4ec7980-ab4a-11eb-9f03-fe721180d793.png)

**Comment by tormozit** [comment]
Покрыл эту потребность своим окном автодополнения https://www.hostedredmine.com/issues/929249

**Comment by salexdv** [comment]
Добавил пару необязательных полей для передачи в [`showCustomSuggestions`](https://github.com/salexdv/bsl_console/blob/develop/docs/custom_suggestions.md). На примере, показанном выше можно попробовать передать для всех элементов списка одинаковое поле `"filter":"ТаблицаЗначений"`. При этом может сломаться нормальная фильтрация при наборе слова на клавиатуре, но стрелками мышкой выбрать можно будет любой элемент. Это всё теория. Насколько это будет удобно на практике сказать пока не могу.

**Comment by salexdv** [comment]
Пробовал предложенный способ?

**Comment by tormozit** [comment]
Пока не пробовал. Не понял, будет ли он активировать сразу ту строку, списка, слово которой сейчас написано в тексте.

**Comment by salexdv** [comment]
> Пока не пробовал. Не понял, будет ли он активировать сразу ту строку списка, слово которой сейчас написано в тексте (слева от каретки). Если не будет, то смысла в таком способе не вижу.

Нет, не будет. Редактор не позволяет сделать такое
