### ISSUE TITLE
Нежелательная особая раскраска обратного слэша в строковом литерале

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#74]
Обратный слэш с последующим символом сейчас красится особым цветом. В моем случае это даже полезно, но в общем подозреваю, что это - не задуманное поведение, а не отключенная логика от другого языка.
```
СтрокаПрограммы = """(?:(?:"""")|[^""\n])*(?:(?://[^\n]*\n|\s|^|$)*\|(?:(?:"""")|[^""\n])*)*(?:""|$)";
Имя = "[_ЁА-ЯA-Z][_ЁА-ЯA-Z\d]*";
Разделитель = "(?://[^\n]*\n|\s|^|$)";
БлокКомментариев = "(?:(?:\t| )*//[^\n]*\n)+(?:(?:\t| )*(?:\r|$))+";
```
![изображение](https://user-images.githubusercontent.com/11896251/116810643-9a085180-ab4d-11eb-80d0-aee064ce8289.png)

**Comment by tormozit** [comment]
Вот и пример того, где это откровенно вредно
`ИмяФайла = "C:\TerminalDisk\Журнал регистрации1.lgf";`
![изображение](https://user-images.githubusercontent.com/11896251/116821580-2719cd80-ab83-11eb-9f17-715191d75f79.png)

**Comment by tormozit** [comment]
В последнем комите проблема все еще присутствует.

**Comment by salexdv** [comment]
Попробуй сейчас

**Comment by tormozit** [comment]
Заработало
