### ISSUE TITLE
Не вижу добавленных пунктов контекстного меню редактора

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#76]
8.3.18
Пробовал в обычной и управляемой формах. В своей форме и в твоей форме.  В обычной форме вижу стандартное контекстное меню, куда я могу штатными средствами платформы добавлять пукнты
![изображение](https://user-images.githubusercontent.com/11896251/116811713-5dd7ef80-ab53-11eb-87ac-9428a11f5ccf.png)
А в управляемой форме оно вообще не открывается (пробовал в твоей внешней обработке).
Ниже код
```
	Инфо = Новый СистемнаяИнформация();
	View().init(Инфо.ВерсияПриложения);
	View().minimap(Ложь);
	View().addContextMenuItem("Конструктор форматной строки...", "EVENT_FORMAT_CONSTRUCT");
```
Что нужно сделать, чтобы собственное контекстное меню редактора открылось?

**Comment by Evg-lylyk** [comment]
Приветствую, нужно отключить автозаполнение контексного меню, программнл это не сделать

**Comment by salexdv** [comment]
Всё так, нужно снять галочку у контекстного меню
![context_menu](https://user-images.githubusercontent.com/6356534/117028703-9ec43580-ad06-11eb-8a6c-34da6a84184f.png)

**Comment by tormozit** [comment]
Так у меня галочка и не стоит. Я твою внешнюю обработку использовал для проверки. Платформа 8.3.18.1334 толстый клиент.

**Comment by salexdv** [comment]
Видимо это глюк платформы. Перепробовал разные варианты в толстом клиенте, ничего не сработало. Тогда выход только один, делать свое контекстное 1С-ное меню и дублировать в нем команды редактора.
