### ISSUE TITLE
Как показать свою подсказку при наведении указателя мыши на выражение в тексте программы?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#77]
Не нашел примера и описания использования метода setCustomHovers . Но подозреваю он - не совсем то, что нужно. Вычислять сразу все возможные выражения в тексте - слишком затратно. Мне нужно событие ПриНаведенииУказателяМыши и функция для отображения текста рядом с текущим выражением. Например в коде
![изображение](https://user-images.githubusercontent.com/11896251/116920330-2b191e80-ac5b-11eb-8e29-e0a760692617.png) 
при удержании указателя на последнем слове выражения "ВычислительРегулярныхВыражений.CurrentDirectory" я буду вычислять значение этого выражения и отображать результат в подсказке также как это делает конфигуратор например.

**Comment by tormozit** [comment]
Путем изучения исходников выяснил, что в метод нужно передавать сериализованную структуру (Ключ:Значение).  Заработало.
Но с одним именем в коде может быть и метод и конструктор и переменная, т.е. нужно все таки сделать подсказку с учетом типа слова. Самое распространенное перекрытие методом во встроенном языке - функция глобального контекста "Строка" перекрывает переменную/параметр "Строка". А про перекрытия конструкторами - так это вообще очень часто встречается в коде, например
![изображение](https://user-images.githubusercontent.com/11896251/116919477-fce70f00-ac59-11eb-86c8-c45d43245159.png)

**Comment by salexdv** [comment]
1. Приоритет у пользовательских подсказок повысил
2. Добавил генерацию [события](https://github.com/salexdv/bsl_console/blob/develop/docs/before_hover_event.md) перед показом всплывающей подсказки
3. Добавил функцию **hideHoverList**, вызвав которую можно скрыть текущую всплывающую подсказку

Теперь при возникновении события **EVENT_BEFORE_HOVER** можно в 1С сформировать подсказку и передать её в **setCustomHovers**

**Comment by tormozit** [comment]
Есть еще небольшое неудобство в том, что после появления окна подсказки удержания оно не скрывается автоматически пока курсор не отведешь на 10 пикселей от границы окна 
![изображение](https://user-images.githubusercontent.com/11896251/117536951-b7826300-b006-11eb-9c57-725042bea0e7.png)
Из-за этого, если на имени функции появилась такая подсказка, то перемещение курсора вправо на один из ее параметров не вызывает подсказку удержания заново. Приходится довольно сильно уводить курсор вверх и затем возвращать его вниз на параметр.

**Comment by tormozit** [comment]
Добавил в свою консоль кода фичу https://www.hostedredmine.com/issues/927423 на базе твоей фичи

**Comment by tormozit** [comment]
Еще бы хотелось чтобы перенос строки работал в тексте этой подсказки. Сейчас он заменяется на пробел. Я хочу в некоторых случаях выводить часть текста подсказки с новой строки для облегчения его обнаружения.
