### ISSUE TITLE
Не получается обновить описание типа значения свойства в событии EVENT_ON_ACTIVATE_SUGGEST_ROW

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#78]
В событии EVENT_ON_ACTIVATE_SUGGEST_ROW не нашел параметра, откуда взять чистое слово активной строки списка подсказки. Пришлось в расширенном режиме списка брать через парсинг свойства "focused".
`ирОбщий.СтрокаМеждуМаркерамиЛкс(Событие.params.focused, "Элемент ", ",")`.  Кстати не понял от чего зависит, придет в параметрах события сокращенный список (без типов) или полный (с типами).
Хотелось бы более надежный и простой способ.

Также не понятно, как обновить описание (тип значения) в активной строке. Если заново весь список установить, то возникает много накладных расходов и теряется текущая позиция в списке. Хочется возможность обновить только описание слова активной строки списка подсказки. 
Если же точечное обновление сделать будет сложно, то нужно тогда хотя бы в методе showCustomSuggestions добавить параметр для передачи слова для восстановления текущей строки в списке автодополнения. Тогда для пользователя это проходить без дополнительных неудобств, не считая задержки на обновление списка целиком.

**Comment by salexdv** [comment]
> Пришлось в расширенном режиме списка брать через парсинг свойства "focused".
> `ирОбщий.СтрокаМеждуМаркерамиЛкс(Событие.params.focused, "Элемент ", ",")`. Кстати не понял от чего зависит, придет в параметрах события сокращенный список (без типов) или полный (с типами).

Свойство **focused** как раз и содержит чистое слово т.е. название пункта при активации которого возникло событие.
Не понял, что ты имеешь ввиду под "сокращенный список (без типов) или полный (с типами)". Можешь подробнее пояснить, лучше с примерами?

**Comment by tormozit** [comment]
Некорректные значения в коллекции rows и других свойствах событий возникают иногда. Выглядит это так
![изображение](https://user-images.githubusercontent.com/11896251/117636431-75cdf580-b189-11eb-82c4-72b9fe98cae9.png)

**Comment by tormozit** [comment]
Главная задача актуальна - обновить описание (тип значения) в активной строке. Если заново весь список установить, то теряется текущая позиция в списке и возникает много накладных расходов. Хочется возможность обновить только описание слова активной строки списка подсказки.

**Comment by salexdv** [comment]
> Главная задача актуальна - обновить описание (тип значения) в активной строке.

Что такое "описание (тип значения)"? Выделенное красным?
![suggest](https://user-images.githubusercontent.com/6356534/118153744-e8a3ce80-b41e-11eb-9f73-a63e88b39a9b.png)

**Comment by tormozit** [comment]
Да

**Comment by salexdv** [comment]
> Некорректные значения в коллекции rows и других свойствах событий возникают иногда. Выглядит это так

Есть алгоритм воспроизведения? Никак не могу поймать такое поведение.

**Comment by tormozit** [comment]
> 
> 
> > Некорректные значения в коллекции rows и других свойствах событий возникают иногда. Выглядит это так
> 
> Есть алгоритм воспроизведения? Никак не могу поймать такое поведение.

Пока нет. Встречал раз 5. Продолжаю наблюдение.

**Comment by salexdv** [comment]
> > Главная задача актуальна - обновить описание (тип значения) в активной строке.
> 
> Что такое "описание (тип значения)"? Выделенное красным?
> 
> > Да

Добавить функцию, которая меняет заголовок пункта не проблема. Также просто можно изменить текст справа, до того как он раскрывается. Проблема в том, что когда ты нажимаешь "Подробнее...CTRL+Space" monaco откуда-то из внутренностей достает старый текст и показывает. Таким образом на момент срабатывания EVENT_ON_ACTIVATE_SUGGEST_ROW просто нечего менять т.к. в DOM-дереве просто нет элементов отвечающих за отображение. Сильно сомневаюсь, что есть способ добраться до "внутренностей" и поменять текст там. Единственный вариант тут, который я пока вижу, это генерировать какое-нибудь событие при нажатии "Подробнее", и уже при его наступлении менять текст. Получится примерно так. Сначала происходит EVENT_ON_ACTIVATE_SUGGEST_ROW, меняется текст справа, потом при вызове подробной подсказки происходит EVENT_ON_DETAIL_SUGGEST_ROW и еще раз заменяется текст на нужный.

**Comment by tormozit** [comment]
Нажатие "Подробнее" переключат видимость окна описания текущей строки списка. Если я его включил и перешел к следующей строке, то события EVENT_ON_DETAIL_SUGGEST_ROW  я уже не получу ?

**Comment by salexdv** [comment]
> Нажатие "Подробнее" переключат видимость окна описания текущей строки списка. Если я его включил и перешел к следующей строке, то события EVENT_ON_DETAIL_SUGGEST_ROW я уже не получу ?

Не получишь, но если ты включил видимость окна описания, то можно будет при EVENT_ON_ACTIVATE_SUGGEST_ROW менять состав описания. Его не получится менять только при первом EVENT_ON_ACTIVATE_SUGGEST_ROW, когда никакого окна с описанием еще нет.

**Comment by tormozit** [comment]
ОК. Давай пробовать. Вроде должно получиться.

**Comment by salexdv** [comment]
Добавил событие **EVENT_ON_DETAIL_SUGGEST_ROW**
Его параметры полностью совпадают вот с [этим](https://github.com/salexdv/bsl_console/blob/develop/docs/activation_event.md).

Добавил две функции:
1. `setActiveSuggestLabel`  - Устанавливает заголовок активного пункта списка подсказок
2. `setActiveSuggestDetail` - Устанавливает подробное описание активного пункта списка подсказок
Обе функции на вход принимают строку

**Comment by tormozit** [comment]
Заработало. При каждом вызове события EVENT_ON_DETAIL_SUGGEST_ROW вызываю setActiveSuggestDetail . Иначе при повторном вызове восстанавливается первоначально описание (детальная подсказка) слова.
