### ISSUE TITLE
Событие EVENT_ON_SELECT_SUGGEST_ROW не вызывается

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#79]
8.3.18 
Подключил событие этим кодом
`	View().enableSelectSuggestEvent(Истина);`
Выбрал из списка слово клавишей ENTER. Слово вставилось. При этом возникло только событие EVENT_CONTENT_CHANGED.
Воспроизводится в твоей внешней обработке.

**Comment by salexdv** [comment]
Исправил

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
Событие не вызывается при выборе элемента списка мышкой
![изображение](https://user-images.githubusercontent.com/11896251/117217644-60b03a00-ae0a-11eb-8eb8-d4161af951dd.png)

**Comment by salexdv** [comment]
> Событие не вызывается при выборе элемента списка кликом мышкой

Всё так. Пока только при выборе через Enter

**Comment by salexdv** [comment]
Доработал. При выборе элемента кликом мыши будет генерироваться событие. Осталось решить проблему с выбором через Tab

**Comment by tormozit** [comment]
Кажется вчера событие при выборе кликом работало. Сегодня не работает.

![изображение](https://user-images.githubusercontent.com/11896251/119725120-3a654380-be78-11eb-9a35-ceb48db0fc4e.png)

В этой ситуации если выбрать кликом слово "ДанныеЭлементаФормыЛкс", то сначала вызовется событие EVENT_ON_SELECT_SUGGEST_ROW  для активной строки списка, т.е. "ВычислитьХешЛкс". А затем уже без вызова события свежевставленная строка "ДанныеЭлементаФормыЛкс()" заменяется на строку "ДанныеЭлементаФормыЛкс".

**Comment by tormozit** [comment]
Почти заработало.
Сейчас при выборе кликом событие вызывается с передачей правильного слова.
![изображение](https://user-images.githubusercontent.com/11896251/119885050-fcc8ef00-bf39-11eb-8b21-8e74244a0d5b.png)
Я его обрабатываю и вставляю скобки
![изображение](https://user-images.githubusercontent.com/11896251/119885033-f9356800-bf39-11eb-82d7-556710ce7f39.png)
Но сразу после этого редактор заменят мою вставку своей - без скобок
![изображение](https://user-images.githubusercontent.com/11896251/119885079-06525700-bf3a-11eb-81ca-edae54c82e4d.png)
Если сразу после этого нажать CTRL+Z, то скобки появляются.

**Comment by salexdv** [comment]
#159
