### ISSUE TITLE
В режиме предприятия не срабатывают горячие клавиши

### ISSUE THREAD

**Issue by sjohnnyv** [salexdv/bsl_console#8]
При использовании обработки console.epf не работают нажатия клавиш ctrl+c, ctrl+v, ctrl+d. При этом эти команды работают, если нажать правую кнопку мышки и выбирать их мышью.
Версия v0.1.5

**Comment by salexdv** [comment]
> При использовании обработки console.epf не работают нажатия клавиш ctrl+c, ctrl+v, ctrl+d. При этом эти команды работают, если нажать правую кнопку мышки и выбирать их мышью.
> Версия v0.1.5

Подскажите, какая версия платформы 1С, ОС и сколько языков раскладки?

**Comment by sjohnnyv** [comment]
Платформа 8.3.15.1778 32х. ОС Win 7 SP1 64х. Языки - английский и русский, не работает для обоих языков.

**Comment by salexdv** [comment]
> Платформа 8.3.15.1778 32х. ОС Win 7 SP1 64х. Языки - английский и русский, не работает для обоих языков.

У вас есть возможность проверить на 8.3.16 и отписаться по результатам?

**Comment by sjohnnyv** [comment]
Проверил. На 8.3.16.1296 работает, на 8.3.15.1778 - нет.

**Comment by salexdv** [comment]
Вот и у меня на 8.3.16 и 8.3.17 работает, а 8.3.15 не хочет. На bugboard.v8.1c.ru ничего по этому поводу пока не нашел. Возможно просто тихо всё это поправили. Пока ситуация такая, что поле html документа в принципе блокирует все горячие клавиши, которые они сами обрабатывают. Какие-нибудь ctrl+r, ctrl+q отлично доходят до webkit и их можно перехватить, а ctrl+c/v просто не доходят. Буду ковырять дальше, возможно, найдется какое-нибудь решение. Спасибо за информацию!

**Comment by salexdv** [comment]
В платформе ниже 8.3.16 нормально не работают нажатия горячих клавишь CTRL+C, CTRL+V и т.п.
Событие keydown просто не доходит до движка, поэтому если очень надо, то можно убрать из actions.js события для копирования/вставки
и в еditor.js реализовать примерно следуюшее:

```javascript
document.addEventListener('keyup', function (e) {    
  if (e.ctrlKey) {
    switch (e.keyCode) {        
      case 67:
        selectionText = editor.getModel().getValueInRange(editor.getSelection());
        e.preventDefault();
        break;
      case 86:
        setText(selectionText, null);
        e.preventDefault();
        break;
      default:
        break;
    }
  }
});
```
Копирование/вставка будет работать только при отпускании сочетания клавиш, но другого решения пока нет.
