### ISSUE TITLE
После инициализации редактор не растягивается вместе с полем

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#80]
Нагляднее всего смотреть этот баг в обычной форме в обычном приложении.  Открыть форму и пока окно формы маленькое, вставить туда большой текст. Затем максимизировать окно формы. При этом область редактора не растягивается вместе с полем.
[Консоль кода HTML.zip](https://github.com/salexdv/bsl_console/files/6412067/HTML.zip)

![изображение](https://user-images.githubusercontent.com/11896251/116824391-8df2b300-ab92-11eb-9435-1fcfe2a8a9ff.png)

**Comment by tormozit** [comment]
Видимо родственная проблема к https://github.com/salexdv/bsl_console/issues/65

**Comment by Evg-lylyk** [comment]
В файле editor.js нужно исправить autolayout : true в конце файла.
Много раз писал автору что это вызывает неудобства,  ссылается что microsoft не рекомендует вкл. растягивание по содержимому.

**Comment by tormozit** [comment]
> В файле editor.js нужно исправить autolayout : true в конце файла.
Хотелось бы более подробной информации, включая как можно исправить.

**Comment by tormozit** [comment]
Пришлось самому искать решение. Нашел тут https://stackoverflow.com/questions/47017753/monaco-editor-dynamically-resizable . Нужно в параметрах вызова функции создания редактора monaco.editor.create указать параметр automaticLayout: true
```
editor = monaco.editor.create(document.getElementById("container"), {
        ...
        automaticLayout: true // the important part
      });

```

**Comment by tormozit** [comment]
Штатные полосы прокрутки убрал через добавление 
```
body {
  overflow: hidden;
}
```
В файл decorations.css

**Comment by tormozit** [comment]
Думаю нужно в поставке также предусмотреть решение этой проблемы хотя бы как опцию. Уверен, большинство будут об нее спотыкаться. Это даже по обсуждениям Monaco видно.

**Comment by salexdv** [comment]
[Вот](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#automaticlayout) что написано в API monaco. 
Установить automaticLayout можно только при инициализации, его нельзя обновить после загрузки редактора. Специально для того, чтобы можно было добавлять свои опции введена фиктивная опция [customOptions](https://github.com/salexdv/bsl_console/blob/d073f64c725c09e76122d69bef64a033b79a2436/src/editor.js#L641). Перед загрузкой исходников в поле HTML-документа её можно заменить на что угодно, в том числе и на automaticLayout

**Comment by tormozit** [comment]
Принято. Сделаю динамическую замену в файлах.

**Comment by tormozit** [comment]
Кстати в функции compare() ты не побоялся включить automaticLayout . Это потому, что там меньше вычислений всяких делается в реальном времени?
![изображение](https://user-images.githubusercontent.com/11896251/117189361-cab6e800-ade6-11eb-9eac-f17046bdff1d.png)
