### ISSUE TITLE
Хотелось бы настройку для отображения табуляций и пробелов

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#81]
![изображение](https://user-images.githubusercontent.com/11896251/116827668-f6e22700-aba2-11eb-9b28-e750ec76ad75.png)

**Comment by salexdv** [comment]
Добавил [функцию](https://github.com/salexdv/bsl_console/blob/develop/docs/whitespaces.md) для включения/отключения

**Comment by tormozit** [comment]
Обрати внимание, что у меня пробелы не отображаются, а табуляции отображаются. Нужно раздельное включение.

**Comment by salexdv** [comment]
> Обрати внимание, что у меня пробелы не отображаются, а табуляции отображаются. Нужно раздельное включение.

monaco позволяет либо включить всё, либо выключить. Других вариантов нет.

**Comment by tormozit** [comment]
Попробовал. Пробелы и табуляции отображаются очень ненавязчиво и практически не затрудняют чтение текста. Понравилось. 
![изображение](https://user-images.githubusercontent.com/11896251/117342908-6eb69700-aeac-11eb-8baa-60b022aad681.png)
