### ISSUE TITLE
Прошу добавить закладки по аналогии с редактором конфигуратора

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#83]
F2 - циклический переход по закладкам
ALT+F2 - установить/снять закладку
![изображение](https://user-images.githubusercontent.com/11896251/116860197-e1541800-ac09-11eb-967b-8bc0645cd050.png)

**Comment by Evg-lylyk** [comment]
Поддерживаю, желательно чтобы их можно было получить и установить через функции

**Comment by salexdv** [comment]
Закладки можно добавлять/удалять двойным кликом в области с номерами строк
Добавлены 4 функции:
* `addBookmark` - Создание закладки в строке с указанным номером						 	 					 
* `removeBookmark` - Удаление закладки из строки с указанным номером						 	 					 
* `goNextBookmark` - Переход к следующей закладке											 	 					 
* `goPreviousBookmark`- Переход к предыдущей закладке

и 2 пункта контекстного меню:
* `Установить/удалить закладку (Alt+F2)`
* `Следующая закладка (F2)`

Закладки работают во всех режимах, но в режиме СКД нет пунктов контекстного меню

**Comment by tormozit** [comment]
Если в последней строке поставить закладку и нажать в ней ENTER, то закладка копируется в новую строку.
Также она копируется при нажатии ENTER, если следующая строка непустая.
Кажется это вредно.

**Comment by salexdv** [comment]
> Если в последней строке текста, которая пустая, поставить закладку и нажать в ней ENTER, то закладка копируется в новую строку. Также она копируется при нажатии ENTER, если следующая строка непустая. В общем слишком часто она копируется нежелательно.

Исправил.
Закладки ведут себя не так, как в конфигураторе, а именно они не переезжают вместе со строкой. Если закладка установлена на 10 строке, он там и останется.

**Comment by tormozit** [comment]
> не переезжают вместе со строкой

Это существенное неудобство. Каждый раз при вставке строки в начало текста все закладки будут съезжать.

**Comment by salexdv** [comment]
> Это существенное неудобство. Каждый раз при вставке строки в начало текста все закладки будут съезжать.

Доработал, но всё равно остается существенный минус, который я пока не придумал, как победить. Undo/Redo (Ctrl+Z/Ctrl+Y) никак не учитывают, что закладки сдвигались при добавлении/удалении строк.

**Comment by tormozit** [comment]
Имеем текст

![изображение](https://user-images.githubusercontent.com/11896251/118083204-2ecd4380-b3c7-11eb-8966-83fe9b065c4e.png)

После нажатия ENTER

![изображение](https://user-images.githubusercontent.com/11896251/118083205-2f65da00-b3c7-11eb-8a65-97dca57dd696.png)

После нажатия Backspace

![изображение](https://user-images.githubusercontent.com/11896251/118083206-2f65da00-b3c7-11eb-8dcf-b6b5805173f1.png)

В стандартном редакторе кода
После нажатия ENTER

![изображение](https://user-images.githubusercontent.com/11896251/118083241-3856ab80-b3c7-11eb-8c26-82d94290eb0e.png)

После нажатия Backspace

![изображение](https://user-images.githubusercontent.com/11896251/118083241-3856ab80-b3c7-11eb-8c26-82d94290eb0e.png)

**Comment by salexdv** [comment]
Посмотри сейчас

**Comment by tormozit** [comment]
На последней и одновременно пустой строке поставленную закладку невозможно убрать.

**Comment by tormozit** [comment]
Стало получше. Но еще много косяков.
Переход по закладкам должен устанавливать курсор на первую колонку строки. Сейчас же он так не делает. Еще в большом тексте он курсор ставит вообще мимо - на строках, где нет закладок. Позже сделаю примеры.

**Comment by tormozit** [comment]
Мой предыдущий пример воспроизвелся в точности. Возможно я как то неправильно обновился. Но обрезанная статусная строка у меня появилась.

**Comment by tormozit** [comment]
заработало

**Comment by tormozit** [comment]
Вызов метода updateText() должен очищать закладки.

**Comment by tormozit** [comment]
Могу конечно и сам вызывать removeBookmark() для каждой строки текста после вызова updateText() , но кажется это нужно всем и сделать очень просто.

**Comment by salexdv** [comment]
> Могу конечно и сам вызывать removeBookmark() для каждой строки текста после вызова updateText() , но кажется это будут лишние вычисления и нужно всем и сделать внутри редактора очень просто и работать будет быстрее.

Не надо. Закладки я доработаю. Там довольно много работы, много заморочек.

**Comment by Evg-lylyk** [comment]
Для примера текст запроса, вызывается конструктор после обновления текст закладки пропадут.
У меня в функции Преобразовать во вложенный вычисляется новый текст и заменяется целиком.

Понятно, что в новом тексте закладки могут потерять актуальность, но все таки некоторые останутся.
Я за то чтобы пока подождать.

**Comment by salexdv** [comment]
> Вызов метода updateText() должен очищать закладки.

> Для примера текст запроса, вызывается конструктор после обновления текст закладки пропадут.
> У меня в функции Преобразовать во вложенный вычисляется новый текст и заменяется целиком.
> 
> Понятно, что в новом тексте закладки могут потерять актуальность, но все таки некоторые останутся.
> Я за то чтобы пока подождать.

Я за то, чтобы `UpdateText` выполняла свою функцию, а `removeBookmark` свою. Модель использования у всех может быть разная, поэтому каждый должен сам решать, очищать ему закладки или нет при обновлении текста.

**Comment by tormozit** [comment]
Тогда нужен простой способ удалить все закладки.

**Comment by tormozit** [comment]
Ну и можно метод UpdateText  научить находить перемещение строк старого и нового текста по аналогии с режимом отображения изменений в тексте. На основе сопоставления старого и нового текста уже можно переносить/удалять/сохранять закладки.

**Comment by salexdv** [comment]
> Тогда нужен простой способ удалить все закладки.

Метод для удаления всех закладок, конечно, будет.

**Comment by salexdv** [comment]
Для удаления всех закладок добавил функцию `removeBookmarks`

**Comment by tormozit** [comment]
Метод removeBookmarks() работает. Вместе с тем и без него теперь при вызове updateText(getText()) удаляются все закладки кроме закладки на первой строке.

![изображение](https://user-images.githubusercontent.com/11896251/119724006-d0986a00-be76-11eb-8d61-6a673aa5d3a9.png)


![изображение](https://user-images.githubusercontent.com/11896251/119724007-d0986a00-be76-11eb-8547-4e227cca3339.png)

**Comment by salexdv** [comment]
> Вместе с тем и без него теперь при вызове updateText(getText()) удаляются все закладки кроме закладки на первой строке.

Исправил. 
Логика работы закладок при программном обновлении текста такая:
1. При вызове `eraseText` закладки удаляются полностью
2. При вызове `updateText` c пустым текстом закладки удаляются полностью
3. При вызове `updateText` c заполненным текстом удаляются закладки, номеров строк для которых больше не существует. Например, в редакторе было 20 строк и закладки были установлены на 5 и 19 строках. После вызова `updateText` осталось только 12 строк. Закладка на 19 строке будет удалена.

Если по какой-то причине нужно избежать удаления закладок, рекомендуется использовать методы `getBookmarks` и `addBookmark`

**Comment by Evg-lylyk** [comment]
Может функцию удаления все закладок лучше назвать removeAllBookmarks
иначе очень похожие названия removeBookmarks, removeBookmark

**Comment by salexdv** [comment]
> Может функцию удаления все закладок лучше назвать removeAllBookmarks
> иначе очень похожие названия removeBookmarks, removeBookmark

Поддержу
