### ISSUE TITLE
Параметры события (свойство "eventData1C") содержат 2 свойства "trigger". В чем разница между ними?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#84]
В моих опытах верхнее свойство "trigger" всегда содержало "Неопределено".
![изображение](https://user-images.githubusercontent.com/11896251/116871898-a956d000-ac1d-11eb-9f4f-b2c7e3c0d3a5.png)

**Comment by salexdv** [comment]
Я заполняю trigger, который в поле params. Тот, который относится к событию всегда будет Неопределено. На него можно не обращать внимания.

**Comment by tormozit** [comment]
Просто я, думаю как и многие, сначала ко внешнему обращался, не поняв сразу что их 2. Возникла потеря времени. Если бы ты верхний удалил, думаю было бы здорово.

**Comment by salexdv** [comment]
> Если бы ты верхний удалил, думаю такого не произошло бы.

К сожалению, я не могу никак на него повлиять
