### ISSUE TITLE
Делать автоотступ после ввода конца строки после ключевых слов Пока, Цикл, Если, Тогда, Попытка, Исключение

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#88]
Конфигуратор и встроенный редактор после ввода конца строки после ключевых слов Пока, Цикл, Если, Тогда, Исключение, Попытка автоматически добавляют табуляциями смещение из предыдущей строки + 1 табуляция. Это полезно. Хотелось бы от твоего редактора такой же встроенной возможности
![изображение](https://user-images.githubusercontent.com/11896251/117096712-93a6ef00-ad72-11eb-909c-d941944128dc.png)

**Comment by salexdv** [comment]
Добавил такой функционал

**Comment by salexdv** [comment]
После доработки появилась возможность двигать блоки и отступы будут вычисляться автоматически
![kY0jJNLirj](https://user-images.githubusercontent.com/6356534/117974084-d5690400-b335-11eb-859c-c32805813f94.gif)

**Comment by Evg-lylyk** [comment]
Отлично, спасибо

**Comment by tormozit** [comment]
Может для единообразия тогда и при вставке из буфера обмена тоже подбирать смещение подходящее?

**Comment by salexdv** [comment]
> Заработало. Может для единообразия тогда и при вставке многострочного фрагмента из буфера обмена тоже подбирать смещение подходящее?

При вставке, к сожалению, не работает.
