### ISSUE TITLE
CTRL+ЛевыйКлик должен выделять слово

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#89]
Конфигуратор и встроенный редактор кода при выполнении на идентификаторе в тексте щелчка левой кнопкой мыши с зажатой клавишей CTRL выделяют его целиком. Твой же редактор делает ничего. Прошу сделать такое же поведение.

**Comment by tormozit** [comment]
Заработало. Но появилось небольшое неудобство. Если курсор мыши случайно задержать на переменной ниже нужного для выделения слова, то появляется подсказка при удержании курсора (Hover) и загораживает целевое слово. Если же я делаю левый клик на это подсказке, то она не исчезает. Поэтому предлагаю при зажатом CTRL не отображает подсказки при удержании курсора (Hover).

**Comment by salexdv** [comment]
> 1. при зажатом CTRL не отображать подсказки при удержании курсора (Hover)

Пока реализовал только этот пункт. Возможно, этого будет достаточно. Можешь проверить?

**Comment by tormozit** [comment]
1. Заработало
2. Если затратно, то можно не делать, т.к. п.1 убирает намного больше неудобств.
