### ISSUE TITLE
Подсказка по функциям общих модулей

### ISSUE THREAD

**Issue by Evg-lylyk** [salexdv/bsl_console#9]
Один из сценариев консоли кода это запуск какой то процедуры из общего модуля
Модули получить из метаданных не сложно, а вот функции уже сложнее
нужно выгрузить тексты модулей (/DumpConfigFiles <каталог выгрузки> -Module) и собрать по ним подсказку
это может длится долго

**Comment by salexdv** [comment]
У меня есть мысль сделать такое. Тут либо через конфигуратор выгружать, либо cf выбирать и через v8unpack извлекать.

**Comment by Evg-lylyk** [comment]
Можно закрывать на текущих возможностях платформа нормально это не сделать
