### ISSUE TITLE
Подсказка по вызову метода выделяет жирным последнее вхождение имени параметра без учета границ слова

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#92]
Обозначение положения текущего параметра относительно других - важная функция подсказки по вызову метода. Но в твоей реализации она работает часто некорректно.
Например есть текст
`ирОбщий.ОтладитьЛкс(
`
и сразу после ввода скобки открывается подсказка по вызову метода, которая правильно определяет номер параметра 1 (индекс 0), берет его имя "Объект" и выделяет жирным его последнее вхождение в описании сигнатуры, но не учитывает при этом границы слова.
(`Объект, !Модально? [Булево], `Объект2? [НастройкиКомпонов...], `ВнешниеНаборыДанных? [Структура, *Неопр...], !ОтложенноеВыполнение?, !ДопустимоеЧислоСтрокВоВременнойТаблицеОтложеннойОтладки? [Число, *500000], !вых**Объект**ДляОтладки?, !Наименование? [Строка])

![изображение](https://user-images.githubusercontent.com/11896251/117330551-7b33f300-ae9e-11eb-8394-9f6a59a5be44.png)

Для родной твоей структуры подсказки сигнатуры аналогичная проблема:
![изображение](https://user-images.githubusercontent.com/11896251/117337769-72471f80-aea6-11eb-8dd0-afd928a0569e.png)

А вот как выглядит аналогичная функция в VSCode 
![изображение](https://user-images.githubusercontent.com/11896251/117332147-23968700-aea0-11eb-86fb-5793025854a9.png)

Там выделяется целиком весь фрагмент, описывающий параметр, т.е. там поиск фрагмента для выделения предполагаю реализован более интеллектуально. Однако очевидно, чтобы это корректно работало для твоего и моего способа формирования представления сигнатуры, придется использовать общие разделители/маркеры/привязки между параметрами в этой строке.

Вариант 1 - самый универсальный и надежный
Я буду передавать в описании каждого параметра свойство "Позиция" первого символа описания параметра в строке сигнатуры. А ты для своих сигнатур исправляешь как удобнее.

Вариант 2
Использовать регулярное выражение [^_ЁА-ЯA-Z0-9]<ИмяПараметра>[^_ЁА-ЯA-Z0-9\]] для поиска имени параметра в сигнатуре. Оно будет некорректно работать в некоторых редких случаях для обоих наших вариантов формирования представления сигнатуры, но их будет приемлемо мало.

**Comment by salexdv** [comment]
Исправил и доработал [пример](https://github.com/salexdv/bsl_console/blob/develop/docs/set_custom_signatures.md). В label для параметра надо передавать полное название, как оно описано в сигнатуре

**Comment by salexdv** [comment]
Если в данный момент ты стоишь на параметре номер 2 и у тебя в label для данного параметра указано "ТЗ?: ТаблицаЗначений", то именно это значение и будет выделено. Выделаяется label параметра, если он присутствует в label описания всех параметров

**Comment by tormozit** [comment]
Конечно я имел ввиду параметр №1. Его label="ТаблицаЗначений"

**Comment by salexdv** [comment]
При выделение всегда учитывается номер параметра и его label. Если label найден в описании сигнатуры и он совпадает с номером текущего параметра, тогда всё будет ок. В твоем примера для первого параметра будет так
**(ТаблицаЗначений**, ТЗ?: ТаблицаЗначений, Ф)
для второго так
(ТаблицаЗначений, **ТЗ?: ТаблицаЗначений**, Ф)

**Comment by tormozit** [comment]
Понял. Просто подумал, что ты будешь искать вхождение строки из label ("ТаблицаЗначений") и тогда было бы опять ложное срабатывание на типе "ТаблицаЗначений".

**Comment by tormozit** [comment]
Проверил. Все равно работает не достаточно корректно. Передал такое описание метода
[Clip_240304.txt](https://github.com/salexdv/bsl_console/files/6451307/Clip_240304.txt)

На первой же позиции параметра вижу

![изображение](https://user-images.githubusercontent.com/11896251/117644205-ed078780-b191-11eb-98e1-f2a70862fb08.png)

**Comment by salexdv** [comment]
> Предлагаю все же рассмотреть мой вариант 1 - самый универсальный и надежный.
> Я буду передавать в описании каждого параметра свойство "Позиция" первого символа описания параметра в строке сигнатуры.

Monaco не предоставляет никакого другого API для работы с описаниями методов. Если реализовывать твой вариант, то это будет очень большой велосипед. 
Данная [ошибка](https://github.com/microsoft/monaco-editor/issues/1986) была исправлена в версии редактора 0.22.0, но, к сожалению, по невыясненным причинам более новые версии пока не удается запустить в webkit внутри 1С. В браузере всё работает без проблем.

**Comment by tormozit** [comment]
> новые версии пока не удается запустить в webkit внутри 1С

Доложил об этом разработчику платформы?

**Comment by salexdv** [comment]
Посмотри сейчас, должно работать корректно

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
Проблема снова появлилась https://github.com/salexdv/bsl_console/issues/184#issuecomment-864568841

**Comment by salexdv** [comment]
Достаточно одного открытого issue.
