### ISSUE TITLE
Подсказка по вызову метода не должна скакать в высоту при расположении выше курсора 

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#93]
Одним из самых раздражающих пользователя действий программы является частое перемещение верхнего края окна. Если твоя подсказка по вызову метода открывается ниже курсора, то при различной высоте окна для разных параметров это не доставляет неудобств, т.к. скачет только нижний край окна. Но если окно подсказки открывается выше области ввода, то начинает скакать его верхняя граница при изменении содержимого окна. Это очень раздражает. Предлагаю в это случае сразу вычислять максимальную высоту окна, пробуя "строить" его для каждого параметра. Тогда оно будет иногда содержать некрасивую пустоту в нижней части, но зато всегда не будет скакать.

![изображение](https://user-images.githubusercontent.com/11896251/117336790-40818900-aea5-11eb-9752-c1601dfdc0fa.png)

![изображение](https://user-images.githubusercontent.com/11896251/117336789-40818900-aea5-11eb-9d30-cfa999dc0586.png)

**Comment by salexdv** [comment]
Не очень понял, что значит "скакать", то что изменяется размер при переходе от одного параметра к другому? Это monaco так делает и влиять я на это без костылей никак не могу. Мне такое поведение не кажется раздражающим VSCode, например, так себя и ведёт

**Comment by tormozit** [comment]
> что изменяется размер при переходе от одного параметра к другому?

Да. VSCode действительно ведет себя также. Но это не отменяет проблемы которую я описал. Причем это не просто мой каприз. Я знаю точно о том что много и менее притязательных пользователей на такие скакания жалуются в различных программах. Человек читает сверху вниз и потому вверху находится самая важная информация в таких маленьких окнах. А частые перемещения это линии ты просто еще не встречал похоже. Поэтому тебя это не сильно волнует. 
Например для вызова следующей функции проблема стоит довольно остро.

```
// Открывает нужную консоль для редактирования сложного объекта. 
// Варианты использования в зависимости от типа параметра Объект:
//   Запрос, COMОбъект, HttpСоединение - открывает Запрос или ADODB.Command или ADODB.Connection в консоли запросов
//   ПостроительЗапроса - открывает результирующий запрос построителя запросов в консоли запросов
//   ПостроительОтчета - открывает построитель отчета в консоли построителей отчетов, откуда можно открыть результирующий запрос построителя отчета в консоли запросов
//   СхемаКомпоновки - открывает схему компоновки в консоли компоновки данных, откуда можно открыть результирующие (из макета компоновки) запросы в консоли запросов
//   МакетКомпоновкиДанных - открывает запросы макета компоновки в консоли запросов
//   ОтчетОбъект - открывает схему и настройки компоновки отчета в консоли компоновки данных, откуда можно открыть результирующие (из макета компоновки) запросы в консоли запросов
//   РегистрСведенийНаборЗаписей - открывает группировку таблицы набора записей по измерениям
//
// Параметры:
//  Объект       – Запрос, ПостроительЗапроса, ПостроительОтчета, СхемаКомпоновкиДанных, МакетКомпоновкиДанных, ОтчетОбъект, ADODB.Command, ADODB.Connection, HttpСоединение,
//                      РегистрСведенийНаборЗаписей, ДинамическийСписок, ТаблицаФормы - исследуемый объект;
//  Модально     – Булево - открывать окно модально, должно быть Истина для использования функции в отладчике;
//  Объект2      - НастройкиКомпоновкиДанных, Строка, *Неопределено - 
//                      если первый параметр СхемаКомпоновкиДанных, то настройки компоновки,
//                      если первый параметр WMI или ADODB.Connection, то текст запроса,
//                      если первый параметр HttpСоединение, то HttpЗапрос,
//                      если первый параметр Запрос, имена временных таблиц разделенных запятыми;
//  ВнешниеНаборыДанных - Структура, *Неопределено - внешние наборы данных для схемы компоновки;
//  ОтложеннаяОтладка - Булево - на сервере игнорируется (равно Истина), вместо открытия инструмента отладки сразу выполняется помещение
//                      объектов отладки во временное хранилище;
//  ДопустимоеЧислоСтрокВоВременнойТаблицеОтложеннойОтладки - Число, *500000 - допустимое количество строк во всех временных таблицах запроса
//                      для отложенной отладки, больше этого количества строки не сохраняются, о чем сообщается в результате;
//  Наименование - Строка - наименование сохраняемого объекта отложенной отладки;
//
// Возвращаемое значение:
//  Неопределено.
//
Функция ОтладитьЛкс(Знач Объект, Модально = Ложь, Знач Объект2 = Неопределено, Знач ВнешниеНаборыДанных = Неопределено,
	ОтложенноеВыполнение = Ложь, ДопустимоеЧислоСтрокВоВременнойТаблицеОтложеннойОтладки = 500000, выхОбъектДляОтладки = Неопределено, Наименование = "") Экспорт 

```
Проблема не критичная. Ее можно смело отнести ко второстепенным. 
Быть может есть какой то простой способ заставить окно отображаться всегда снизу пусть даже с выездом за рабочую область?

**Comment by salexdv** [comment]
> Быть может есть какой то простой способ заставить окно отображаться всегда снизу пусть даже с выездом за рабочую область?

Простого способа сделать это нет т.к. monaco вообще не предоставляет никакого API для управления данным окном. Можно попробовать поиграться с DOM-элементами, но это очень будет похоже на костыль.

**Comment by tormozit** [comment]
> Простого способа сделать это нет т.к. monaco вообще не предоставляет никакого API для управления данным окном. Можно попробовать поиграться с DOM-элементами, но это очень будет похоже на костыль.

Ясно. Ну и сама моя идея с выездом за рабочую (видимую) область - тоже костыль. Садить костыль на костыль точно не стОит.
