### ISSUE TITLE
В версии 05.05.2021 появилось залипание окна подсказки по вызыву метода

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#94]
Надо сначала вызывать подсказку по вызову известного метода, затем ее закрыть, затем вызвать подсказку у любого другого неизвестного метода. При этом откроется окно подсказки, как будто курсор стоит в последнем положении, где подсказка была вызвана для известного метода. Открывшееся таким образом окно подсказки не будет закрываться всеми известными мне способами (например выводом курсора из области параметров метода). Помогает только поиск известного подсказке метода и вызов для него подсказки.
```
Сообщить(
Думка(
```
![изображение](https://user-images.githubusercontent.com/11896251/117341613-06b38100-aeab-11eb-90ce-90f998b81b1e.png)

**Comment by salexdv** [comment]
Исправил

**Comment by tormozit** [comment]
Заработало.
