### ISSUE TITLE
Метод hideSignatureList не закрывает окно подсказки по вызову метода

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#95]
Событие вызывается, метод выполняется, но окно подсказки остается видимым
```
	РедакторHTML.enableBeforeSignatureEvent(Истина);
...
		ИначеЕсли Событие.event = "EVENT_BEFORE_SIGNATURE" Тогда
				РедакторHTML.hideSignatureList();
```
![изображение](https://user-images.githubusercontent.com/11896251/117397876-c9c8a800-af05-11eb-91b3-479799311d12.png)

**Comment by salexdv** [comment]
Попробуй сейчас

**Comment by tormozit** [comment]
Не заработало

**Comment by salexdv** [comment]
Доработал. Сейчас всё должно отрабатывать корректно.

**Comment by tormozit** [comment]
Вроде заработало. Хотя пару раз все таки она не закрывалась. Но возможно проблема была в моем коде.
