### ISSUE TITLE
При нажатие ENTER создавать отступ в новой строке из табуляций, а не из пробелов как сейчас

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#96]
Как видно на картинке
![изображение](https://user-images.githubusercontent.com/11896251/117485320-ecdc7180-af70-11eb-9de3-ffecd99875f1.png)
курсор после нажатия ENTER перешел на новую строку и сместился вправо на ту позцию, с которой начинается предыдущая строка. Но при этом отступ сформировался из пробелов, а должен максимально заполняться табуляциями и остаток уже пробелами. Так в частности делает встроенный редактор платформы.

**Comment by salexdv** [comment]
> при этом отступ сформировался из пробелов, а должен максимально заполняться табуляциями и остаток уже пробелами

Не наблюдаю такой проблемы.
![n3vYYCluwi](https://user-images.githubusercontent.com/6356534/117793258-b9416600-b254-11eb-9aa1-dbd8ff27c851.gif)
Есть алгоритм воспроизведения?

**Comment by tormozit** [comment]
У меня еще при нажатии клавиши TAB вставляется 4 пробела вместо табуляции. Видимо в этом корень проблемы. 

```
	Инфо = Новый СистемнаяИнформация();
	РедакторHTML.minimap(Ложь);
	//РедакторHTML.switchQueryMode();
	РедакторHTML.init(Инфо.ВерсияПриложения);
	РедакторHTML.enableBeforeSignatureEvent(Истина);
	РедакторHTML.enableSuggestActivationEvent(Истина);
	РедакторHTML.enableBeforeShowSuggestEvent(Истина);
	РедакторHTML.enableSelectSuggestEvent(Истина);
	РедакторHTML.enableModificationEvent(Истина);
	РедакторHTML.enableBeforeHoverEvent(Истина);
	//РедакторHTML.showStatusBar();
	РедакторHTML.renderWhitespace(Истина);
	РедакторHTML.setFontSize(13);
	РедакторHTML.setFontFamily("Lucida Console");
```

**Comment by tormozit** [comment]
да

**Comment by tormozit** [comment]
Нет. В поле текстового документа вставляется табуляция.
![изображение](https://user-images.githubusercontent.com/11896251/117805828-1a236b00-b262-11eb-875a-830e7847d92b.png)

**Comment by salexdv** [comment]
> Нет. В поле текстового документа вставляется табуляция.

Тогда мыслей по поводу решения у меня пока нет.
![L7irvIhxuV](https://user-images.githubusercontent.com/6356534/117811810-b2711e00-b269-11eb-9bbe-9800643df7c2.gif)

**Comment by tormozit** [comment]
У тебя видимо включена настройка замены табуляций на пробелы.
![изображение](https://user-images.githubusercontent.com/11896251/117812915-13e5bc80-b26b-11eb-8fd1-66f4e81d027e.png)

**Comment by tormozit** [comment]
В браузере Firefox в dev ветке сейчас воспроизводится проблема.

**Comment by salexdv** [comment]
Попробуй сейчас

**Comment by tormozit** [comment]
Заработало
