### ISSUE TITLE
Хочу возможность обозначать гиперссылки в тексте всплывающих окон и событие для обработки клика по ним

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#97]
Например есть переменная "ТЗ". Отображаю при наведении ее подсказку
![изображение](https://user-images.githubusercontent.com/11896251/117535478-9ae22d00-affe-11eb-84f2-71c1f4076e67.png)
Хочу обозначить гиперссылкой в ней весь текст. Желательно чтобы с зажатой клавишей CTRL/ALT можно было кликать/выделять без перехода по гиперссылке. При клике по гиперссылке с переходом хочу получать событие ПриНажатииГиперссылки и получать в его параметрах 
- выражение, для которого отображается подсказка
- текст/идентификатор гиперссылки

**Comment by salexdv** [comment]
Добавил генерацию события *EVENT_ON_LINK_CLICK*. К сожалению, нет возможности при отправке события передавать выражение, для которого отображается подсказка.
Передать ссылку можно вот так:
```js
// Передача фейковой ссылки
setCustomHovers(`{
    "ТаблицаКонтрагентов": "[Таблица](СсылкаНаТаблицу), содержащая всех контрагентов"
}`)
// Вернет
{
    "label": "Таблица",
    "href": "СсылкаНаТаблицу"
}

// Передача реальной ссылки
setCustomHovers(`{
    "ТаблицаКонтрагентов": "[Таблица](http://example.com), содержащая всех контрагентов"
}`)
// Вернет
{
    "label": "Таблица",
    "href": "http://example.com"
}

```
Предотвратить переход по реальной ссылке нельзя.

**Comment by tormozit** [comment]
Заработало

**Comment by tormozit** [comment]
Теперь еще бы скрыть окно подсказки после нажатия гиперссылки.

**Comment by salexdv** [comment]
> Теперь еще бы возможность скрыть окно подсказки после нажатия гиперссылки.

hideHoverList не помогает?

**Comment by tormozit** [comment]
hideHoverList помогает. Мне становится сложно следить за расширением состава экспортируемых методов, т.к. нет общего списка.

**Comment by salexdv** [comment]
> Мне становится сложно следить за расширением состава экспортируемых методов, т.к. нет общего списка.

Список методов я стараюсь оперативно поддерживать в [readme](https://github.com/salexdv/bsl_console/blob/develop/README.md)

**Comment by tormozit** [comment]
Мой косяк. Я смотрел readme в ветке master.
